WITH RECURSIVE D AS
(
  SELECT *, 0 AS DEPTH FROM GRID_REPLICA_ARR WHERE 
  	SESSION_ID = :sessionId
	AND REPLICA_ID = :replicaId
	AND ARR_REP = :arrayRep
	AND ARR_SEQ = :arraySeq
	AND REF_REP = :arrayRep
	AND REF_SEQ = :arraySeq
  UNION ALL 
  SELECT D1.*, D.DEPTH + 1 AS DEPTH FROM D INNER JOIN GRID_REPLICA_ARR D1 ON (
	D.SESSION_ID = D1.SESSION_ID
	AND D.REPLICA_ID = D1.REPLICA_ID
	AND D.ARR_REP = D1.ARR_REP
	AND D.ARR_SEQ = D1.ARR_SEQ
	AND D.NODE_REP = D1.REF_REP
	AND D.NODE_SEQ = D1.REF_SEQ
	)
)
SELECT D.DEPTH AS `INDEX`,
	D.NODE_REP, D.NODE_SEQ,
    O1.OBJ_REP, O1.OBJ_SEQ,
    V1.VEC_REP, V1.VEC_SEQ,
	JSON_ARRAY(%s) AS VALS,
	O2.OBJ_REP, O2.OBJ_SEQ,
	O3.OBJ_REP, O3.OBJ_SEQ, O3.OBJ_VAL,
	O4.OBJ_REP, O4.OBJ_SEQ, O4.OBJ_VAL
  FROM D JOIN GRID_REPLICA_OBJ O1 ON  (
	D.SESSION_ID = O1.SESSION_ID 
    AND D.REPLICA_ID = O1.REPLICA_ID 
    AND D.DATA_REP = O1.OBJ_REP 
    AND D.DATA_SEQ = O1.OBJ_SEQ
) JOIN GRID_REPLICA_VEC V1 ON (
	D.SESSION_ID = V1.SESSION_ID 
    AND D.REPLICA_ID = V1.REPLICA_ID
    AND JSON_EXTRACT(O1.OBJ_VAL, '$.data[0]') = V1.VEC_REP
    AND JSON_EXTRACT(O1.OBJ_VAL, '$.data[1]') = V1.VEC_SEQ
) JOIN GRID_REPLICA_OBJ O2 ON (
	D.SESSION_ID = O2.SESSION_ID 
    AND D.REPLICA_ID = O2.REPLICA_ID
    AND JSON_EXTRACT(O1.OBJ_VAL, '$.metadata[0]') = O2.OBJ_REP
    AND JSON_EXTRACT(O1.OBJ_VAL, '$.metadata[1]') = O2.OBJ_SEQ
) LEFT JOIN GRID_REPLICA_OBJ O3 ON (
	D.SESSION_ID = O3.SESSION_ID 
    AND D.REPLICA_ID = O3.REPLICA_ID
    AND JSON_EXTRACT(O2.OBJ_VAL, '$.synapseRow[0]') = O3.OBJ_REP
    AND JSON_EXTRACT(O2.OBJ_VAL, '$.synapseRow[1]') = O3.OBJ_SEQ
) LEFT JOIN GRID_REPLICA_OBJ O4 ON (
	D.SESSION_ID = O4.SESSION_ID 
    AND D.REPLICA_ID = O4.REPLICA_ID
    AND JSON_EXTRACT(O2.OBJ_VAL, '$.rowValidation[0]') = O4.OBJ_REP
    AND JSON_EXTRACT(O2.OBJ_VAL, '$.rowValidation[1]') = O4.OBJ_SEQ
)
%s ORDER BY DEPTH ASC LIMIT :limit OFFSET :offset;	