WITH RECURSIVE D AS
(
  SELECT *, 0 AS DEPTH FROM GRID_REPLICA_ARR WHERE 
  	SESSION_ID = :sessionId
	AND REPLICA_ID = :replicaId
	AND ARR_REP = :arrayRep
	AND ARR_SEQ = :arraySeq
	AND REF_REP = :arrayRep
	AND REF_SEQ = :arraySeq
  UNION ALL 
  SELECT D1.*, D.DEPTH + 1 AS DEPTH FROM D INNER JOIN GRID_REPLICA_ARR D1 ON (
	D.SESSION_ID = D1.SESSION_ID
	AND D.REPLICA_ID = D1.REPLICA_ID
	AND D.ARR_REP = D1.ARR_REP
	AND D.ARR_SEQ = D1.ARR_SEQ
	AND D.NODE_REP = D1.REF_REP
	AND D.NODE_SEQ = D1.REF_SEQ
	)
),
GRID AS (
  SELECT D.DEPTH AS `INDEX`,
	D.NODE_REP AS AN_REP, D.NODE_SEQ AS AN_SEQ,
    O1.OBJ_REP AS RO_REP, O1.OBJ_SEQ AS RO_SEQ,
    V1.VEC_REP AS VEC_REP, V1.VEC_SEQ AS VEC_SEQ,
	JSON_ARRAY(%s) AS VALS,
	O2.OBJ_REP AS MO_REP, O2.OBJ_SEQ AS MO_SEQ,
	O2.OBJ_VAL->>'$.synapseRow[0]' AS SRC_REP,
	O2.OBJ_VAL->>'$.synapseRow[1]' AS SRC_SEQ,
	O2.OBJ_VAL->>'$.rowValidation[0]' AS RVC_REP,
	O2.OBJ_VAL->>'$.rowValidation[1]' AS RVC_SEQ,
	CO1.CON_VAL->>'$[0]' AS VAL_RES,
    CO2.CON_VAL->>'$[0]' AS SYN_ROW
  FROM D JOIN GRID_REPLICA_OBJ O1 ON  (
	D.SESSION_ID = O1.SESSION_ID 
    AND D.REPLICA_ID = O1.REPLICA_ID 
    AND D.DATA_REP = O1.OBJ_REP 
    AND D.DATA_SEQ = O1.OBJ_SEQ
  ) JOIN GRID_REPLICA_VEC V1 ON (
	D.SESSION_ID = V1.SESSION_ID 
    AND D.REPLICA_ID = V1.REPLICA_ID
    AND CAST(O1.OBJ_VAL->>'$.data[0]' AS UNSIGNED) = V1.VEC_REP
    AND CAST(O1.OBJ_VAL->>'$.data[1]' AS UNSIGNED) = V1.VEC_SEQ
  ) LEFT JOIN GRID_REPLICA_OBJ O2 ON (
	D.SESSION_ID = O2.SESSION_ID 
    AND D.REPLICA_ID = O2.REPLICA_ID
    AND CAST(O1.OBJ_VAL->>'$.metadata[0]' AS UNSIGNED) = O2.OBJ_REP
    AND CAST(O1.OBJ_VAL->>'$.metadata[1]' AS UNSIGNED) = O2.OBJ_SEQ
  ) LEFT JOIN GRID_REPLICA_CON CO1 ON (
	D.SESSION_ID = CO1.SESSION_ID 
    AND D.REPLICA_ID = CO1.REPLICA_ID
    AND CAST(O2.OBJ_VAL->>'$.rowValidation[0]' AS UNSIGNED) = CO1.CON_REP
    AND CAST(O2.OBJ_VAL->>'$.rowValidation[1]' AS UNSIGNED) = CO1.CON_SEQ
  ) LEFT JOIN GRID_REPLICA_CON CO2 ON (
	D.SESSION_ID = CO2.SESSION_ID 
    AND D.REPLICA_ID = CO2.REPLICA_ID
    AND CAST(O2.OBJ_VAL->>'$.synapseRow[0]' AS UNSIGNED) = CO2.CON_REP
    AND CAST(O2.OBJ_VAL->>'$.synapseRow[1]' AS UNSIGNED) = CO2.CON_SEQ
 )
 	WHERE IS_DELETED IS FALSE
)
%s	