repos:
  - repo: https://github.com/awslabs/git-secrets
    rev: b9e96b3212fa06aea65964ff0d5cda84ce935f38
    hooks:
      - id: git-secrets
        entry: git-secrets
        args: [--scan, --recursive]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0
    hooks:
      - id: yamllint
