package org.sagebionetworks.repo.model.dbo.persistence;

import static org.sagebionetworks.repo.model.query.jdo.SqlConstants.*;

import org.sagebionetworks.repo.model.dbo.AutoTableMapping;
import org.sagebionetworks.repo.model.dbo.DatabaseObject;
import org.sagebionetworks.repo.model.dbo.Field;
import org.sagebionetworks.repo.model.dbo.Table;
import org.sagebionetworks.repo.model.dbo.TableMapping;

@Table(name = TABLE_PRINCIPAL_PREFIX, constraints = { "index PREFIX_TOKEN_INDEX (" + COL_PRINCIPAL_PREFIX_TOKEN +")" })
public class DBOPrincipalPrefix implements DatabaseObject<DBOPrincipalPrefix>{
	
	private static TableMapping<DBOPrincipalPrefix> mapping = AutoTableMapping.create(DBOPrincipalPrefix.class);

	@Field(name = COL_PRINCIPAL_PREFIX_TOKEN, nullable = false, varchar = 256)
	private String token;
	@Field(name = COL_PRINCIPAL_PREFIX_PRINCIPAL_ID, nullable = false)
	private Long principalId;
	@Field(name = COL_PRINCIPAL_PREFIX_ID, nullable = false, primary=true, autogenerated=true)
	private Long id;
	
	@Override
	public TableMapping<DBOPrincipalPrefix> getTableMapping() {
		return mapping;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public Long getPrincipalId() {
		return principalId;
	}

	public void setPrincipalId(Long principalId) {
		this.principalId = principalId;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result
				+ ((principalId == null) ? 0 : principalId.hashCode());
		result = prime * result + ((token == null) ? 0 : token.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DBOPrincipalPrefix other = (DBOPrincipalPrefix) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (principalId == null) {
			if (other.principalId != null)
				return false;
		} else if (!principalId.equals(other.principalId))
			return false;
		if (token == null) {
			if (other.token != null)
				return false;
		} else if (!token.equals(other.token))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "DBOPrincipalPrefix [token=" + token + ", principalId="
				+ principalId + ", id=" + id + "]";
	}

}
