package org.sagebionetworks.table.cluster.facets;


import java.sql.ResultSet;

import org.sagebionetworks.repo.model.table.FacetColumnResult;

public interface FacetTransformer2 {

	/**
	 * Returns the name of the column for which this transformer is responsible.
	 * @return
	 */
	public String getColumnName();

	/**
	 * Generates a SQL query to get facet information based on the original query
	 * @param originalQuery
	 * @return
	 */
	public String getFacetQuery();

	/**
	 * translates the result obtained after running the query generated by generateSqlQuery()
	 * @param rowSet
	 * @return
	 */
	public FacetColumnResult translateResults(ResultSet resultSet);
}
