CREATE TABLE IF NOT EXISTS `ACCESS_REQUIREMENT_PROJECT` (
  `AR_ID` BIGINT NOT NULL,
  `PROJECT_ID` BIGINT NOT NULL,
  PRIMARY KEY (`AR_ID`,`PROJECT_ID`),
  CONSTRAINT FOREIGN KEY (`AR_ID`) REFERENCES `ACCESS_REQUIREMENT` (`ID`) ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY (`PROJECT_ID`) REFERENCES `JDONODE` (`ID`) ON DELETE CASCADE
)
