CREATE TABLE IF NOT EXISTS `ACL` (
  `ID` bigint(20) NOT NULL,
  `OWNER_ID` bigint(20) NOT NULL,
  `OWNER_TYPE`  ENUM('ENTITY', 'EVALUATION', 'TEAM'),
  `ETAG` char(36) NOT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  PRIMARY KEY (`OWNER_ID`, `OWNER_TYPE`),
  UNIQUE KEY `ACL_BACK_UP_ID` (`ID`)
)
