CREATE TABLE `ACL` (
  `ID` bigint(20) NOT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  `OWNER_ID_COLUMN` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ACL_UNIQUE_RESOURCE` (`OWNER_ID_COLUMN`),
  KEY `ACL_N49` (`OWNER_ID_COLUMN`),
  CONSTRAINT `ACL_OWNER_FK` FOREIGN KEY (`OWNER_ID_COLUMN`) REFERENCES `JDONODE` (`ID`) ON DELETE CASCADE
)