CREATE TABLE IF NOT EXISTS `ACTIVITY` (
  `ID` BIGINT NOT NULL,
  `ETAG` char(36) NOT NULL,  
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` BIGINT NOT NULL,
  `MODIFIED_BY` BIGINT NOT NULL,
  `MODIFIED_ON` BIGINT NOT NULL,
  `SERIALIZED_OBJECT` blob,
  PRIMARY KEY (`ID`),
  CONSTRAINT `ACTIVITY_CREATED_BY_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `ACTIVITY_MODIFIED_BY_FK` FOREIGN KEY (`MODIFIED_BY`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE

)
