CREATE TABLE IF NOT EXISTS `ACTIVITY` (
  `ID` bigint(20) NOT NULL,
  `ETAG` char(36) NOT NULL,  
  `CREATED_BY` bigint(20) NOT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  `MODIFIED_BY` bigint(20) NOT NULL,
  `MODIFIED_ON` bigint(20) NOT NULL,
  `SERIALIZED_OBJECT` blob,
  PRIMARY KEY (`ID`),
  CONSTRAINT `ACTIVITY_CREATED_BY_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `JDOUSERGROUP` (`ID`),
  CONSTRAINT `ACTIVITY_MODIFIED_BY_FK` FOREIGN KEY (`MODIFIED_BY`) REFERENCES `JDOUSERGROUP` (`ID`)

)
