CREATE TABLE IF NOT EXISTS `AUTHORIZATION_CONSENT` (
  `ID` BIGINT NOT NULL,
  `ETAG` char(36) NOT NULL,
  `USER_ID` BIGINT NOT NULL,
  `CLIENT_ID` BIGINT NOT NULL,
  `SCOPE_HASH` char(64) NOT NULL,
  `GRANTED_ON` BIGINT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `AUTHORIZATION_CONSENT_USER_ID_FK` FOREIGN KEY (`USER_ID`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `AUTHORIZATION_CONSENT_CLIENT_ID_FK` FOREIGN KEY (`CLIENT_ID`) REFERENCES `OAUTH_CLIENT` (`ID`) ON DELETE CASCADE,
  UNIQUE KEY `AUTHORIZATION_CONSENT_UNIQUE` (`USER_ID`,`CLIENT_ID`,`SCOPE_HASH`)
)
