CREATE TABLE IF NOT EXISTS `MESSAGE_BROADCAST` (
  `CHANGE_NUMBER` bigint(20) NOT NULL,
  `MESSAGE_ID` bigint(20) NOT NULL,
  `SENT_ON` bigint(20) NOT NULL,
  PRIMARY KEY (`CHANGE_NUMBER`),
  CONSTRAINT `BROAD_CHANGE_NUM_FK` FOREIGN KEY (`CHANGE_NUMBER`) REFERENCES `CHANGES` (`CHANGE_NUM`) ON DELETE CASCADE,
  CONSTRAINT `BROAD_MESSAGE_ID_FK` FOREIGN KEY (`MESSAGE_ID`) REFERENCES `MESSAGE_CONTENT` (`ID`) ON DELETE CASCADE
)