CREATE TABLE IF NOT EXISTS `MESSAGE_BROADCAST` (
  `CHANGE_NUMBER` bigint(20) NOT NULL,
  `SENT_ON` bigint(20) NOT NULL,
  PRIMARY KEY (`CHANGE_NUMBER`),
  CONSTRAINT `BROAD_CHANGE_NUM_FK` FOREIGN KEY (`CHANGE_NUMBER`) REFERENCES `CHANGES` (`CHANGE_NUM`) ON DELETE CASCADE
)