CREATE TABLE IF NOT EXISTS `CERTIFIED_USERS` (
  `USER_ID` BIGINT NOT NULL,
  PRIMARY KEY (`USER_ID`),
  CONSTRAINT `CERTIFIED_USERS_USER_ID_FK` FOREIGN KEY (`USER_ID`) REFERENCES `USER_GROUP` (`ID`) ON DELETE CASCADE
)