CREATE TABLE IF NOT EXISTS `CHALLENGE_TEAM` (
  `ID` bigint NOT NULL,
  `ETAG` char(36) NOT NULL,
  `TEAM_ID` bigint NOT NULL,
  `CHALLENGE_ID` bigint NOT NULL,
  `SERIALIZED_ENTITY` mediumblob NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_CT_CHALL_AND_TEAM` (`TEAM_ID`,`CHALLENGE_ID`),
  KEY `CHALLENGE_T_CHALLENGE_ID_FK` (`CHALLENGE_ID`),
  CONSTRAINT `CHALLENGE_T_CHALLENGE_ID_FK` FOREIGN KEY (`CHALLENGE_ID`) REFERENCES `CHALLENGE` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `CHALLENGE_T_TEAM_ID_FK` FOREIGN KEY (`TEAM_ID`) REFERENCES `TEAM` (`ID`) ON DELETE CASCADE
)