CREATE TABLE IF NOT EXISTS `CHALLENGE` (
  `ID` bigint NOT NULL,
  `ETAG` char(36) NOT NULL,
  `TEAM_ID` bigint NOT NULL,
  `PROJECT_ID` bigint NOT NULL,
  `SERIALIZED_ENTITY` mediumblob NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_CHALL_PID` (`PROJECT_ID`),
  KEY `CHALLENGE_TEAM_ID_FK` (`TEAM_ID`),
  CONSTRAINT `CHALLENGE_PROJECT_ID_FK` FOREIGN KEY (`PROJECT_ID`) REFERENCES `node` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `CHALLENGE_TEAM_ID_FK` FOREIGN KEY (`TEAM_ID`) REFERENCES `team` (`ID`) ON DELETE RESTRICT
)