CREATE TABLE `CHANGES` (
  `CHANGE_NUM` BIGINT NOT NULL,
  `TIME_STAMP` timestamp NOT NULL,
  `OBJECT_ID` BIGINT NOT NULL,
  `OBJECT_VERSION` BIGINT NOT NULL,
  `USER_ID` BIGINT DEFAULT NULL,
  `OBJECT_TYPE` enum('ENTITY','ENTITY_CONTAINER','PRINCIPAL','ACTIVITY','EVALUATION','SUBMISSION','EVALUATION_SUBMISSIONS','FILE','MESSAGE','WIKI','FAVORITE','ACCESS_REQUIREMENT','ACCESS_APPROVAL','TEAM','TABLE','ACCESS_CONTROL_LIST','PROJECT_SETTING','VERIFICATION_SUBMISSION','CERTIFIED_USER_PASSING_RECORD','FORUM','THREAD','REPLY','ENTITY_VIEW','USER_PROFILE','DATA_ACCESS_REQUEST','DATA_ACCESS_SUBMISSION','DATA_ACCESS_SUBMISSION_STATUS') NOT NULL,
  `CHANGE_TYPE` enum('CREATE','UPDATE','DELETE') DEFAULT NULL,
  PRIMARY KEY (`OBJECT_ID`, `OBJECT_VERSION` ,`OBJECT_TYPE`),
  UNIQUE KEY `CHANGE_NUM` (`CHANGE_NUM`)
)
