CREATE TABLE IF NOT EXISTS `COLUMN_PROVENANCE` (
  `OBJECT_ID` BIGINT NOT NULL,
  `OBJECT_VERSION` BIGINT NOT NULL,
  `PROVENANCE_JSON` JSON NOT NULL,
  PRIMARY KEY (`OBJECT_ID`, `OBJECT_VERSION`),
  CONSTRAINT `COLUMN_PROVENANCE_OBJECT_FK` FOREIGN KEY (`OBJECT_ID`) REFERENCES `NODE` (`ID`) ON DELETE CASCADE
)
