CREATE TABLE IF NOT EXISTS `COMMENT` (
  `MESSAGE_ID` BIGINT NOT NULL,
  `OBJECT_TYPE` ENUM('ENTITY', 'EVALUATION', 'SUBMISSION', 'FILE', 'WIKI', 'TEAM') NOT NULL,
  `OBJECT_ID` BIGINT NOT NULL,
  PRIMARY KEY (`MESSAGE_ID`),
  UNIQUE KEY (`MESSAGE_ID`, `OBJECT_TYPE`, `OBJECT_ID`),
  CONSTRAINT `COMMENT_ID_FK` FOREIGN KEY (`MESSAGE_ID`) REFERENCES `MESSAGE_CONTENT` (`ID`) ON DELETE CASCADE
)
