CREATE TABLE `COMMUNITY_TEAM` (
	`COMMUNITY_ID` bigint(20) NOT NULL,
	`TEAM_ID` bigint(20) NOT NULL,
	PRIMARY KEY (`TEAM_ID`),
	CONSTRAINT `COMMUNITY_TEAM_TEAM_FK` FOREIGN KEY (`TEAM_ID`) REFERENCES `TEAM` (`ID`) ON DELETE CASCADE,
	CONSTRAINT `COMMUNITY_TEAM_COMMUNITY_FK` FOREIGN KEY (`COMMUNITY_ID`) REFERENCES `JDONODE` (`ID`)
)
