CREATE TABLE IF NOT EXISTS `CREDENTIAL` (
  `PRINCIPAL_ID` BIGINT NOT NULL,
  `PASS_HASH` varchar(73) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SECRET_KEY` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`PRINCIPAL_ID`), 
  CONSTRAINT `PRINCIPAL_ID_FK` FOREIGN KEY (`PRINCIPAL_ID`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE
)
