CREATE TABLE IF NOT EXISTS `DAEMON_TERMINATE` (
  `BACKUP_OWNER` bigint(20) NOT NULL,
  `FORCE_TERMINATION` bit(1) NOT NULL,
  PRIMARY KEY (`BACKUP_OWNER`),
  CONSTRAINT `BACKUP_OWNER_FK` FOREIGN KEY (`BACKUP_OWNER`) REFERENCES `DAEMON_STATUS` (`ID`) ON DELETE CASCADE
)
