CREATE TABLE IF NOT EXISTS `DATA_ACCESS_SUBMISSION_ACCESSOR` (
  `ID` bigint(20) NOT NULL,
  `ACCESS_REQUIREMENT_ID` bigint(20) NOT NULL,
  `ACCESSOR_ID` bigint(20) NOT NULL,
  `CURRENT_SUBMISSION_ID` bigint(20) NOT NULL,
  `ETAG` char(36) NOT NULL,
  UNIQUE KEY (`ID`),
  PRIMARY KEY (`ACCESS_REQUIREMENT_ID`, `ACCESSOR_ID`),
  CONSTRAINT `DATA_ACCESS_SUBMISSION_ACCESSORS_SUBMISSION_ID_FK` FOREIGN KEY (`CURRENT_SUBMISSION_ID`) REFERENCES `DATA_ACCESS_SUBMISSION` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `DATA_ACCESS_SUBMISSION_ACCESSORS_ACCESS_REQUIREMENT_ID_FK` FOREIGN KEY (`ACCESS_REQUIREMENT_ID`) REFERENCES `ACCESS_REQUIREMENT` (`ID`) ON DELETE CASCADE
)
