CREATE TABLE IF NOT EXISTS `DATA_ACCESS_REQUEST` (
  `ID` bigint(20) NOT NULL,
  `ACCESS_REQUIREMENT_ID` bigint(20) NOT NULL,
  `RESEARCH_PROJECT_ID` bigint(20) NOT NULL,
  `CREATED_BY` bigint(20) NOT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  `MODIFIED_BY` bigint(20) NOT NULL,
  `MODIFIED_ON` bigint(20) NOT NULL,
  `ETAG` char(36) NOT NULL,
  `ACCESSORS` varchar(256) NOT NULL,
  `REQUEST_SERIALIZED` mediumblob NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE (`ACCESS_REQUIREMENT_ID`, `CREATED_BY`),
  CONSTRAINT `DATA_ACCESS_REQUEST_ACCESS_REQUIREMENT_ID_FK` FOREIGN KEY (`ACCESS_REQUIREMENT_ID`) REFERENCES `ACCESS_REQUIREMENT` (`ID`),
  CONSTRAINT `DATA_ACCESS_REQUEST_RESEARCH_PROJECT_ID_FK` FOREIGN KEY (`RESEARCH_PROJECT_ID`) REFERENCES `RESEARCH_PROJECT` (`ID`)
)
