CREATE TABLE IF NOT EXISTS `DATA_ACCESS_SUBMISSION_STATUS` (
  `SUBMISSION_ID` bigint(20) NOT NULL,
  `CREATED_BY` bigint(20) NOT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  `MODIFIED_BY` bigint(20) NOT NULL,
  `MODIFIED_ON` bigint(20) NOT NULL,
  `STATE` enum('SUBMITTED','APPROVED','REJECTED','CANCELLED') NOT NULL,
  `REASON` blob NOT NULL,
  PRIMARY KEY (`SUBMISSION_ID`),
  CONSTRAINT `DATA_ACCESS_SUBMISSION__STATUS_SUBMISSION_ID_FK` FOREIGN KEY (`SUBMISSION_ID`) REFERENCES `DATA_ACCESS_SUBMISSION` (`ID`) ON DELETE RESTRICT
)
