CREATE TABLE IF NOT EXISTS `DATA_ACCESS_REQUEST` (
  `ID` BIGINT NOT NULL,
  `ACCESS_REQUIREMENT_ID` BIGINT NOT NULL,
  `RESEARCH_PROJECT_ID` BIGINT NOT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` BIGINT NOT NULL,
  `MODIFIED_BY` BIGINT NOT NULL,
  `MODIFIED_ON` BIGINT NOT NULL,
  `ETAG` char(36) NOT NULL,
  `REQUEST_SERIALIZED` mediumblob NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ACCESS_REQUIREMENT_ID_AND_CREATED_BY` (`ACCESS_REQUIREMENT_ID`, `CREATED_BY`),
  CONSTRAINT `DATA_ACCESS_REQUEST_ACCESS_REQUIREMENT_ID_FK` FOREIGN KEY (`ACCESS_REQUIREMENT_ID`) REFERENCES `ACCESS_REQUIREMENT` (`ID`) ON DELETE RESTRICT,
  CONSTRAINT `DATA_ACCESS_REQUEST_RESEARCH_PROJECT_ID_FK` FOREIGN KEY (`RESEARCH_PROJECT_ID`) REFERENCES `RESEARCH_PROJECT` (`ID`) ON DELETE RESTRICT
)
