CREATE TABLE IF NOT EXISTS `DATA_TYPE` (
  `ID` BIGINT NOT NULL,
  `OBJECT_ID` BIGINT NOT NULL,
  `OBJECT_TYPE` enum('ENTITY') NOT NULL,
  `DATA_TYPE` enum('SENSITIVE_DATA','OPEN_DATA') NOT NULL,
  `UPDATED_BY` BIGINT NOT NULL,
  `UPDATED_ON` BIGINT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE (`OBJECT_ID`, `OBJECT_TYPE`),
  CONSTRAINT `UPDATED_BY_FK` FOREIGN KEY (`UPDATED_BY`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE
)
