CREATE TABLE IF NOT EXISTS `DATA_ACCESS_SUBMISSION` (
  `ID` bigint(20) NOT NULL,
  `ACCESS_REQUIREMENT_ID` bigint(20) NOT NULL,
  `DATA_ACCESS_REQUEST_ID` bigint(20) NOT NULL,
  `SUBMITTED_BY` bigint(20) NOT NULL,
  `SUBMITTED_ON` bigint(20) NOT NULL,
  `REVIEWED_BY` bigint(20) NOT NULL,
  `MODIFIED_ON` bigint(20) NOT NULL,
  `STATE` enum('SUBMITTED','APPROVED','REJECTED','CANCELLED') NOT NULL,
  `ETAG` char(36) NOT NULL,
  `SUBMISSION_SERIALIZED` mediumblob NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `DATA_ACCESS_SUBMISSION_ACCESS_REQUIREMENT_ID_FK` FOREIGN KEY (`ACCESS_REQUIREMENT_ID`) REFERENCES `ACCESS_REQUIREMENT` (`ID`) ON DELETE RESTRICT,
  CONSTRAINT `DATA_ACCESS_SUBMISSION_DATA_ACCESS_REQUEST_ID_FK` FOREIGN KEY (`DATA_ACCESS_REQUEST_ID`) REFERENCES `DATA_ACCESS_REQUEST` (`ID`) ON DELETE RESTRICT
)
