CREATE TABLE IF NOT EXISTS `DATA_ACCESS_SUBMISSION_ACCESSOR` (
  `SUBMISSION_ID` bigint(20) NOT NULL,
  `ACCESSOR_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`SUBMISSION_ID`, `ACCESSOR_ID`),
  CONSTRAINT `DATA_ACCESS_SUBMISSION_ACCESSORS_SUBMISSION_ID_FK` FOREIGN KEY (`SUBMISSION_ID`) REFERENCES `DATA_ACCESS_SUBMISSION` (`ID`) ON DELETE RESTRICT
)
