CREATE TABLE IF NOT EXISTS `DATA_ACCESS_SUBMISSION_ACCESSOR_CHANGES` (
  `SUBMISSION_ID` BIGINT NOT NULL,
  `ACCESSOR_ID` BIGINT NOT NULL,
  PRIMARY KEY (`SUBMISSION_ID`, `ACCESSOR_ID`),
  CONSTRAINT `DATA_ACCESS_SUBMISSION_ACCESSOR_CHANGES_SUBMISSION_ID_FK` FOREIGN KEY (`SUBMISSION_ID`) REFERENCES `DATA_ACCESS_SUBMISSION` (`ID`) ON DELETE CASCADE
)
