CREATE TABLE IF NOT EXISTS `DATA_ACCESS_REQUEST_USER` (
  `REQUEST_ID` BIGINT NOT NULL,
  `USER_ID` BIGINT NOT NULL,
  PRIMARY KEY (`REQUEST_ID`, `USER_ID`),
  CONSTRAINT `DATA_ACCESS_REQUEST_USER_REQUEST_ID_FK` FOREIGN KEY (`REQUEST_ID`) REFERENCES `DATA_ACCESS_REQUEST` (`ID`) ON DELETE CASCADE,
  INDEX `DATA_ACCESS_REQUEST_USER_USER_ID_IDX` (`USER_ID`)
)
