CREATE TABLE IF NOT EXISTS `DATA_ACCESS_SUBMISSION` (
  `ID` BIGINT NOT NULL,
  `ACCESS_REQUIREMENT_ID` BIGINT NOT NULL,
  `DATA_ACCESS_REQUEST_ID` BIGINT NOT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` BIGINT NOT NULL,
  `ETAG` char(36) NOT NULL,
  `SUBMISSION_SERIALIZED` mediumblob NOT NULL,
  `RESEARCH_PROJECT_ID` BIGINT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `DATA_ACCESS_SUBMISSION_ACCESS_REQUIREMENT_ID_FK` FOREIGN KEY (`ACCESS_REQUIREMENT_ID`) REFERENCES `ACCESS_REQUIREMENT` (`ID`) ON DELETE RESTRICT,
  CONSTRAINT `DATA_ACCESS_SUBMISSION_DATA_ACCESS_REQUEST_ID_FK` FOREIGN KEY (`DATA_ACCESS_REQUEST_ID`) REFERENCES `DATA_ACCESS_REQUEST` (`ID`) ON DELETE RESTRICT,
  CONSTRAINT `DATA_ACCESS_SUBMISSION_RESEARCH_PROJECT_ID_FK` FOREIGN KEY (`RESEARCH_PROJECT_ID`) REFERENCES `RESEARCH_PROJECT` (`ID`) ON DELETE RESTRICT
)
