CREATE TABLE IF NOT EXISTS `DATA_ACCESS_NOTIFICATION` (
  `ID` BIGINT NOT NULL,
  `ETAG` char(36) NOT NULL,
  `NOTIFICATION_TYPE` enum('FIRST_RENEWAL_REMINDER','SECOND_RENEWAL_REMINDER', 'REVOCATION') NOT NULL,
  `REQUIREMENT_ID` BIGINT NOT NULL,
  `RECIPIENT_ID` BIGINT NOT NULL,
  `SENT_ON` TIMESTAMP(3) NOT NULL,
  `ACCESS_APPROVAL_ID` BIGINT NOT NULL,
  `MESSAGE_ID` BIGINT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NOTIFICATION_TYPE_REQUIREMENT_ID_RECIPIENT_ID` (`NOTIFICATION_TYPE`, `REQUIREMENT_ID`, `RECIPIENT_ID`),
  CONSTRAINT `DATA_ACCESS_NOTIFICATION_REQUIREMENT_ID_FK` FOREIGN KEY (`REQUIREMENT_ID`) REFERENCES `ACCESS_REQUIREMENT` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `DATA_ACCESS_NOTIFICATION_RECIPIENT_ID_FK` FOREIGN KEY (`RECIPIENT_ID`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `DATA_ACCESS_NOTIFICATION_APPROVAL_ID_FK` FOREIGN KEY (`ACCESS_APPROVAL_ID`) REFERENCES `ACCESS_APPROVAL` (`ID`) ON DELETE CASCADE
)
