CREATE TABLE IF NOT EXISTS `DEFINING_SQL_OBJECT` (
  `OBJECT_ID` BIGINT NOT NULL,
  `ETAG` CHAR(36) NOT NULL,
  PRIMARY KEY(`OBJECT_ID`),
  CONSTRAINT `DEFINING_SQL_OBJECT_ID_FK` FOREIGN KEY (`OBJECT_ID`) REFERENCES `NODE` (`ID`) ON DELETE CASCADE
)
