CREATE TABLE IF NOT EXISTS `DEFINING_SQL_DEPENDENCY` (
  `OBJECT_ID` BIGINT NOT NULL,
  `OBJECT_VERSION` BIGINT NOT NULL,
  `OBJECT_TYPE` ENUM('MATERIALIZED_VIEW','SEARCH_INDEX') NOT NULL DEFAULT 'MATERIALIZED_VIEW',
  `SOURCE_TABLE_ID` BIGINT NOT NULL,
  `SOURCE_TABLE_VERSION` BIGINT NOT NULL,
  PRIMARY KEY (`OBJECT_ID`, `OBJECT_VERSION`, `SOURCE_TABLE_ID`, `SOURCE_TABLE_VERSION`),
  KEY `DEFINING_SQL_DEPENDENCY_SOURCE_IDX` (`SOURCE_TABLE_ID`, `SOURCE_TABLE_VERSION`, `OBJECT_TYPE`),
  CONSTRAINT `DEFINING_SQL_DEPENDENCY_FK` FOREIGN KEY (`OBJECT_ID`) REFERENCES `DEFINING_SQL_OBJECT` (`OBJECT_ID`) ON DELETE CASCADE
)
