CREATE TABLE IF NOT EXISTS `DISCUSSION_THREAD_VIEW` (
  `THREAD_ID` BIGINT NOT NULL,
  `USER_ID` BIGINT NOT NULL,
  PRIMARY KEY (`THREAD_ID`, `USER_ID`),
  INDEX `DISCUSSION_THREAD_VIEW_USER_ID_INDEX` (`USER_ID`),
  CONSTRAINT `DISCUSSION_THREAD_VIEW_THREAD_ID_FK` FOREIGN KEY (`THREAD_ID`) REFERENCES `DISCUSSION_THREAD` (`ID`) ON DELETE CASCADE
)
