CREATE TABLE IF NOT EXISTS `DOCKER_REPOSITORY_NAME` (
  `OWNER_ID` bigint NOT NULL,
  `REPOSITORY_NAME` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`OWNER_ID`),
  UNIQUE KEY `UNIQUE_DOCKER_REPO_NAME` (`REPOSITORY_NAME`),
  CONSTRAINT `DOCKER_REPO_NAME_FK` FOREIGN KEY (`OWNER_ID`) REFERENCES `NODE` (`ID`) ON DELETE CASCADE
)