CREATE TABLE IF NOT EXISTS `DOCKER_COMMIT` (
  `ID` bigint NOT NULL,
  `OWNER_ID` bigint NOT NULL,
  `TAG` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `DIGEST` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `CREATED_ON` bigint NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_DOCKER_COMMIT` (`OWNER_ID`,`TAG`,`CREATED_ON`),
  CONSTRAINT `DOCKER_COMMIT_OWNER_FK` FOREIGN KEY (`OWNER_ID`) REFERENCES `NODE` (`ID`) ON DELETE CASCADE
)