CREATE TABLE IF NOT EXISTS `DOWNLOAD_LIST` (
  `PRINCIPAL_ID` BIGINT NOT NULL,
  `UPDATED_ON` BIGINT NOT NULL,
  `ETAG` char(36) NOT NULL,
  PRIMARY KEY (`PRINCIPAL_ID`),
  CONSTRAINT `DOWNLOAD_PRI_FK` FOREIGN KEY (`PRINCIPAL_ID`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE
)
