CREATE TABLE IF NOT EXISTS `DOWNLOAD_ORDER` (
  `ORDER_ID` bigint(20) NOT NULL,
  `CREATED_BY` bigint(20) NOT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  `FILE_NAME` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `TOTAL_SIZE_BYTES` bigint(20) NOT NULL,
  `TOTAL_NUM_FILES` bigint(20) NOT NULL,
  `FILES_BLOB` blob,
  PRIMARY KEY (`ORDER_ID`),
  INDEX (`CREATED_BY`),
  CONSTRAINT `CREATED_BY_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE
)
