CREATE TABLE IF NOT EXISTS `DOWNLOAD_LIST_ITEM_2` (
  `PRINCIPAL_ID` BIGINT NOT NULL,
  `ENTITY_ID` BIGINT NOT NULL,
  `VERSION_NUMBER` BIGINT DEFAULT NULL,
  `ADDED_ON` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`PRINCIPAL_ID`, `ENTITY_ID`, `VERSION_NUMBER`),
  INDEX (`PRINCIPAL_ID`),
  CONSTRAINT `DOWNLOAD_ITEM_OWNER_FK` FOREIGN KEY (`PRINCIPAL_ID`) REFERENCES `DOWNLOAD_LIST_2` (`PRINCIPAL_ID`) ON DELETE CASCADE
)