CREATE TABLE IF NOT EXISTS `DOWNLOAD_LIST_ITEM_V2` (
  `PRINCIPAL_ID` BIGINT NOT NULL,
  `ENTITY_ID` BIGINT NOT NULL,
  `VERSION_NUMBER` BIGINT DEFAULT -1,
  `ADDED_ON` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`PRINCIPAL_ID`, `ENTITY_ID`, `VERSION_NUMBER`),
  CONSTRAINT FOREIGN KEY (`PRINCIPAL_ID`) REFERENCES `DOWNLOAD_LIST_V2` (`PRINCIPAL_ID`) ON DELETE CASCADE
)