CREATE TABLE IF NOT EXISTS `EDUC_ENVELOPE_NOTIFICATION` (
  `ID` BIGINT NOT NULL,
  `ETAG` char(36) NOT NULL,
  `ENVELOPE_ID` VARCHAR(255) NOT NULL,
  `REQUEST_ID` BIGINT NOT NULL,
  `TERMINAL_STATUS` enum('completed','declined','voided') NOT NULL,
  `OBSERVED_ON` TIMESTAMP(3) NOT NULL,
  `MESSAGE_ID` BIGINT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `EDUC_ENVELOPE_NOTIFICATION_ENVELOPE_ID` (`ENVELOPE_ID`),
  CONSTRAINT `EDUC_ENV_NOTIF_REQUEST_ID_FK` FOREIGN KEY (`REQUEST_ID`) REFERENCES `DATA_ACCESS_REQUEST` (`ID`) ON DELETE CASCADE
)
