CREATE TABLE IF NOT EXISTS `EDUC_QUOTA` (
  `ID` BIGINT NOT NULL,
  `USER_ID` BIGINT NOT NULL,
  `ACCESS_REQUIREMENT_ID` BIGINT NOT NULL,
  `CREATED_ON` BIGINT NOT NULL,
  `ENVELOPE_ID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `EDUC_QUOTA_ENVELOPE_ID` (`ENVELOPE_ID`),
  INDEX `EDUC_QUOTA_USER_AR_CREATED` (`USER_ID`, `ACCESS_REQUIREMENT_ID`, `CREATED_ON`),
  CONSTRAINT `EDUC_QUOTA_USER_ID_FK` FOREIGN KEY (`USER_ID`) REFERENCES `USER_GROUP` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `EDUC_QUOTA_AR_ID_FK` FOREIGN KEY (`ACCESS_REQUIREMENT_ID`) REFERENCES `ACCESS_REQUIREMENT` (`ID`) ON DELETE CASCADE
)
