CREATE TABLE IF NOT EXISTS `FORM_TEMPLATE` (
  `ID` BIGINT NOT NULL,
  `ETAG` char(36) NOT NULL,
  `NAME` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `CURRENT_REV_NUM` BIGINT NOT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` BIGINT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `FORM_TEMPLATE_NAME` (`NAME`),
  CONSTRAINT `FORM_TEMPLATE_CREATED_BY_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE CASCADE
)
