CREATE TABLE IF NOT EXISTS `FORM_TEMPLATE_REVISION` (
  `OWNER_ID` BIGINT NOT NULL,
  `NUMBER` BIGINT NOT NULL,
  `MODIFIED_BY` BIGINT NOT NULL,
  `MODIFIED_ON` BIGINT NOT NULL,
  `DEPRECATED` BOOLEAN NOT NULL,
  `TEMPLATE_JSON` JSON NOT NULL,
  PRIMARY KEY (`OWNER_ID`,`NUMBER`),
  CONSTRAINT `FORM_TEMPLATE_REVISION_OWNER_FK` FOREIGN KEY (`OWNER_ID`) REFERENCES `FORM_TEMPLATE` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `FORM_TEMPLATE_REVISION_MODIFIED_BY_FK` FOREIGN KEY (`MODIFIED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE RESTRICT
)
