CREATE TABLE `GROUP_MEMBERS` (
  `GROUP_ID` bigint(20) NOT NULL,
  `MEMBER_ID` bigint(20) NOT NULL,
  CONSTRAINT `UNIQUE_MEMBERSHIP` PRIMARY KEY (`GROUP_ID`, `MEMBER_ID`), 
  CONSTRAINT `GROUP_ID_FK` FOREIGN KEY (`GROUP_ID`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE, 
  CONSTRAINT `MEMBER_ID_FK` FOREIGN KEY (`MEMBER_ID`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE 
)