CREATE TABLE `GROUP_PARENTS_CACHE` (
  `GROUP_ID` bigint(20) NOT NULL,
  `PARENTS` blob DEFAULT NULL, 
  PRIMARY KEY (`GROUP_ID`), 
  CONSTRAINT `GROUP_ID_CACHE_FK` FOREIGN KEY (`GROUP_ID`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE
)