CREATE TABLE IF NOT EXISTS `JSON_SCHEMA_VERSION` (
  `VERSION_NUM` BIGINT NOT NULL,
  `SCHEMA_ID` BIGINT NOT NULL,
  `SEMANTIC_VERSION` VARCHAR(250) CHARACTER SET ascii DEFAULT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `S3_BUCKET` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `S3_KEY` varchar(700) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`VERSION_NUM`),
  UNIQUE (`SCHEMA_ID`, `SEMANTIC_VERSION`),
  CONSTRAINT FOREIGN KEY (`CREATED_BY`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE RESTRICT,
  CONSTRAINT FOREIGN KEY (`SCHEMA_ID`) REFERENCES `JSON_SCHEMA` (`ID`) ON DELETE RESTRICT
)