CREATE TABLE IF NOT EXISTS `JSON_SCHEMA_OBJECT_BINDING` (
  `BIND_ID` BIGINT NOT NULL,
  `SCHEMA_ID` BIGINT NOT NULL,
  `VERSION_ID` BIGINT DEFAULT NULL,
  `OBJECT_ID` BIGINT NOT NULL,
  `OBJECT_TYPE` ENUM ('entity'),
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`BIND_ID`),
  UNIQUE (`OBJECT_ID`,`OBJECT_TYPE`),
  CONSTRAINT FOREIGN KEY (`CREATED_BY`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE RESTRICT,
  CONSTRAINT `FK_BOUND_DEPENDS_ON_SCHEMA_ID` FOREIGN KEY (`SCHEMA_ID`) REFERENCES `JSON_SCHEMA` (`SCHEMA_ID`) ON DELETE RESTRICT,
  CONSTRAINT `FK_BOUND_DEPENDS_ON_VERSION_ID` FOREIGN KEY (`VERSION_ID`) REFERENCES `JSON_SCHEMA_VERSION` (`VERSION_ID`) ON DELETE RESTRICT
)
