CREATE TABLE IF NOT EXISTS `JSON_SCHEMA_VERSION` (
  `VERSION_ID` BIGINT NOT NULL,
  `SCHEMA_ID` BIGINT NOT NULL,
  `SEMANTIC_VERSION` VARCHAR(250) CHARACTER SET ascii COLLATE ascii_general_ci DEFAULT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `BLOB_ID` BIGINT NOT NULL,
  PRIMARY KEY (`VERSION_ID`),
  UNIQUE (`SCHEMA_ID`, `SEMANTIC_VERSION`),
  INDEX (`SEMANTIC_VERSION`),
  CONSTRAINT FOREIGN KEY (`CREATED_BY`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE RESTRICT,
  CONSTRAINT FOREIGN KEY (`SCHEMA_ID`) REFERENCES `JSON_SCHEMA` (`SCHEMA_ID`) ON DELETE RESTRICT,
  CONSTRAINT FOREIGN KEY (`BLOB_ID`) REFERENCES `JSON_SCHEMA_BLOB` (`BLOB_ID`) ON DELETE RESTRICT
)