CREATE TABLE IF NOT EXISTS `JSON_SCHEMA` (
  `ID` BIGINT NOT NULL,
  `ORG_ID` BIGINT NOT NULL,
  `NAME` VARCHAR(250) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`ORG_ID`, `NAME`),
  UNIQUE (`ID`),
  CONSTRAINT `J_S_CREATOR_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE RESTRICT,
  CONSTRAINT `J_S_ORG_ID_FK` FOREIGN KEY (`ORG_ID`) REFERENCES `ORGANIZATION` (`ID`) ON DELETE RESTRICT
)
