CREATE TABLE IF NOT EXISTS `JSON_SCHEMA_VALIDATION_RESULTS` (
  `OBJECT_ID` BIGINT NOT NULL,
  `OBJECT_TYPE` ENUM ('entity'),
  `OBJECT_ETAG` char(36) NOT NULL,
  `SCHEMA_ID` VARCHAR(753) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  `IS_VALID` BOOLEAN NOT NULL,
  `VALIDATED_ON` TIMESTAMP(3) NOT NULL,
  `ERROR_MESSAGE` TEXT DEFAULT NULL,
  `ALL_ERROR_MESSAGES` JSON DEFAULT NULL,
  `VALIDATION_EXCEPTION` JSON DEFAULT NULL,
  PRIMARY KEY (`OBJECT_ID`,`OBJECT_TYPE`)
)
