CREATE TABLE IF NOT EXISTS `JSON_SCHEMA` (
  `SCHEMA_ID` BIGINT NOT NULL,
  `ORGANIZATION_ID` BIGINT NOT NULL,
  `SCHEMA_NAME` VARCHAR(250) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`ORGANIZATION_ID`, `SCHEMA_NAME`),
  UNIQUE (`SCHEMA_ID`),
  INDEX (`SCHEMA_NAME`),
  CONSTRAINT `FK_SCHEMA_TO_USER` FOREIGN KEY (`CREATED_BY`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE RESTRICT,
  CONSTRAINT `FK_SCHEMA_TO_ORGANIZATION` FOREIGN KEY (`ORGANIZATION_ID`) REFERENCES `ORGANIZATION` (`ID`) ON DELETE RESTRICT
)
