CREATE TABLE `jdolongannotation` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ATTRIBUTE` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `OWNER_ID` bigint(20) NOT NULL,
  `VALUE` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `JDOLONGANNOTATION_N49` (`OWNER_ID`),
  CONSTRAINT `LONG_ANNON_OWNER_FK` FOREIGN KEY (`OWNER_ID`) REFERENCES `jdonode` (`ID`) ON DELETE CASCADE
)