CREATE TABLE IF NOT EXISTS `JDOLONGANNOTATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ATTRIBUTE` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `OWNER_ID` bigint(20) NOT NULL,
  `VALUE` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `LONG_ANNO_UNIQUE` (`OWNER_ID`,`ATTRIBUTE`, `VALUE`),
  CONSTRAINT `LONG_ANNO_OWNER_FK` FOREIGN KEY (`OWNER_ID`) REFERENCES `ANNOTATIONS_OWNER` (`OWNER_ID`) ON DELETE CASCADE
)
