CREATE TABLE IF NOT EXISTS `MATERIALIZED_VIEW_ID` (
  `MATERIALIZED_VIEW_ID` BIGINT NOT NULL,
  `ETAG` CHAR(36) NOT NULL,
  PRIMARY KEY(`MATERIALIZED_VIEW_ID`),
  CONSTRAINT `MV_ID_ID_FK` FOREIGN KEY (`MATERIALIZED_VIEW_ID`) REFERENCES `JDONODE` (`ID`) ON DELETE CASCADE
)