CREATE TABLE IF NOT EXISTS `MATERIALIZED_VIEW_SOURCE_TABLES` (
  `MATERIALIZED_VIEW_ID` BIGINT NOT NULL,
  `SOURCE_TABLE_ID` BIGINT NOT NULL,
  `SOURCE_TABLE_VERSION` BIGINT NOT NULL,
  PRIMARY KEY (`MATERIALIZED_VIEW_ID`, `SOURCE_TABLE_ID`, `SOURCE_TABLE_VERSION`)
)