CREATE TABLE IF NOT EXISTS `MATERIALIZED_VIEW_SOURCE_TABLES` (
  `MATERIALIZED_VIEW_ID` BIGINT NOT NULL,
  `MATERIALIZED_VIEW_VERSION` BIGINT NOT NULL,
  `SOURCE_TABLE_ID` BIGINT NOT NULL,
  `SOURCE_TABLE_VERSION` BIGINT NOT NULL,
  PRIMARY KEY (`MATERIALIZED_VIEW_ID`, `MATERIALIZED_VIEW_VERSION`, `SOURCE_TABLE_ID`, `SOURCE_TABLE_VERSION`),
  CONSTRAINT `MV_SOURCE_TABLES_MV_ID_FK` FOREIGN KEY (`MATERIALIZED_VIEW_ID`) REFERENCES `MATERIALIZED_VIEW_ID` (`MATERIALIZED_VIEW_ID`) ON DELETE CASCADE
)