CREATE TABLE IF NOT EXISTS `MEMBERSHIP_REQUEST_SUBMISSION` (
  `ID` BIGINT NOT NULL,
  `TEAM_ID` BIGINT NOT NULL,
  `CREATED_ON` BIGINT NOT NULL,
  `USER_ID` BIGINT NOT NULL,
  `EXPIRES_ON` BIGINT,
  `PROPERTIES` mediumblob,
  PRIMARY KEY (`ID`),
  CONSTRAINT `MEMBERSHIP_REQUEST_TEAM_FK` FOREIGN KEY (`TEAM_ID`) REFERENCES `TEAM` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `MEMBERSHIP_REQUEST_USER_FK` FOREIGN KEY (`USER_ID`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE
  
)
