CREATE TABLE `MEMBERSHIP_INVITEE` (
  `MEMBERSHIP_INVITATION_ID` bigint(20) NOT NULL,
  `INVITEE_ID` bigint(20) NOT NULL,
  CONSTRAINT `MEMBERSHIP_INVITEE_INVITATION_FK` FOREIGN KEY (`MEMBERSHIP_INVITATION_ID`) REFERENCES `MEMBERSHIP_INVITATION_SUBMISSION` (`ID`),
  CONSTRAINT `MEMBERSHIP_INVITEE_INVITEE_FK` FOREIGN KEY (`INVITEE_ID`) REFERENCES `JDOUSERGROUP` (`ID`)
)