CREATE TABLE `MESSAGE_TO_USER` (
  `MESSAGE_ID` bigint(20) NOT NULL,
  `ROOT_MESSAGE_ID` bigint(20) NOT NULL,
  `IN_REPLY_TO` bigint(20) DEFAULT NULL, 
  `SUBJECT` varchar(256) DEFAULT NULL, 
  `STATUS` ENUM('PENDING', 'SENT', 'FAILED') NOT NULL, 
  PRIMARY KEY (`MESSAGE_ID`),
  CONSTRAINT `MESSAGE_TO_USER_FK` FOREIGN KEY (`MESSAGE_ID`) REFERENCES `MESSAGE_CONTENT` (`ID`) ON DELETE CASCADE, 
  CONSTRAINT `MESSAGE_TO_USER_SELF_FK` FOREIGN KEY (`ROOT_MESSAGE_ID`) REFERENCES `MESSAGE_TO_USER` (`MESSAGE_ID`) ON DELETE CASCADE, 
  CONSTRAINT `MESSAGE_TO_USER_IN_REPLY_TO_FK` FOREIGN KEY (`IN_REPLY_TO`) REFERENCES `MESSAGE_CONTENT` (`ID`) ON DELETE CASCADE
)