CREATE TABLE `MESSAGE_THREAD` (
  `THREAD_ID` bigint(20) NOT NULL,
  `THREAD_MESSAGE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`THREAD_ID`, `THREAD_MESSAGE_ID`),
  UNIQUE KEY (`THREAD_MESSAGE_ID`),
  CONSTRAINT `THREAD_MESSAGE_ID_FK` FOREIGN KEY (`THREAD_MESSAGE_ID`) REFERENCES `MESSAGE` (`ID`) ON DELETE CASCADE
)