CREATE TABLE `MESSAGE` (
  `ID` bigint(20) NOT NULL,
  `THREAD_ID` bigint(20) NOT NULL,
  `CREATED_BY` bigint(20) NOT NULL,
  `RECIPIENT_TYPE` ENUM('ENTITY', 'PRINCIPAL') NOT NULL,
  `RECIPIENTS` blob NOT NULL, 
  `FILE_HANDLE_ID` bigint(20) NOT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  `SUBJECT` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL, 
  PRIMARY KEY (`ID`),
  KEY (`THREAD_ID`),
  CONSTRAINT `SENDER_ID_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `FILE_HANDLE_ID_FK` FOREIGN KEY (`FILE_HANDLE_ID`) REFERENCES `FILES` (`ID`) ON DELETE CASCADE
)