CREATE TABLE IF NOT EXISTS `MESSAGE_TO_USER` (
  `MESSAGE_ID` BIGINT NOT NULL,
  `ROOT_MESSAGE_ID` BIGINT NOT NULL,
  `IN_REPLY_TO` BIGINT DEFAULT NULL,
  `SUBJECT` blob, 
  `NOTIFICATIONS_ENDPOINT` varchar(256) DEFAULT NULL, 
  `PROFILE_SETTING_ENDPOINT` varchar(256) DEFAULT NULL, 
  `WITH_UNSUBSCRIBE_LINK` boolean DEFAULT FALSE, 
  `WITH_PROFILE_SETTING_LINK` boolean DEFAULT FALSE,
  `IS_NOTIFICATION_MESSAGE` boolean DEFAULT FALSE, 
  `TO` blob DEFAULT NULL,
  `CC` blob DEFAULT NULL,
  `BCC` blob DEFAULT NULL,
  `SENT` boolean, 
  PRIMARY KEY (`MESSAGE_ID`),
  CONSTRAINT `MESSAGE_TO_USER_FK` FOREIGN KEY (`MESSAGE_ID`) REFERENCES `MESSAGE_CONTENT` (`ID`) ON DELETE CASCADE, 
  CONSTRAINT `MESSAGE_TO_USER_SELF_FK` FOREIGN KEY (`ROOT_MESSAGE_ID`) REFERENCES `MESSAGE_TO_USER` (`MESSAGE_ID`) ON DELETE CASCADE, 
  CONSTRAINT `MESSAGE_TO_USER_IN_REPLY_TO_FK` FOREIGN KEY (`IN_REPLY_TO`) REFERENCES `MESSAGE_CONTENT` (`ID`) ON DELETE CASCADE
)
