CREATE TABLE IF NOT EXISTS `MESSAGE_CONTENT` (
  `ID` bigint(20) NOT NULL,
  `CREATED_BY` bigint(20) NOT NULL,
  `FILE_HANDLE_ID` bigint(20) NOT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  `ETAG` char(36) NOT NULL, 
  PRIMARY KEY (`ID`),
  CONSTRAINT `MESSAGE_CONTENT_CREATED_BY_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `MESSAGE_CONTENT_FILE_HANDLE_ID_FK` FOREIGN KEY (`FILE_HANDLE_ID`) REFERENCES `FILES` (`ID`)
)
