CREATE TABLE `MESSAGE_THREAD` (
  `THREAD_ID` bigint(20) NOT NULL,
  `MESSAGE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`THREAD_ID`, `MESSAGE_ID`),
  UNIQUE KEY (`MESSAGE_ID`),
  CONSTRAINT `MESSAGE_ID_FK` FOREIGN KEY (`MESSAGE_ID`) REFERENCES `MESSAGE` (`ID`) ON DELETE CASCADE
)