CREATE TABLE `MESSAGE_THREAD_OBJECT` (
  `MESSAGE_THREAD_ID` bigint(20) NOT NULL,
  `OBJECT_ID` bigint(20) NOT NULL,
  `OBJECT_TYPE` ENUM('ENTITY', 'PRINCIPAL') NOT NULL,
  PRIMARY KEY (`MESSAGE_THREAD_ID`),
  UNIQUE KEY (`MESSAGE_THREAD_ID`, `OBJECT_ID`, `OBJECT_TYPE`),
  CONSTRAINT `MESSAGE_THREAD_ID_FK` FOREIGN KEY (`MESSAGE_THREAD_ID`) REFERENCES `MESSAGE_THREAD` (`PARENT_MESSAGE_ID`)
)