CREATE TABLE `MESSAGE_THREAD` (
  `CHILD_MESSAGE_ID` bigint(20) NOT NULL,
  `PARENT_MESSAGE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`CHILD_MESSAGE_ID`),
  KEY (`PARENT_MESSAGE_ID`), 
  CONSTRAINT `CHILD_MESSAGE_ID` FOREIGN KEY (`CHILD_MESSAGE_ID`) REFERENCES `MESSAGE` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `SELF_CHILD_MESSAGE_ID_FK` FOREIGN KEY (`PARENT_MESSAGE_ID`) REFERENCES `MESSAGE_THREAD` (`CHILD_MESSAGE_ID`) ON DELETE CASCADE
)