CREATE TABLE IF NOT EXISTS `MULTIPART_UPLOAD_PART_STATE` (
  `UPLOAD_ID` BIGINT NOT NULL,
  `PART_NUMBER` int NOT NULL,
  `PART_MD5_HEX` char(35) DEFAULT NULL,
  `ERROR_DETAILS` BLOB DEFAULT NULL,
  PRIMARY KEY (`UPLOAD_ID`,`PART_NUMBER`),
  CONSTRAINT `MULTIPART_UPLOAD_FK` FOREIGN KEY (`UPLOAD_ID`) REFERENCES `MULTIPART_UPLOAD` (`ID`) ON DELETE CASCADE
)