CREATE TABLE IF NOT EXISTS MULTIPART_UPLOAD_COMPOSER_PART_STATE (
  `UPLOAD_ID` bigint(20) NOT NULL,
  `PART_RANGE_LOWER_BOUND` int NOT NULL,
  `PART_RANGE_UPPER_BOUND` int NOT NULL,
  CHECK (`PART_RANGE_UPPER_BOUND` >= `PART_RANGE_LOWER_BOUND`),
  PRIMARY KEY (`UPLOAD_ID`,`PART_RANGE_LOWER_BOUND`, `PART_RANGE_UPPER_BOUND`),
  CONSTRAINT `MULTIPART_UPLOAD_COMPOSER_FK` FOREIGN KEY (`UPLOAD_ID`) REFERENCES `MULTIPART_UPLOAD` (`ID`) ON DELETE CASCADE
)