CREATE TABLE IF NOT EXISTS `MULTIPART_UPLOAD` (
  `ID` bigint(20) NOT NULL,
  `REQUEST_HASH` char(100) NOT NULL,
  `ETAG` char(36) NOT NULL,
  `REQUEST_BLOB` BLOB NOT NULL,
  `STARTED_BY` bigint(20) NOT NULL,
  `STARTED_ON` TIMESTAMP NOT NULL,
  `UPDATED_ON` TIMESTAMP NOT NULL,
  `FILE_HANDLE_ID` bigint(20) DEFAULT NULL,
  `STATE` ENUM('UPLOADING','COMPLETE') NOT NULL,
  `STORAGE_LOCATION_ID` bigint(20) DEFAULT NULL,
  `STORAGE_LOCATION_TOKEN` char(100) NOT NULL, 
  PRIMARY KEY (`ID`),
  UNIQUE KEY (`STARTED_BY`,`REQUEST_HASH`),
  CONSTRAINT `MUTI_FILE_HAN_BY_FK` FOREIGN KEY (`FILE_HANDLE_ID`) REFERENCES `FILES` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `MUTI_STARTED_BY_FK` FOREIGN KEY (`STARTED_BY`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `MULTI_STORAGE_LOC_ID_FK` FOREIGN KEY (`STORAGE_LOCATION_ID`) REFERENCES `STORAGE_LOCATION` (`ID`) ON DELETE CASCADE
)