CREATE TABLE IF NOT EXISTS `JDONODE` (
  `ID` bigint(20) NOT NULL,
  `CREATED_BY` bigint(20) NOT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  `CURRENT_REV_NUM` bigint(20) DEFAULT NULL,
  `ETAG` char(36) NOT NULL,
  `NAME` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `NODE_TYPE` ENUM('project', 'folder', 'link','file','table','entityview','dockerrepo') NOT NULL,
  `PARENT_ID` bigint(20) DEFAULT NULL,
  `ALIAS` varchar(64) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NODE_UNIQUE_CHILD_NAME` (`PARENT_ID`,`NAME`),
  KEY `JDONODE_KEY_TYPE` (`NODE_TYPE`),
  KEY `JDONODE_KEY_PAR` (`PARENT_ID`),
  INDEX `NODE_NAME_INDEX` (`NAME` ASC),
  UNIQUE KEY `NODE_UNIQUE_ALIAS` (`ALIAS`),
  CONSTRAINT `NODE_PARENT_FK` FOREIGN KEY (`PARENT_ID`) REFERENCES `JDONODE` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `NODE_CREATED_BY_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `JDOUSERGROUP` (`ID`)
)
