CREATE TABLE IF NOT EXISTS `NODE_TYPE_ALIAS` (
  `OWNER_TYPE` smallint(6) NOT NULL,
  `ALIAS` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`OWNER_TYPE`, `ALIAS`),
  KEY `ALIAS_INDEX` (`ALIAS`),
  CONSTRAINT `NODE_TYPE_ALIAS_FK` FOREIGN KEY (`OWNER_TYPE`) REFERENCES `NODE_TYPE` (`ID`) ON DELETE CASCADE
)
