CREATE TABLE IF NOT EXISTS `NOTIFICATION_EMAIL` (
  `ID` bigint NOT NULL,
  `ETAG` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `PRINCIPAL_ID` bigint NOT NULL,
  `ALIAS_ID` bigint NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_NOTIFICATION_EMAIL_PRINCIPAL_ID` (`PRINCIPAL_ID`),
  UNIQUE KEY `UNIQUE_NOTIFICATION_EMAIL_ALIAS_ID` (`ALIAS_ID`),
  CONSTRAINT `NOTIFICATION_E_ALIAS_ID_FK` FOREIGN KEY (`ALIAS_ID`) REFERENCES `PRINCIPAL_ALIAS` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `NOTIFICATION_E_PRINCIPAL_ID_FK` FOREIGN KEY (`PRINCIPAL_ID`) REFERENCES `USER_GROUP` (`ID`) ON DELETE CASCADE
)