CREATE TABLE IF NOT EXISTS `OAUTH_SECTOR_IDENTIFIER` (
  `OAUTH_SECTOR_IDENTIFIER_ID` bigint(20) NOT NULL,
  `OAUTH_SECTOR_IDENTIFIER_URI` varchar(256) NOT NULL UNIQUE,
  `OAUTH_SECTOR_IDENTIFIER_ENCRYPTED_SECRET` varchar(256) NOT NULL,
  `OAUTH_SECTOR_IDENTIFIER_CREATED_BY` bigint(20) NOT NULL,
  `OAUTH_SECTOR_IDENTIFIER_CREATED_ON` bigint(20) NOT NULL,
  PRIMARY KEY (`OAUTH_SECTOR_IDENTIFIER_ID`),
  CONSTRAINT `OAUTH_SECTOR_IDENTIFIER_CREATED_BY_FK` FOREIGN KEY (`OAUTH_SECTOR_IDENTIFIER_CREATED_BY`) REFERENCES `JDOUSERGROUP` (`ID`)
)
