CREATE TABLE IF NOT EXISTS `OAUTH_ACCESS_TOKEN` (
  `ID` BIGINT NOT NULL,
  `ETAG` CHAR(36) NOT NULL,
  `TOKEN_ID` CHAR(36) NOT NULL,
  `PRINCIPAL_ID` BIGINT NOT NULL,
  `CLIENT_ID` BIGINT NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `EXPIRES_ON` TIMESTAMP(3) DEFAULT NULL,
  `CONTEXT` JSON NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `OAUTH_ACCESS_TOKEN_TOKEN_ID_KEY` (`TOKEN_ID`),
  CONSTRAINT `OAUTH_REFRESH_TOKEN_PRINCIPAL_RESOURCE_OWNER_FK` FOREIGN KEY (`PRINCIPAL_ID`) REFERENCES `USER_GROUP` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `OAUTH_REFRESH_TOKEN_CLIENT_ID_FK` FOREIGN KEY (`CLIENT_ID`) REFERENCES `OAUTH_CLIENT` (`ID`) ON DELETE CASCADE
)