CREATE TABLE IF NOT EXISTS `OAUTH_SECTOR_IDENTIFIER` (
  `OAUTH_SECTOR_IDENTIFIER_ID` bigint(20) NOT NULL,
  `OAUTH_SECTOR_IDENTIFIER_URI` varchar(256) NOT NULL,
  `OAUTH_SECTOR_IDENTIFIER_SALT` varchar(256) NOT NULL,
  PRIMARY KEY (`OAUTH_SECTOR_IDENTIFIER_ID`),
  UNIQUE KEY (`OAUTH_SECTOR_IDENTIFIER_URI`)
)
