CREATE TABLE IF NOT EXISTS `OAUTH_CLIENT` (
  `OAUTH_CLIENT_ID` bigint(20) NOT NULL,
  `OAUTH_CLIENT_SECRET` char(36) NOT NULL,
  `OAUTH_SECTOR_IDENTIFIER_ID` bigint(20) NOT NULL,
  `OAUTH_CLIENT_PROPERTIES` mediumblob,
  `OAUTH_CLIENT_CREATED_BY` bigint(20) NOT NULL,
  `OAUTH_CLIENT_CREATED_ON` bigint(20) NOT NULL,
  `OAUTH_CLIENT_MODIFIED_ON` bigint(20) NOT NULL,
  `OAUTH_CLIENT_ETAG` char(36) NOT NULL,
  PRIMARY KEY (`OAUTH_CLIENT_ID`),
  CONSTRAINT `OAUTH_CLIENT_SECTOR_IDENTIFIER_FK` FOREIGN KEY (`OAUTH_SECTOR_IDENTIFIER_ID`) REFERENCES `OAUTH_SECTOR_IDENTIFIER` (`OAUTH_SECTOR_IDENTIFIER_ID`),
  CONSTRAINT `OAUTH_CLIENT_CREATED_BY_FK` FOREIGN KEY (`OAUTH_CLIENT_CREATED_BY`) REFERENCES `JDOUSERGROUP` (`ID`)
)


	
	