CREATE TABLE IF NOT EXISTS `PASSWORD_RESET_TOKEN`(
  `USER_ID` bigint(20) NOT NULL,
  `PASSWORD_RESET_TOKEN_HASH` varchar(73) DEFAULT NULL,
  `LOCKOUT_EXPIRATION` bigint(20) NOT NULL DEFAULT 0,
  PRIMARY KEY (`USER_ID`),
  CONSTRAINT `USER_ID_FK` FOREIGN KEY (`USER_ID`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE,
);