CREATE TABLE IF NOT EXISTS `PERSONAL_ACCESS_TOKEN` (
  `ID` BIGINT NOT NULL,
  `NAME` VARCHAR(256) NOT NULL,
  `PRINCIPAL_ID` BIGINT NOT NULL,
  `SCOPES` MEDIUMBLOB NOT NULL,
  `CLAIMS` MEDIUMBLOB NOT NULL,
  `LAST_USED` TIMESTAMP(3) NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `PERSONAL_ACCESS_TOKEN_PRINCIPAL_FK` FOREIGN KEY (`PRINCIPAL_ID`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE,
  UNIQUE (`PRINCIPAL_ID`, `NAME`)
)
