CREATE TABLE IF NOT EXISTS `PREVIEW_BLOB` (
  `OWNER_NODE_ID` bigint(20) NOT NULL,
  `TOKEN_ID` bigint(20) NOT NULL,
  `PREVIEW_BLOB` mediumblob,
  PRIMARY KEY (`OWNER_NODE_ID`,`TOKEN_ID`),
  CONSTRAINT `PREVIEW_OWNER_FK` FOREIGN KEY (`OWNER_NODE_ID`) REFERENCES `JDONODE` (`ID`) ON DELETE CASCADE
)
