CREATE TABLE IF NOT EXISTS `PRINCIPAL_OIDC_BINDING` (
  `ID` BIGINT NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `PRINCIPAL_ID` BIGINT NOT NULL,
  `PROVIDER` ENUM('GOOGLE_OAUTH_2_0') NOT NULL,
  `SUBJECT` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `PRINCIPAL_OIDC_SUBJECT_PRINCIPAL_ID_FK` FOREIGN KEY (`PRINCIPAL_ID`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE,
  UNIQUE (`PROVIDER`, `SUBJECT`)
)