CREATE TABLE IF NOT EXISTS `PRINCIPAL_OIDC_BINDING` (
  `ID` BIGINT NOT NULL,
  `ETAG` char(36) NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `PRINCIPAL_ID` BIGINT NOT NULL,
  `ALIAS_ID` BIGINT,
  `PROVIDER` ENUM('GOOGLE_OAUTH_2_0', 'ORCID') NOT NULL,
  `SUBJECT` VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `PRINCIPAL_OIDC_SUBJECT_PRINCIPAL_ID_FK` FOREIGN KEY (`PRINCIPAL_ID`) REFERENCES `USER_GROUP` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `PRINCIPAL_OIDC_SUBJECT_PRINCIPAL_ALIAS_ID_FK` FOREIGN KEY (`ALIAS_ID`) REFERENCES `PRINCIPAL_ALIAS` (`ID`) ON DELETE CASCADE,
  UNIQUE (`PROVIDER`, `SUBJECT`)
)