CREATE TABLE IF NOT EXISTS `PRINCIPAL_ALIAS` (
  `ID` bigint NOT NULL,
  `ETAG` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `PRINCIPAL_ID` bigint NOT NULL,
  `ALIAS_UNIQUE` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `ALIAS_DISPLAY` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `TYPE` enum('USER_NAME','TEAM_NAME','USER_EMAIL','USER_OPEN_ID','USER_ORCID') NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PRINCIPAL_ALIAS_UNIQUE` (`ALIAS_UNIQUE`),
  KEY `PRINCIPAL_A_PRINCIPAL_ID_FK` (`PRINCIPAL_ID`),
  CONSTRAINT `PRINCIPAL_A_PRINCIPAL_ID_FK` FOREIGN KEY (`PRINCIPAL_ID`) REFERENCES `USER_GROUP` (`ID`) ON DELETE CASCADE
)