CREATE TABLE IF NOT EXISTS `PROJECT_SETTING` (
  `ID` bigint NOT NULL,
  `PROJECT_ID` bigint NOT NULL,
  `TYPE` enum('upload') NOT NULL,
  `ETAG` char(36) NOT NULL,
  `SETTINGS` JSON,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_PSID_TYPE` (`PROJECT_ID`,`TYPE`),
  CONSTRAINT `PROJECT_S_PROJECT_ID_FK` FOREIGN KEY (`PROJECT_ID`) REFERENCES `NODE` (`ID`) ON DELETE CASCADE
)