CREATE TABLE IF NOT EXISTS `PROJECT_STAT` (
  `ID` bigint NOT NULL,
  `PROJECT_ID` bigint NOT NULL,
  `USER_ID` bigint NOT NULL,
  `LAST_ACCESSED` TIMESTAMP(3) NOT NULL,
  `ETAG` char(36) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_PSTAT_PID_USER` (`PROJECT_ID`,`USER_ID`),
  KEY `PROJECT_STAT_USR_ID_FK` (`USER_ID`),
  CONSTRAINT `PROJECT_STAT_PROJ_ID_FK` FOREIGN KEY (`PROJECT_ID`) REFERENCES `NODE` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `PROJECT_STAT_USR_ID_FK` FOREIGN KEY (`USER_ID`) REFERENCES `USER_GROUP` (`ID`) ON DELETE CASCADE
)