CREATE TABLE `QUIZ_RESPONSE` (
  `ID` bigint NOT NULL,
  `ETAG` char(36) NOT NULL,
  `CREATED_BY` bigint NOT NULL,
  `CREATED_ON` bigint NOT NULL,
  `REVOKED_ON` bigint DEFAULT NULL,
  `QUIZ_ID` bigint NOT NULL,
  `SCORE` bigint NOT NULL,
  `PASSED` bit(1) NOT NULL,
  `SERIALIZED` mediumblob NOT NULL,
  `PASSING_RECORD` mediumblob NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `QUIZ_R_CREATED_BY_FK` (`CREATED_BY`),
  CONSTRAINT `QUIZ_R_CREATED_BY_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `user_group` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
