CREATE TABLE IF NOT EXISTS `SYNAPSE_REALM_IDP` (
  `REALM_ID` BIGINT NOT NULL,
  `PROVIDER` ENUM('SYNAPSE', 'GOOGLE_OAUTH_2_0', 'ORCID', 'ARCUS_BIOSCIENCES', 'SAGE_BIONETWORKS') NOT NULL,
  PRIMARY KEY (`REALM_ID`, `PROVIDER`),
  UNIQUE (`PROVIDER`),
  CONSTRAINT `REALM_ID_REALM_FK` FOREIGN KEY (`REALM_ID`) REFERENCES `SYNAPSE_REALM` (`ID`) ON DELETE CASCADE
)
