CREATE TABLE IF NOT EXISTS `SYNAPSE_REALM` (
  `ID` BIGINT NOT NULL,
  `NAME` varchar(250) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE (`NAME`)
)
