CREATE TABLE IF NOT EXISTS `SYNAPSE_REALM_PRINCIPAL` (
  `ID` BIGINT NOT NULL,
  `REALM_ID` BIGINT NOT NULL,
  `PRINCIPAL_ID` BIGINT NOT NULL,
  `TYPE` ENUM('ANONYMOUS', 'PUBLIC', 'AUTHENTICATED', 'ADMINISTRATORS') NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE (`PRINCIPAL_ID`),
  UNIQUE (`REALM_ID`, `TYPE`),
  CONSTRAINT `REALM_PRINCIPAL_REALM_FK` FOREIGN KEY (`REALM_ID`) REFERENCES `SYNAPSE_REALM` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `PRINCIPAL_FK` FOREIGN KEY (`PRINCIPAL_ID`) REFERENCES `USER_GROUP` (`ID`) ON DELETE RESTRICT
)
