CREATE TABLE IF NOT EXISTS `RECORDSET_VALIDATION_STATS` (
  `ID` BIGINT NOT NULL,
  `ETAG` CHAR(36) NOT NULL,
  `RECORDSET_ID` BIGINT NOT NULL,
  `RECORDSET_VERSION` BIGINT NOT NULL,
  `STATS_JSON` JSON NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_RECORDSET_ID_VERSION` (`RECORDSET_ID`,`RECORDSET_VERSION`)
)