CREATE TABLE `jdoreference` (
  `REF_GROUP_NAME` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `REF_OWNER_NODE_ID` bigint(20) NOT NULL,
  `REF_TARGET_NODE_ID` bigint(20) NOT NULL,
  `REF_TARGET_REV_NUM` bigint(20) NOT NULL,
  PRIMARY KEY (`REF_GROUP_NAME`,`REF_OWNER_NODE_ID`,`REF_TARGET_NODE_ID`,`REF_TARGET_REV_NUM`),
  KEY `JDOREFERENCE_N49` (`REF_OWNER_NODE_ID`),
  CONSTRAINT `REFERENCE_OWNER_FK` FOREIGN KEY (`REF_OWNER_NODE_ID`) REFERENCES `jdonode` (`ID`) ON DELETE CASCADE
)