CREATE TABLE IF NOT EXISTS `JDOREFERENCE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `REF_GROUP_NAME` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `REF_OWNER_NODE_ID` bigint(20) NOT NULL,
  `REF_TARGET_NODE_ID` bigint(20) NOT NULL,
  `REF_TARGET_REV_NUM` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `REFERENCE_UNIQUE` (`REF_GROUP_NAME`,`REF_OWNER_NODE_ID`,`REF_TARGET_NODE_ID`,`REF_TARGET_REV_NUM`),
  KEY `JDOREFERENCE_OWNER` (`REF_OWNER_NODE_ID`)
)
