CREATE TABLE IF NOT EXISTS `RESEARCH_PROJECT` (
  `ID` bigint(20) NOT NULL,
  `ACCESS_REQUIREMENT_ID` bigint(20) NOT NULL,
  `CREATED_BY` bigint(20) NOT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  `MODIFIED_BY` bigint(20) NOT NULL,
  `MODIFIED_ON` bigint(20) NOT NULL,
  `OWNER_ID` bigint(20) NOT NULL,
  `ETAG` char(36) NOT NULL,
  `PROJECT_LEAD` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `INSTITUTION` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `IDU` blob NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE (`ACCESS_REQUIREMENT_ID`, `OWNER_ID`),
  CONSTRAINT `RESEARCH_PROJECT_ACCESS_REQUIREMENT_ID_FK` FOREIGN KEY (`ACCESS_REQUIREMENT_ID`) REFERENCES `ACCESS_REQUIREMENT` (`ID`) ON DELETE RESTRICT
)
