CREATE TABLE `JDORESOURCEACCESS` (
  `ID` bigint(20) NOT NULL,
  `OWNER_ID` bigint(20) NOT NULL,
  `GROUP_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `RESOURCE_ACCESS_OWNER_FK` FOREIGN KEY (`OWNER_ID`) REFERENCES `ACL` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `RESOURCE_ACCESS_GROUP_ID_FK` FOREIGN KEY (`GROUP_ID`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE
)
