CREATE TABLE IF NOT EXISTS `ACL_RESOURCE_ACCESS_TYPE` (
  `ID_OID` BIGINT NOT NULL,
  `OWNER_ID` BIGINT NOT NULL,
  `STRING_ELE` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`ID_OID`,`STRING_ELE`),
  KEY `ACL_RESOURCE_ACCESS_ID` (`ID_OID`),
  CONSTRAINT `RES_ACCESS_TYP_OWNER_FK` FOREIGN KEY (`OWNER_ID`) REFERENCES `ACL` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `ACL_RESOURCE_ACCESS_ID_FK` FOREIGN KEY (`ID_OID`) REFERENCES `ACL_RESOURCE_ACCESS` (`ID`) ON DELETE CASCADE
)
