CREATE TABLE `jdoresourceaccess_accesstype` (
  `ID_OID` bigint(20) NOT NULL,
  `STRING_ELE` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`ID_OID`,`STRING_ELE`),
  KEY `JDORESOURCEACCESS_ACCESSTYPE_N49` (`ID_OID`),
  CONSTRAINT `JDORESOURCEACCESS_ACCESSTYPE_FK1` FOREIGN KEY (`ID_OID`) REFERENCES `jdoresourceaccess` (`ID`) ON DELETE CASCADE
)