CREATE TABLE `jdorevision` (
  `OWNER_NODE_ID` bigint(20) NOT NULL,
  `NUMBER` bigint(20) NOT NULL,
  `ANNOTATIONS` mediumblob,
  `COMMENT` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `LABEL` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `MODIFIED_BY` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `MODIFIED_ON` bigint(20) NOT NULL,
  `REFERENCES` mediumblob,
  PRIMARY KEY (`OWNER_NODE_ID`,`NUMBER`),
  UNIQUE KEY `UNIQUE_REVISION_LABEL` (`OWNER_NODE_ID`,`LABEL`),
  KEY `JDOREVISION_KEY_OWN` (`OWNER_NODE_ID`),
  CONSTRAINT `REVISION_OWNER_FK` FOREIGN KEY (`OWNER_NODE_ID`) REFERENCES `jdonode` (`ID`) ON DELETE CASCADE
)