CREATE TABLE IF NOT EXISTS `JDOREVISION` (
  `OWNER_NODE_ID` bigint(20) NOT NULL,
  `NUMBER` bigint(20) NOT NULL,
  `ACTIVITY_ID` bigint(20) DEFAULT NULL,
  `ANNOTATIONS` mediumblob,
  `COMMENT` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `LABEL` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `MODIFIED_BY` bigint(20) NOT NULL,
  `MODIFIED_ON` bigint(20) NOT NULL,
  `FILE_HANDLE_ID` bigint(20) DEFAULT NULL,
  `COLUMN_MODEL_IDS` mediumblob,
  `REFERENCES` mediumblob,
  PRIMARY KEY (`OWNER_NODE_ID`,`NUMBER`),
  UNIQUE KEY `UNIQUE_REVISION_LABEL` (`OWNER_NODE_ID`,`LABEL`),
  KEY `JDOREVISION_KEY_OWN` (`OWNER_NODE_ID`),
  CONSTRAINT `REVISION_ACTIVITY_ID_FK` FOREIGN KEY (`ACTIVITY_ID`) REFERENCES `ACTIVITY` (`ID`) ON DELETE SET NULL,
  CONSTRAINT `REVISION_OWNER_FK` FOREIGN KEY (`OWNER_NODE_ID`) REFERENCES `JDONODE` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `FILE_HANDLE_FK` FOREIGN KEY (`FILE_HANDLE_ID`) REFERENCES `FILES` (`ID`)  ON DELETE RESTRICT,
  CONSTRAINT `REVISION_MODIFIED_BY_FK` FOREIGN KEY (`MODIFIED_BY`) REFERENCES `JDOUSERGROUP` (`ID`)

)
