CREATE TABLE IF NOT EXISTS `SEARCH_CONFIGURATION` (
  `ID` BIGINT NOT NULL,
  `ETAG` char(36) NOT NULL,
  `ORGANIZATION_NAME` varchar(250) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  `NAME` varchar(256) NOT NULL,
  `DESCRIPTION` varchar(1000) DEFAULT NULL,
  `DEFAULT_ANALYZER` JSON DEFAULT NULL,
  `COLUMN_ANALYZER_OVERRIDES` JSON DEFAULT NULL,
  `COLUMN_SEMANTIC_ENRICHMENT` JSON DEFAULT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `MODIFIED_BY` BIGINT NOT NULL,
  `MODIFIED_ON` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SC_ORG_NAME_UQ` (`ORGANIZATION_NAME`, `NAME`),
  CONSTRAINT `SC_ORG_FK` FOREIGN KEY (`ORGANIZATION_NAME`) REFERENCES `ORGANIZATION` (`NAME`) ON DELETE RESTRICT,
  CONSTRAINT `SC_CREATED_BY_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE RESTRICT,
  CONSTRAINT `SC_MODIFIED_BY_FK` FOREIGN KEY (`MODIFIED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE RESTRICT
);
