CREATE TABLE IF NOT EXISTS `SESSION_TOKEN` (
  `PRINCIPAL_ID` bigint(20) NOT NULL,
  `VALIDATED_ON` bigint(20) DEFAULT NULL,
  `SESSION_TOKEN` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  PRIMARY KEY (`PRINCIPAL_ID`),
  UNIQUE KEY `SESSION_TOKEN_UNIQUE` (`SESSION_TOKEN`),
  CONSTRAINT `SESSION_T_PRINCIPAL_ID_FK` FOREIGN KEY (`PRINCIPAL_ID`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE
)