CREATE TABLE IF NOT EXISTS `JDOSTACKSTATUS` (
  `ID` bigint(20) NOT NULL,
  `CURRENT_MESSAGE` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `PENDING_MESSAGE` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `STATUS` ENUM('READ_WRITE','READ_ONLY', 'DOWN') NOT NULL,
  PRIMARY KEY (`ID`)
)
