CREATE TABLE IF NOT EXISTS `JDOSTACKSTATUS` (
  `ID` BIGINT NOT NULL,
  `CURRENT_MESSAGE` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `PENDING_MESSAGE` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `STATUS` ENUM('READ_WRITE','READ_ONLY', 'DOWN') NOT NULL,
  PRIMARY KEY (`ID`)
)
