CREATE TABLE IF NOT EXISTS `JDOSTACKSTATUS` (
  `ID` bigint(20) NOT NULL,
  `CURRENT_MESSAGE` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `PENDING_MESSAGE` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `STATUS` smallint(6) NOT NULL,
  PRIMARY KEY (`ID`)
)
