CREATE TABLE `STORAGE_LOCATION` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
	`NODE_ID` bigint(20) NOT NULL,
	`USER_ID` bigint(20) NOT NULL,
	`LOCATION` varchar(2000) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
	`IS_ATTACHMENT` boolean NOT NULL,
	`STORAGE_PROVIDER` varchar(50) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
	`CONTENT_TYPE` varchar(500) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
	`CONTENT_SIZE` bigint(20) DEFAULT NULL,
	`CONTENT_MD5` varchar(100) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
	PRIMARY KEY (`ID`)
)