CREATE TABLE `STORAGE_LOCATION` (
  `PRINCIPAL_ID` bigint NOT NULL,
  `SESSION_TOKEN` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  PRIMARY KEY (`PRINCIPAL_ID`),
  UNIQUE KEY `UNIQUE_SESSION_TOKEN` (`SESSION_TOKEN`),
  CONSTRAINT `SESSION_T_PRINCIPAL_ID_FK` FOREIGN KEY (`PRINCIPAL_ID`) REFERENCES `user_group` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
