CREATE TABLE `STORAGE_LOCATION` (
  `ID` bigint NOT NULL,
  `DESCRIPTION` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `UPLOAD_TYPE` enum('S3','GOOGLECLOUDSTORAGE','SFTP','HTTPS','PROXYLOCAL','NONE') NOT NULL DEFAULT 'NONE',
  `ETAG` char(36) NOT NULL,
  `JSON` JSON,
  `DATA_HASH` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `CREATED_BY` bigint NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CREATED_BY_DATA_HASH_INDEX` (`CREATED_BY`,`DATA_HASH`)
)