# Note, the table name should be 'SUBJECT_ACCESS_REQUIREMENT' but migration issues prevent 
# us from using that name at this time.

CREATE TABLE IF NOT EXISTS `NODE_ACCESS_REQUIREMENT` (
	`SUBJECT_ID` BIGINT  NOT NULL,
	`SUBJECT_TYPE` ENUM('ENTITY', 'EVALUATION', 'TEAM') NOT NULL,
	`REQUIREMENT_ID` BIGINT NOT NULL,
	PRIMARY KEY (`SUBJECT_ID`, `SUBJECT_TYPE`, `REQUIREMENT_ID`),
	CONSTRAINT `SUBJECT_ACCESS_REQUIREMENT_REQUIREMENT_ID_FK` FOREIGN KEY (`REQUIREMENT_ID`) REFERENCES `ACCESS_REQUIREMENT` (`ID`) ON DELETE CASCADE
)
