CREATE TABLE `TABLE_STATUS` (
  `TABLE_ID` bigint(20) NOT NULL,
  `VERSION` bigint(20) NOT NULL,
  `STATE` enum('AVAILABLE','PROCESSING','PROCESSING_FAILED') NOT NULL,
  `RESET_TOKEN` char(200) NOT NULL,
  `LAST_TABLE_CHANGE_ETAG` char(200) DEFAULT NULL,
  `STARTED_ON` bigint(20) NOT NULL,
  `CHANGED_ON` bigint(20) NOT NULL,
  `PROGRESS_MESSAGE` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `PROGRESS_CURRENT` bigint(20) DEFAULT NULL,
  `PROGRESS_TOTAL` bigint(20) DEFAULT NULL,
  `ERROR_MESSAGE` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ERROR_DETAILS` mediumblob,
  `RUNTIME_MS` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`TABLE_ID`, `VERSION`)
);
