CREATE TABLE IF NOT EXISTS `TABLE_TRANSACTION` (
  `TRX_ID` BIGINT NOT NULL,
  `TABLE_ID` BIGINT NOT NULL,
  `STARTED_BY` BIGINT NOT NULL,
  `STARTED_ON` BIGINT NOT NULL,
  `ETAG` char(36) NOT NULL,
  PRIMARY KEY (`TRX_ID`),
  INDEX (`TABLE_ID`),
  CONSTRAINT `TRX_USER_ID_FK` FOREIGN KEY (`STARTED_BY`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE
)
