CREATE TABLE IF NOT EXISTS `TABLE_ID_SEQUENCE` (
  `TABLE_ID` bigint(20) NOT NULL,
  `ETAG` char(36) NOT NULL,
  `ROW_VERSION` bigint(20) NOT NULL,
  `SEQUENCE` bigint(20) NOT NULL,
  PRIMARY KEY (`TABLE_ID`)
)
