CREATE TABLE IF NOT EXISTS `TABLE_SNAPSHOT` (
  `SNAPSHOT_ID` BIGINT NOT NULL,
  `TABLE_ID` BIGINT NOT NULL,
  `VERSION` BIGINT NOT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` timestamp(3) NOT NULL,
  `BUCKET_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `KEY` varchar(700) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`SNAPSHOT_ID`),
  UNIQUE (`TABLE_ID`, `VERSION`),
  CONSTRAINT `TABLE_SNAP_CREATOR_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE CASCADE
)
