CREATE TABLE `TABLE_CHANGE` (
  `CHANGE_NUMBER` bigint(20) NOT NULL,
  `TABLE_ID` bigint(20) NOT NULL,
  `TABLE_VERSION` bigint(20) NOT NULL,
  `FILE_HANDLE_ID`  bigint(20)  NOT NULL,
  PRIMARY KEY (`CHANGE_NUMBER`),
  KEY `KEY_KEY` (`TABLE_IDs`),
  CONSTRAINT `TABLE_DEL_CREATED_BY_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `JDOUSERGROUP` (`ID`),
  CONSTRAINT `TABLE_CHG_FLE_HD_FK` FOREIGN KEY (`FILE_HANDLE_ID`) REFERENCES `FILES` (`ID`) ON DELETE CASCADE
)