CREATE TABLE IF NOT EXISTS `TABLE_ROW_CHANGE` (
  `TABLE_ID` bigint(20) NOT NULL,
  `ROW_VERSION` bigint(20) NOT NULL,
  `ETAG` char(36) NOT NULL,
  `COLUMN_IDS`  varchar(1000) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `CREATED_BY`  bigint(20)  NOT NULL,
  `CREATED_ON`  bigint(20)  NOT NULL,
  `S3_BUCKET`	varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `S3_KEY`		varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `ROW_COUNT` bigint(20) NOT NULL,
  PRIMARY KEY (`TABLE_ID`,`ROW_VERSION`),
  KEY `TRC_ETAG_INDEX` (`ETAG`),
  CONSTRAINT `TABLE_DEL_CREATED_BY_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `JDOUSERGROUP` (`ID`),
  CONSTRAINT `TABLE_ID_FK` FOREIGN KEY (`TABLE_ID`) REFERENCES `TABLE_ID_SEQUENCE` (`TABLE_ID`) ON DELETE CASCADE
)
