CREATE TABLE IF NOT EXISTS `TABLE_ID_SEQUENCE` (
  `TABLE_ID` BIGINT NOT NULL,
  `ETAG` char(36) NOT NULL,
  `ROW_VERSION` BIGINT NOT NULL,
  `SEQUENCE` BIGINT NOT NULL,
  PRIMARY KEY (`TABLE_ID`)
)
