CREATE TABLE IF NOT EXISTS `TABLE_ROW_CHANGE` (
  `TABLE_ID` BIGINT NOT NULL,
  `ROW_VERSION` BIGINT NOT NULL,
  `ETAG` char(36) NOT NULL,
  `CREATED_BY`  BIGINT  NOT NULL,
  `CREATED_ON`  BIGINT  NOT NULL,
  `S3_BUCKET`	varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `S3_KEY`		varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `ROW_COUNT` BIGINT NOT NULL,
  `CHANGE_TYPE` ENUM('ROW','COLUMN') DEFAULT 'ROW',
  `TRX_ID` BIGINT DEFAULT NULL,
  PRIMARY KEY (`TABLE_ID`,`ROW_VERSION`),
  KEY `TRC_ETAG_INDEX` (`ETAG`),
  CONSTRAINT `TABLE_TRX_ID_FK` FOREIGN KEY (`TRX_ID`) REFERENCES `TABLE_TRANSACTION` (`TRX_ID`) ON DELETE RESTRICT,
  CONSTRAINT `TABLE_ID_FK` FOREIGN KEY (`TABLE_ID`) REFERENCES `TABLE_ID_SEQUENCE` (`TABLE_ID`) ON DELETE CASCADE
)
