CREATE TABLE `TEAM` (
  `ID` bigint(20) NOT NULL,
  `ETAG` char(36) NOT NULL,
  `PROPERTIES` mediumblob,
  PRIMARY KEY (`ID`),
  CONSTRAINT `TEAM_USERGROUP_FK` FOREIGN KEY (`ID`) REFERENCES `JDOUSERGROUP` (`ID`)
)