CREATE TABLE `TERMS_OF_USE_AGREEMENT` (
  `PRINCIPAL_ID` bigint(20) NOT NULL,
  `DOMAIN` varchar(20) NOT NULL,
  `AGREES_TO_TERMS_OF_USE` bit(1) DEFAULT NULL,
  PRIMARY KEY (`PRINCIPAL_ID`, `DOMAIN`), 
  CONSTRAINT `TOU_PRINCIPAL_ID_FK` FOREIGN KEY (`PRINCIPAL_ID`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE
)