CREATE TABLE IF NOT EXISTS `THREAD` (
  `ID` bigint(20) NOT NULL,
  `FORUM_ID` bigint(20) NOT NULL,
  `TITLE` tinyblob NOT NULL,
  `ETAG` char(36) NOT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  `CREATED_BY` bigint(20) NOT NULL,
  `MODIFIED_ON` bigint(20) NOT NULL,
  `MESSAGE_URL` char(36) NOT NULL,
  `IS_EDITED` boolean NOT NULL,
  `IS_DELETED` boolean NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE (`MESSAGE_URL`),
  CONSTRAINT `THREAD_FORUM_ID_FK` FOREIGN KEY (`FORUM_ID`) REFERENCES `FORUM` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `THREAD_CREATED_BY_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `JDOUSERGROUP` (`ID`)
)
