CREATE TABLE `THROTTLE_RULES`(
    `THROTTLE_ID` BIGINT unsigned NOT NULL,
    `NORMALIZED_PATH` varchar(255) NOT NULL,
    `MAX_CALLS_PER_USER_PER_PERIOD` BIGINT unsigned NOT NULL,
    `PERIOD_IN_SECONDS` BIGINT unsigned NOT NULL,
    `MODIFIED_ON` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(`THROTTLE_ID`),
    UNIQUE (`NORMALIZED_PATH`)
);