CREATE TABLE `THROTTLE_RULES`(
    `THROTTLE_ID` bigint(20) unsigned,
    `NORMALIZED_URI` varchar(256) NOT NULL,
    `MAX_CALLS` int(20) unsigned NOT NULL,
    `CALL_PERIOD_IN_SECONDS` int(20) unsigned  NULL,
    `MODIFIED_ON` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`NORMALIZED_URI`),
    UNIQUE (`THROTTLE_ID`)
);