CREATE TABLE IF NOT EXISTS `TRASH_CAN` (
	`NODE_ID`     bigint(20)    NOT NULL,
	`NODE_NAME`   varchar(256)  CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
	`DELETED_BY`  bigint(20)    NOT NULL,
	`DELETED_ON`  TIMESTAMP     NOT NULL,
	`PARENT_ID`   bigint(20)    NOT NULL,
	PRIMARY KEY (`NODE_ID`),
	CONSTRAINT `TRASH_CAN_DELETED_BY_FK_IDX` FOREIGN KEY (`DELETED_BY`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE,
	INDEX `TRASH_CAN_DELETED_ON_IDX` (`DELETED_ON`),
	INDEX `TRASH_CAN_PARENT_ID_IDX` (`PARENT_ID`)
)
