CREATE TABLE IF NOT EXISTS `TRASH_CAN` (
	`NODE_ID`     bigint(20)    NOT NULL,
	`NODE_NAME`   varchar(256)  CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
	`DELETED_BY`  bigint(20)    NOT NULL,
	`DELETED_ON`  TIMESTAMP     NOT NULL,
	`PARENT_ID`   bigint(20)    NOT NULL,
	PRIMARY KEY (`NODE_ID`),
	CONSTRAINT `TRASH_CAN_DELETED_BY_FK_IDX` FOREIGN KEY (`DELETED_BY`) REFERENCES `JDOUSERGROUP` (`ID`),
	INDEX `TRASH_CAN_DELETED_ON_IDX` (`DELETED_ON`)
)
