CREATE TABLE IF NOT EXISTS `TRASH_CAN` (
	`NODE_ID`     		BIGINT    NOT NULL,
	`NODE_NAME`   		varchar(256)  CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
	`DELETED_BY`  		BIGINT    NOT NULL,
	`DELETED_ON`  		TIMESTAMP     NOT NULL,
	`PARENT_ID`   		BIGINT    NOT NULL,
	`ETAG` 				char(36) 	  NOT NULL,
	`PRIORITY_PURGE`	boolean 	  NOT NULL DEFAULT FALSE,
	PRIMARY KEY (`NODE_ID`),
	CONSTRAINT `TRASH_CAN_DELETED_BY_FK_IDX` FOREIGN KEY (`DELETED_BY`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE,
	INDEX `TRASH_CAN_DELETED_ON_IDX` (`DELETED_ON`),
	INDEX `TRASH_CAN_PARENT_ID_IDX` (`PARENT_ID`),
	INDEX `TRASH_CAN_PRIORITY_PURGE_IDX` (`PRIORITY_PURGE`)
)
