CREATE TABLE IF NOT EXISTS `UNSUCCESSFUL_LOGIN_LOCKOUT`(
  `USER_ID` bigint(20) NOT NULL,
  `UNSUCCESSFUL_LOGIN_COUNT` bigint(20) NOT NULL,
  `LOCKOUT_EXPIRATION` bigint(20) NOT NULL,
  PRIMARY KEY (`ATTEMPT_KEY`)
);