CREATE TABLE IF NOT EXISTS `UNSUCCESSFUL_LOGIN_LOCKOUT`(
  `USER_ID` BIGINT NOT NULL,
  `UNSUCCESSFUL_LOGIN_COUNT` BIGINT NOT NULL,
  `LOCKOUT_EXPIRATION` BIGINT NOT NULL,
  PRIMARY KEY (`USER_ID`),
  CONSTRAINT `USER_ID_FK` FOREIGN KEY (`USER_ID`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE
);