CREATE TABLE IF NOT EXISTS 'UNSUCCESSFUL_ATTEMPT_LOCKOUT'(
  `KEY` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `UNSUCESSFUL_ATTEMPT_COUNT` bigint(20) NOT NULL,
  `LOCKOUT_EXPIRATION` TIMESTAMP NOT NULL,
  PRIMARY KEY (`KEY`)
)