CREATE TABLE `UPLOAD_STATUS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `STATE` ENUM('FAILED', 'COMPLETED', 'PROCESSING') NOT null,
  `STARTED_BY` bigint(20) NOT NULL,  
  `STARTED_ON` bigint(20) NOT NULL,
  `PERCENT_COMPLETE` FLOAT NOT NULL,
  `ERROR_MESSAGE` varchar(3000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `FILE_HANDLE_IDS` bigint(20) DEFAULT NULL,  
  `RUNTIME_MS` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `UP_STAT_STARTED_BY_FK` FOREIGN KEY (`STARTED_BY`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE
)

