CREATE TABLE IF NOT EXISTS `USER_STATUS` (
  `PRINCIPAL_ID` BIGINT NOT NULL,
  `ETAG` CHAR(36) NOT NULL,
  `LAST_SEEN_ON` TIMESTAMP(3) DEFAULT NULL,
  `DISABLED` BOOLEAN DEFAULT FALSE,
  `WARNED_ON` TIMESTAMP(3) DEFAULT NULL,
  PRIMARY KEY (`PRINCIPAL_ID`),
  INDEX `USER_STATUS_LAST_SEEN_ON_WARNED_ON_INDEX` (`DISABLED`, `LAST_SEEN_ON`, `WARNED_ON`),
  CONSTRAINT `USER_STATUS_PRINCIPAL_ID_FK` FOREIGN KEY (`PRINCIPAL_ID`) REFERENCES `USER_GROUP` (`ID`) ON DELETE CASCADE
)