CREATE TABLE IF NOT EXISTS `V2_WIKI_MARKDOWN` (
	`WIKI_ID` bigint(20)  NOT NULL,
	`FILE_HANDLE_ID`  bigint(20)  NOT NULL,
	`MARKDOWN_VERSION` bigint(20) NOT NULL,
	`MODIFIED_ON` bigint(20) NOT NULL,
	`MODIFIED_BY` bigint(20) NOT NULL,
	`TITLE` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
	`ATTACHMENT_ID_LIST` mediumblob DEFAULT NULL,
	UNIQUE KEY `V2_WIKI_UNIQUE_MARKDOWN_VERSION` (`WIKI_ID`,`MARKDOWN_VERSION`),
	CONSTRAINT `V2_WIKI_MARKDOWN_FK` FOREIGN KEY (`WIKI_ID`) REFERENCES `V2_WIKI_PAGE` (`ID`) ON DELETE CASCADE,
	CONSTRAINT `V2_WIKI_MARKDOWN_FILE_HAND_FK` FOREIGN KEY (`FILE_HANDLE_ID`) REFERENCES `FILES` (`ID`) ON DELETE CASCADE
)
