CREATE TABLE IF NOT EXISTS `VALIDATION_JSON_SCHEMA_INDEX` (
  `VERSION_ID` BIGINT NOT NULL,
  `VALIDATION_SCHEMA` JSON NOT NULL,
  PRIMARY KEY (`VERSION_ID`),
  CONSTRAINT FOREIGN KEY (`VERSION_ID`) REFERENCES `JSON_SCHEMA_VERSION` (`VERSION_ID`)
)