CREATE TABLE IF NOT EXISTS `VERIFICATION_FILE` (
  `VERIFICATION_ID` bigint NOT NULL,
  `FILE_HANDLE_ID` bigint NOT NULL,
  PRIMARY KEY (`VERIFICATION_ID`,`FILE_HANDLE_ID`),
  KEY `VERI_FILE_FILE_ID` (`FILE_HANDLE_ID`),
  CONSTRAINT `VERI_FILE_FILE_ID` FOREIGN KEY (`FILE_HANDLE_ID`) REFERENCES `FILES` (`ID`) ON DELETE RESTRICT,
  CONSTRAINT `VERI_FILE_VERI_ID` FOREIGN KEY (`VERIFICATION_ID`) REFERENCES `VERIFICATION_SUBMISSION` (`ID`) ON DELETE CASCADE
)