CREATE TABLE IF NOT EXISTS `VERIFICATION_SUBMISSION` (
  `ID` bigint NOT NULL,
  `ETAG` char(36) NOT NULL,
  `CREATED_BY` bigint NOT NULL,
  `CREATED_ON` bigint NOT NULL,
  `SERIALIZED` mediumblob NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_VERIFICATION_BY_ON` (`CREATED_BY`,`CREATED_ON`),
  CONSTRAINT `VERI_USER_GROUP_ID` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE CASCADE
)