CREATE TABLE IF NOT EXISTS `VIEW_SNAPSHOT` (
  `SNAPSHOT_ID` BIGINT NOT NULL,
  `VIEW_ID` BIGINT NOT NULL,
  `VERSION` BIGINT NOT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` timestamp(3) NOT NULL,
  `BUCKET_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `KEY` varchar(700) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`SNAPSHOT_ID`),
  UNIQUE (`VIEW_ID`, `VERSION`),
  CONSTRAINT `VIEW_SNAP_CREATOR_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `JDOUSERGROUP` (`ID`) ON DELETE CASCADE
)
