CREATE TABLE IF NOT EXISTS `VIEW_SCOPE` (
  `ID` bigint(20) NOT NULL,
  `VIEW_ID` bigint(20) NOT NULL,
  `CONTAINER_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE (`VIEW_ID`,`CONTAINER_ID`),
  INDEX (`VIEW_ID`),
  INDEX (`CONTAINER_ID`)
)
