CREATE TABLE IF NOT EXISTS `WEBHOOK_VERIFICATION` (
  `VERIFICATION_ID` BIGINT NOT NULL,
  `WEBHOOK_ID` BIGINT NOT NULL,
  `VERIFICATION_CODE` CHAR(6) NOT NULL,
  `EXPIRES_ON` TIMESTAMP(3) NOT NULL,
  `ATTEMPTS` BIGINT NOT NULL,
  `STATE` ENUM('PENDING_VERIFICATION', 'VERIFICATION_CODE_SENT', 'VERIFIED') NOT NULL,
  `ETAG` CHAR(36) NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `MODIFIED_ON` TIMESTAMP(3) NOT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `MODIFIED_BY` BIGINT NOT NULL,
  PRIMARY KEY (`VERIFICATION_ID`),
  CONSTRAINT `WEBHOOK_VERIFICATION_WEBHOOK_ID_FK` FOREIGN KEY (`WEBHOOK_ID`) REFERENCES `WEBHOOK` (`WEBHOOK_ID`) ON DELETE CASCADE
)