CREATE TABLE IF NOT EXISTS `WEBHOOK` (
  `WEBHOOK_ID` BIGINT NOT NULL,
  `OBJECT_ID` BIGINT NOT NULL,
  `OBJECT_TYPE` VARCHAR(255) NOT NULL,
  `USER_ID` BIGINT NOT NULL,
  `INVOKE_ENDPOINT` VARCHAR(255) NOT NULL,
  `IS_WEBHOOK_ENABLED` BOOLEAN NOT NULL,
  `IS_AUTHENTICATION_ENABLED` BOOLEAN NOT NULL,
  `ETAG` CHAR(36) NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `MODIFIED_ON` TIMESTAMP(3) NOT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `MODIFIED_BY` BIGINT NOT NULL,
  PRIMARY KEY (`WEBHOOK_ID`),
  INDEX `INDEX_USER_ID` (`USER_ID`),
  UNIQUE `UNIQUE_OBJECT_ENDPOINT` (`OBJECT_ID`, `OBJECT_TYPE`, `INVOKE_ENDPOINT`),
  CONSTRAINT `WEBHOOK_UID_FK` FOREIGN KEY (`USER_ID`) REFERENCES `USER_GROUP` (`ID`) ON DELETE CASCADE
)
