CREATE TABLE IF NOT EXISTS `V2_WIKI_MARKDOWN` (
  `WIKI_ID` bigint NOT NULL,
  `FILE_HANDLE_ID` bigint NOT NULL,
  `MARKDOWN_VERSION` bigint NOT NULL,
  `MODIFIED_ON` bigint NOT NULL,
  `MODIFIED_BY` bigint NOT NULL,
  `TITLE` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ATTACHMENT_ID_LIST` mediumblob,
  PRIMARY KEY (`WIKI_ID`,`MARKDOWN_VERSION`),
  UNIQUE KEY `V2_WIKI_UNIQUE_MARKDOWN_VERSION` (`WIKI_ID`,`MARKDOWN_VERSION`),
  KEY `V2_WIKI_MARKDOWN_FILE_HAND_FK` (`FILE_HANDLE_ID`),
  CONSTRAINT `V2_WIKI_MARKDOWN_FILE_HAND_FK` FOREIGN KEY (`FILE_HANDLE_ID`) REFERENCES `FILES` (`ID`) ON DELETE RESTRICT,
  CONSTRAINT `V2_WIKI_MARKDOWN_FK` FOREIGN KEY (`WIKI_ID`) REFERENCES `V2_WIKI_PAGE` (`ID`) ON DELETE CASCADE
)