CREATE TABLE IF NOT EXISTS `V2_WIKI_OWNERS` (
  `OWNER_ID` bigint NOT NULL,
  `OWNER_OBJECT_TYPE` enum('ENTITY','ENTITY_CONTAINER','PRINCIPAL','ACTIVITY','EVALUATION','EVALUATION_ROUND','SUBMISSION','EVALUATION_SUBMISSIONS','FILE','MESSAGE','WIKI','FAVORITE','ACCESS_REQUIREMENT','ACCESS_APPROVAL','TEAM','TABLE','ACCESS_CONTROL_LIST','PROJECT_SETTING','VERIFICATION_SUBMISSION','CERTIFIED_USER_PASSING_RECORD','FORUM','THREAD','REPLY','FORM_GROUP','ORGANIZATION','FORM_DATA','ENTITY_VIEW','USER_PROFILE','DATA_ACCESS_REQUEST','DATA_ACCESS_SUBMISSION','DATA_ACCESS_SUBMISSION_STATUS','MEMBERSHIP_INVITATION','JSON_SCHEMA','JSON_SCHEMA_DEPENDANT','DATASET','DATASET_COLLECTION','THREAD_VIEW','MATERIALIZED_VIEW','VIRTUAL_TABLE','TABLE_STATUS_EVENT','DATA_ACCESS_SUBMISSION_EVENT','FILE_EVENT','QUERY_CACHE_HIT') NOT NULL,
  `ROOT_WIKI_ID` bigint NOT NULL,
  `ORDER_HINT` mediumblob,
  `ETAG` char(36) NOT NULL,
  PRIMARY KEY (`OWNER_ID`,`OWNER_OBJECT_TYPE`),
  UNIQUE KEY `ROOT_WIKI_ID` (`ROOT_WIKI_ID`),
  CONSTRAINT `V2_WIKI_OWNER_FK` FOREIGN KEY (`ROOT_WIKI_ID`) REFERENCES `V2_WIKI_PAGE` (`ID`) ON DELETE CASCADE
)