CREATE TABLE `WIKI_PAGE` (
	`ID`     bigint(20)  NOT NULL,
	`ETAG` char(36) NOT NULL,
	`TITLE` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
	`CREATED_BY` bigint(20) NOT NULL,
	`CREATED_ON` bigint(20) NOT NULL,
	`MODIFIED_BY` bigint(20) NOT NULL,
	`MODIFIED_ON` bigint(20) NOT NULL,
	`PARENT_ID` bigint(20) DEFAULT NULL,
	`MARKDOWN` mediumblob DEFAULT NULL,
	PRIMARY KEY (`ID`),
	CONSTRAINT `WIKI_PARENT_FK` FOREIGN KEY (`PARENT_ID`) REFERENCES `WIKI_PAGE` (`ID`) ON DELETE CASCADE,
	CONSTRAINT `WIKI_CREATED_BY_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `JDOUSERGROUP` (`ID`),
	CONSTRAINT `WIKI_MODIFIED_BY_FK` FOREIGN KEY (`MODIFIED_BY`) REFERENCES `JDOUSERGROUP` (`ID`)
)