CREATE TABLE `WIKI_ATTACHMENTS` (
	`WIKI_ID` bigint(20)  NOT NULL,
	`FILE_HANDLE_ID`  bigint(20)  NOT NULL,
	`FILE_NAME`  varchar(100) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
	UNIQUE KEY `WIKI_UNIQUE_FILE_NAME` (`WIKI_ID`,`FILE_NAME`),
	CONSTRAINT `WIKI_ATTACH_FK` FOREIGN KEY (`WIKI_ID`) REFERENCES `WIKI_PAGE` (`ID`) ON DELETE CASCADE,
	CONSTRAINT `WIKI_FILE_HAND_FK` FOREIGN KEY (`FILE_HANDLE_ID`) REFERENCES `FILES` (`ID`) ON DELETE CASCADE
)