CREATE TABLE `WIKI_OWNERS` (
	`OWNER_ID` bigint(20)  NOT NULL,
	`OWNER_OBJECT_TYPE` ENUM('ENTITY', 'EVALUATION') NOT NULL,
	`ROOT_WIKI_ID` bigint(20) NOT NULL,
	PRIMARY KEY (`OWNER_ID`, `OWNER_OBJECT_TYPE`),
	CONSTRAINT `WIKI_OWNER_FK` FOREIGN KEY (`ROOT_WIKI_ID`) REFERENCES `WIKI_PAGE` (`ID`) ON DELETE CASCADE
)