package org.sagebionetworks.logging.reader;

import java.io.BufferedReader;
import java.io.IOException;
import java.util.regex.Matcher;

import org.joda.time.DateTime;
import org.sagebionetworks.logging.SynapseLoggingUtils;
import org.sagebionetworks.logging.collate.LogEvent;

/**
 * A class for reading LogEvents from the logs generated by the
 * {@link profiler.org.sagebionetworks.usagemetrics.ActivityLogger ActivityLogger}.
 * Methods for parsing the logs into an object can be found in
 * {@link org.sagebionetworks.logging.SynapseLoggingUtils SynapseLoggingUtils}.
 * @author geoff
 *
 */
public class ActivityLogReader implements LogReader {

	public static class ActivityLogReaderFactory implements LogReader.LogReaderFactory<ActivityLogReader> {
		@Override
		public ActivityLogReader create(BufferedReader rdr) {
			return new ActivityLogReader(rdr);
		}
	}

	private BufferedReader reader;

	private ActivityLogReader(BufferedReader rdr) {
		this.reader = rdr;
	}

	/**
	 * {@inheritDoc}
	 * This class assumes that each log event is on it's own line.  If the activity log format
	 * changes, this will need updating!
	 */
	@Override
	public LogEvent readLogEvent() throws IOException {
		String line = reader.readLine();
		if (line == null) return null;

		DateTime timestamp = extractTimestamp(line);
		return new LogEvent(timestamp, line);
	}

	private DateTime extractTimestamp(String line) {
		Matcher matcher = SynapseLoggingUtils.DATE_PATTERN.matcher(line);
		if (matcher.find())
			return SynapseLoggingUtils.DATE_FORMATTER.parseDateTime(matcher.group(1));
		else
			throw new IllegalArgumentException("Malformed log line: " + line);
	}

	@Override
	public void close() throws IOException {
		reader.close();
	}

}
