CREATE TABLE `STATISTICS_MONTHLY_PROJECT_FILES` (
  `PROJECT_ID` bigint(20) NOT NULL,
  `MONTH` DATE NOT NULL,
  `ACTION` enum('FILE_DOWNLOAD', 'FILE_UPLOAD') NOT NULL,
  `LAST_UPDATED_ON` bigint(20) NOT NULL,
  `FILES_COUNT` INT NOT NULL,
  `USERS_COUNT` INT NOT NULL,
  PRIMARY KEY (`PROJECT_ID`, `MONTH`, `ACTION`)
);