CREATE TABLE `STATISTICS_MONTHLY_STATUS` (
  `OBJECT_TYPE` enum('PROJECT') NOT NULL,
  `MONTH` DATE NOT NULL,
  `STATUS` enum('AVAILABLE','PROCESSING','PROCESSING_FAILED') NOT NULL,
  PRIMARY KEY (`OBJECT_TYPE`, `MONTH`)
);