CREATE TABLE `STATISTICS_MONTHLY_PROJECT_FILES` (
  `PROJECT_ID` BIGINT NOT NULL,
  `MONTH` DATE NOT NULL,
  `EVENT_TYPE` enum('FILE_DOWNLOAD', 'FILE_UPLOAD') NOT NULL,
  `LAST_UPDATED_ON` BIGINT NOT NULL,
  `FILES_COUNT` INT NOT NULL,
  `USERS_COUNT` INT NOT NULL,
  PRIMARY KEY (`PROJECT_ID`, `MONTH`, `EVENT_TYPE`)
);