CREATE TABLE `STATISTICS_MONTHLY_STATUS` (
  `OBJECT_TYPE` enum('PROJECT') NOT NULL,
  `MONTH` DATE NOT NULL,
  `STATUS` enum('AVAILABLE','PROCESSING','PROCESSING_FAILED') NOT NULL,
  `LAST_STARTED_ON` BIGINT DEFAULT NULL,
  `LAST_UPDATED_ON` BIGINT DEFAULT NULL,
  `ERROR_MESSAGE` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ERROR_DETAILS` mediumblob,
  PRIMARY KEY (`OBJECT_TYPE`, `MONTH`)
);