CREATE PROCEDURE generateNewId(IN typeName VARCHAR(256))
    MODIFIES SQL DATA
    SQL SECURITY INVOKER
BEGIN
	DECLARE newId BIGINT;
    DECLARE typeLock VARCHAR(256);
	
	SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
  
	START TRANSACTION;
	/* Lock on the type to ensure consistency.*/
	SELECT TYPE_LOCK INTO typeLock FROM ID_GENERATOR_SEMAPHORE WHERE TYPE_LOCK = typeName FOR UPDATE;

	SET @sql_text:=CONCAT('INSERT INTO ',typeName,' (CREATED_ON) VALUES (NOW())');
	PREPARE stmt from @sql_text;
	EXECUTE stmt; 
    DEALLOCATE PREPARE stmt;
	
	SELECT LAST_INSERT_ID() INTO newId;
	
	COMMIT;
	SELECT newId AS NEW_ID;
END