CREATE TABLE IF NOT EXISTS `QUARANTINED_EMAILS` (
  `EMAIL` VARCHAR(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `UPDATED_ON` TIMESTAMP(3) NOT NULL,
  `REASON` ENUM('HARD_BOUNCE', 'TOO_MANY_BOUNCES', 'COMPLAINT', 'OTHER') NOT NULL,
  `SES_MESSAGE_ID` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`EMAIL`),
  INDEX `QUARANTINED_EMAILS_SES_MESSAGE_ID_INDEX` (`SES_MESSAGE_ID`)
)
