CREATE TABLE IF NOT EXISTS `SES_NOTIFICATIONS` (
  `ID` bigint(20) NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `SES_MESSAGE_ID` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `SES_FEEDBACK_ID` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `NOTIFICATION_TYPE` ENUM('Bounce', 'Complaint', 'Delivery', 'Unknown') NOT NULL,
  `NOTIFICATION_BODY` MEDIUMBLOB,
  PRIMARY KEY (`ID`),
  UNIQUE (`SES_MESSAGE_ID`)
)
