WITH RECURSIVE D AS
(
  SELECT *, 0 AS DEPTH FROM GRID_REPLICA_RGA WHERE
  	SESSION_ID = :sessionId
	AND REPLICA_ID = :replicaId
	AND CTR_REP = :ctrRep
	AND CTR_SEQ = :ctrSeq
	AND REF_REP = :ctrRep
	AND REF_SEQ = :ctrSeq
  UNION ALL
  SELECT D1.*, D.DEPTH + 1 AS DEPTH FROM D INNER JOIN GRID_REPLICA_RGA D1 ON (
	D.SESSION_ID = D1.SESSION_ID
	AND D.REPLICA_ID = D1.REPLICA_ID
	AND D.CTR_REP = D1.CTR_REP
	AND D.CTR_SEQ = D1.CTR_SEQ
	AND D.NODE_REP = D1.REF_REP
	AND D.NODE_SEQ = D1.REF_SEQ
	)
)
SELECT * FROM D
%s
ORDER BY DEPTH %s LIMIT :limit OFFSET :offset;
