WITH RECURSIVE D AS
(
  SELECT *, 0 AS DEPTH FROM GRID_REPLICA_ARR WHERE 
  	SESSION_ID = :sessionId 
	AND REPLICA_ID = :replicaId
	AND ARR_REP = :arrRep 
	AND ARR_SEQ = :arrSeq
	AND REF_REP = :arrRep
	AND REF_SEQ = :arrSeq
  UNION ALL 
  SELECT D1.*, D.DEPTH + 1 AS DEPTH FROM D INNER JOIN GRID_REPLICA_ARR D1 ON (
	D.SESSION_ID = D1.SESSION_ID
	AND D.REPLICA_ID = D1.REPLICA_ID
	AND D.ARR_REP = D1.ARR_REP
	AND D.ARR_SEQ = D1.ARR_SEQ
	AND D.NODE_REP = D1.REF_REP
	AND D.NODE_SEQ = D1.REF_SEQ
	)
)
SELECT * FROM D ORDER BY DEPTH ASC LIMIT :limit OFFSET :offset;