#!/usr/bin/env bash

if [ ! -d "${SYNAPSE_HOME}" ]; then
    echo
    echo " *ERROR* You must specify a SYNAPSE_HOME variable with the path to the tools"
    echo
fi

LIBDIR="${SYNAPSE_HOME}/lib"

JAVA_HOME=${JAVA_HOME:?JAVA_HOME is not set}
CP="${CLASSPATH}"

case "`uname`" in
	CYGWIN*) cygwin=true;;
esac 

cygprop=""

if [ "${cygwin}" == "true" ] ; then
	cygprop="-Dcs.cygwin=true"

	if [ -n "${SYNAPSE_HOME}" ]
	then
		if echo "${SYNAPSE_HOME}" | egrep -q '[[:alpha:]]:\\'
		then
			echo
			echo " *INFO* Your SYNAPSE_HOME variable needs to specified as a Unix path under Cygwin"
			echo
		fi
	fi

	for jar in "${LIBDIR}"/*.jar ; do
		cygjar=$(cygpath -w -a "${jar}")
		CP="${CP};${cygjar}"
	done
else 
	for jar in "${LIBDIR}"/*.jar ; do
		CP="${CP}:${jar}"
	done
fi

TOOL=$1
shift
"${JAVA_HOME}/bin/java" ${SYNAPSE_JVM_ARGS} ${cygprop} -classpath "${CP}" "org.sagebionetworks.cli.${TOOL}" $SYNAPSE_DEFAULT_ARGS "$@"
