#!/usr/bin/env bash

if [ -z "${SYNAPSE_HOME}" ]; then
    echo
    echo " *ERROR* SYNAPSE_HOME is not set, please set it to the directory that contains the synapse tools."
    echo "export SYNAPSE_HOME=<your install dir>"
    echo
    exit 1
fi
if [ ! -f "${SYNAPSE_HOME}/bin/synapse-cmd" ]; then
    echo
    echo " *ERROR* SYNAPSE_HOME is set to "\"$SYNAPSE_HOME\"", should be set to a valid cloud search tool path. Looking for synapse-cmd, but didn't find it there." 
    echo
    exit 1
fi
"${SYNAPSE_HOME}"/bin/synapse-cmd UploadFile "$@"
