CREATE TABLE IF NOT EXISTS `TERMS_OF_SERVICE_AGREEMENT` (
  `ID` BIGINT NOT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `VERSION` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `TOS_AGREEMENT_ID_VERSION` (`CREATED_BY`, `VERSION`),
  CONSTRAINT `TOS_AGREEMENT_CREATED_BY_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE CASCADE
)