CREATE TABLE IF NOT EXISTS `WEBHOOK` (
  `ID` BIGINT NOT NULL,
  `ETAG` CHAR(36) NOT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `MODIFIED_ON` TIMESTAMP(3) NOT NULL,
  `OBJECT_ID` BIGINT NOT NULL,
  `OBJECT_TYPE` ENUM('ENTITY') NOT NULL,
  `EVENT_TYPES` JSON NOT NULL,
  `INVOKE_ENDPOINT` VARCHAR(256) NOT NULL,
  `IS_ENABLED` BOOLEAN NOT NULL,
  `VERIFICATION_STATUS` ENUM('VERIFIED', 'PENDING', 'REVOKED', 'FAILED') NOT NULL,
  `VERIFICATION_MSG` VARCHAR(256) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `INDEX_CREATED_BY` (`CREATED_BY`),
  UNIQUE INDEX `OBJECT_ID_OBJECT_TYPE_INVOKE_ENDPOINT` (`OBJECT_ID`, `OBJECT_TYPE`, `INVOKE_ENDPOINT`),
  CONSTRAINT `WEBHOOK_ID_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE CASCADE
)
