CREATE TABLE IF NOT EXISTS `WEBHOOK_VERIFICATION` (
  `WEBHOOK_ID` BIGINT NOT NULL,
  `ETAG` CHAR(36) NOT NULL,
  `MODIFIED_ON` TIMESTAMP(3) NOT NULL,
  `CODE` CHAR(6) DEFAULT NULL,
  `CODE_EXPIRES_ON` TIMESTAMP(3) DEFAULT NULL,
  `CODE_MESSAGE_ID` VARCHAR(36) DEFAULT NULL,
  `STATUS` ENUM('PENDING', 'CODE_SENT', 'VERIFIED', 'FAILED', 'REVOKED') NOT NULL,
  `MESSAGE` VARCHAR(256) DEFAULT NULL,
  PRIMARY KEY (`WEBHOOK_ID`),
  CONSTRAINT `WEBHOOK_VERIFICATION_ID_FK` FOREIGN KEY (`WEBHOOK_ID`) REFERENCES `WEBHOOK` (`ID`) ON DELETE CASCADE
)