package org.sagebionetworks.web.client.ontology;

import java.util.HashMap;
import java.util.Map;

import org.sagebionetworks.web.client.DisplayConstants;

public class StaticEnumerations {

	/**
	 * This is a temporary solution until we have an ontology service, as well
	 * as a mapping from annotation key to ontologies.
	 */
	private final Map<String, Enumeration> annotationToOntology;

	public StaticEnumerations() {
		annotationToOntology = new HashMap<String, Enumeration>();
		annotationToOntology.put(StaticEnumerations.STATUS.getDisplayName(),
				StaticEnumerations.STATUS);
		annotationToOntology.put(StaticEnumerations.LAYER_TYPES.getDisplayName(),
				StaticEnumerations.LAYER_TYPES);
		annotationToOntology.put(StaticEnumerations.LAYER_TYPE.getDisplayName(),
				StaticEnumerations.LAYER_TYPE);
		annotationToOntology.put(StaticEnumerations.VENDOR.getDisplayName(),
				StaticEnumerations.VENDOR);
		annotationToOntology.put(StaticEnumerations.PLATFORM.getDisplayName(),
				StaticEnumerations.PLATFORM);
	}

	public Map<String, Enumeration> getAnnotationToEnum() {
		return annotationToOntology;
	}

	public static final Enumeration STATUS = new Enumeration(
			DisplayConstants.SERVICE_STATUS_KEY, new EnumerationTerm[] {
					new EnumerationTerm("Active", "Active"),
					new EnumerationTerm("Complete", "Complete") });

	public static final Enumeration LAYER_TYPES = new Enumeration(
			DisplayConstants.SERVICE_LAYER_TYPE_KEY, new EnumerationTerm[] {
					new EnumerationTerm("Genetic Sequence Data", "G"),
					new EnumerationTerm("Clinical / Phenotypic", "C"),
					new EnumerationTerm("Molecular Expression Data", "E"),
					new EnumerationTerm("Media", "M")});

	public static final Enumeration LAYER_TYPE = new Enumeration("Layer Type",
			new EnumerationTerm[] { new EnumerationTerm("Expression", "Expression"),
					new EnumerationTerm("Genotype", "Genotype"),
					new EnumerationTerm("miRNA", "miRNA"),
					new EnumerationTerm("CNV", "CNV"),
					new EnumerationTerm("Phenotype", "Phenotype"),
					new EnumerationTerm("Image", "Image"),
					new EnumerationTerm("Analysis Result", "Analysis Result") });

	public static final Enumeration VENDOR = new Enumeration("Vendor",
			new EnumerationTerm[] { new EnumerationTerm("Expression", "Expression"),
					new EnumerationTerm("Affymetrix", "Affymetrix"),
					new EnumerationTerm("Agilent", "Agilent"),
					new EnumerationTerm("Illumina", "Illumina"),
					new EnumerationTerm("Nimblegen", "Nimblegen"),
					new EnumerationTerm("Custom", "Custom") });

	public static final Enumeration PLATFORM = new Enumeration("platform",
			new EnumerationTerm[] {			
			new EnumerationTerm("ABI Human Genome Survey Microarray Version 2", "ABI Human Genome Survey Microarray Version 2"),
			new EnumerationTerm("ABI Mouse Genome Survey Microarray", "ABI Mouse Genome Survey Microarray"),
			new EnumerationTerm("Affymetrix Arabidopsis ATH1 Genome Array", "Affymetrix Arabidopsis ATH1 Genome Array"),
			new EnumerationTerm("Affymetrix Arabidopsis Tiling 1.0R Array", "Affymetrix Arabidopsis Tiling 1.0R Array"),
			new EnumerationTerm("Affymetrix Barley Genome Array", "Affymetrix Barley Genome Array"),
			new EnumerationTerm("Affymetrix Bovine Genome Array", "Affymetrix Bovine Genome Array"),
			new EnumerationTerm("Affymetrix C. elegans Genome Array", "Affymetrix C. elegans Genome Array"),
			new EnumerationTerm("Affymetrix C. elegans Tiling 1.0R Array", "Affymetrix C. elegans Tiling 1.0R Array"),
			new EnumerationTerm("Affymetrix Canine Genome 1.0 Array", "Affymetrix Canine Genome 1.0 Array"),
			new EnumerationTerm("Affymetrix Canine Genome 2.0 Array", "Affymetrix Canine Genome 2.0 Array"),
			new EnumerationTerm("Affymetrix Chicken Genome Array", "Affymetrix Chicken Genome Array"),
			new EnumerationTerm("Affymetrix Chinese Hamster Ovary (CHO)-specific custom array", "Affymetrix Chinese Hamster Ovary (CHO)-specific custom array"),
			new EnumerationTerm("Affymetrix custom Bradyrhizobium japonicum strain USDA 110 19K array", "Affymetrix custom Bradyrhizobium japonicum strain USDA 110 19K array"),
			new EnumerationTerm("Affymetrix Drosophila Genome 2.0 Array", "Affymetrix Drosophila Genome 2.0 Array"),
			new EnumerationTerm("Affymetrix Drosophila Genome Array", "Affymetrix Drosophila Genome Array"),
			new EnumerationTerm("Affymetrix Drosophila Tiling 2.0R Array", "Affymetrix Drosophila Tiling 2.0R Array"),
			new EnumerationTerm("Affymetrix E. coli Antisense Genome Array", "Affymetrix E. coli Antisense Genome Array"),
			new EnumerationTerm("Affymetrix E. coli Genome 2.0 Array", "Affymetrix E. coli Genome 2.0 Array"),
			new EnumerationTerm("Affymetrix GeneChip Early Access Mapping 500K Set Array (250K_Nsp_SNP)", "Affymetrix GeneChip Early Access Mapping 500K Set Array (250K_Nsp_SNP)"),
			new EnumerationTerm("Affymetrix GeneChip HT-HG_U133A Early Access Array", "Affymetrix GeneChip HT-HG_U133A Early Access Array"),
			new EnumerationTerm("Affymetrix GeneChip Human Genome HG-U133 Plus 2 Array [Brainarray Version 12]", "Affymetrix GeneChip Human Genome HG-U133 Plus 2 Array [Brainarray Version 12]"),
			new EnumerationTerm("Affymetrix GeneChip Human Genome U133 Array Set HG-U133A [CDF: Hs133A_Hs_UG_3]", "Affymetrix GeneChip Human Genome U133 Array Set HG-U133A [CDF: Hs133A_Hs_UG_3]"),
			new EnumerationTerm("Affymetrix GeneChip Human Genome U133 Plus 2.0 Array (MBNI v11 Entrez Gene ID CDF)", "Affymetrix GeneChip Human Genome U133 Plus 2.0 Array (MBNI v11 Entrez Gene ID CDF)"),
			new EnumerationTerm("Affymetrix GeneChip Human Genome U133 Plus 2.0 Array [CDF: Hs133P_Hs_ENTREZG.cdf]", "Affymetrix GeneChip Human Genome U133 Plus 2.0 Array [CDF: Hs133P_Hs_ENTREZG.cdf]"),
			new EnumerationTerm("Affymetrix GeneChip Human Genome U133A 2.0 Array [CDF: Brainarray Version 10, Hs133Av2_Hs_ENTREZG]", "Affymetrix GeneChip Human Genome U133A 2.0 Array [CDF: Brainarray Version 10, Hs133Av2_Hs_ENTREZG]"),
			new EnumerationTerm("Affymetrix GeneChip Mapping 500K Early Access Array (250K_Sty_SNP)", "Affymetrix GeneChip Mapping 500K Early Access Array (250K_Sty_SNP)"),
			new EnumerationTerm("Affymetrix GeneChip S. cerevisiae Tiling 1.0R Array", "Affymetrix GeneChip S. cerevisiae Tiling 1.0R Array"),
			new EnumerationTerm("Affymetrix GeneChip Universal 70K Tag Array", "Affymetrix GeneChip Universal 70K Tag Array"),
			new EnumerationTerm("Affymetrix Genome-Wide Human SNP 5.0 Array", "Affymetrix Genome-Wide Human SNP 5.0 Array"),
			new EnumerationTerm("Affymetrix Genome-Wide Human SNP 6.0 Array", "Affymetrix Genome-Wide Human SNP 6.0 Array"),
			new EnumerationTerm("Affymetrix Glyco v3 GeneChip", "Affymetrix Glyco v3 GeneChip"),
			new EnumerationTerm("Affymetrix HT HG-U133+ PM Array Plate", "Affymetrix HT HG-U133+ PM Array Plate"),
			new EnumerationTerm("Affymetrix HT Human Genome U133A Array", "Affymetrix HT Human Genome U133A Array"),
			new EnumerationTerm("Affymetrix HT Mouse Genome 430A Array", "Affymetrix HT Mouse Genome 430A Array"),
			new EnumerationTerm("Affymetrix Human CentHindAv2 SNP Array", "Affymetrix Human CentHindAv2 SNP Array"),
			new EnumerationTerm("Affymetrix Human CentXbaAv2 SNP Array", "Affymetrix Human CentXbaAv2 SNP Array"),
			new EnumerationTerm("AFFYMETRIX Human Chromosomes 21 & 22 v2.0", "AFFYMETRIX Human Chromosomes 21 & 22 v2.0"),
			new EnumerationTerm("Affymetrix Human Exon 1.0 ST Array [CDF: HuEx_1_0_st_v2_main_A20071112_EP.cdf]", "Affymetrix Human Exon 1.0 ST Array [CDF: HuEx_1_0_st_v2_main_A20071112_EP.cdf]"),
			new EnumerationTerm("Affymetrix Human Exon 1.0 ST Array [HuEx-1_0-st-v2,coreR3,A20071112,EP.cdf]", "Affymetrix Human Exon 1.0 ST Array [HuEx-1_0-st-v2,coreR3,A20071112,EP.cdf]"),
			new EnumerationTerm("Affymetrix Human Exon 1.0 ST Array [probe set (exon) version]", "Affymetrix Human Exon 1.0 ST Array [probe set (exon) version]"),
			new EnumerationTerm("Affymetrix Human Exon 1.0 ST Array [transcript (gene) version]", "Affymetrix Human Exon 1.0 ST Array [transcript (gene) version]"),
			new EnumerationTerm("Affymetrix Human Full Length HuGeneFL Array", "Affymetrix Human Full Length HuGeneFL Array"),
			new EnumerationTerm("Affymetrix Human Gene 1.0 ST Array [transcript (gene) version]", "Affymetrix Human Gene 1.0 ST Array [transcript (gene) version]"),
			new EnumerationTerm("Affymetrix Human Genome U133 Plus 2.0 Array [MBNI v12 Entrez Gene ID CDF]", "Affymetrix Human Genome U133 Plus 2.0 Array [MBNI v12 Entrez Gene ID CDF]"),
			new EnumerationTerm("Affymetrix Human Genome U133 Plus 2.0 Array", "Affymetrix Human Genome U133 Plus 2.0 Array"),
			new EnumerationTerm("Affymetrix Human Genome U133A 2.0 Array", "Affymetrix Human Genome U133A 2.0 Array"),
			new EnumerationTerm("Affymetrix Human Genome U133A Array", "Affymetrix Human Genome U133A Array"),
			new EnumerationTerm("Affymetrix Human Genome U133B Array", "Affymetrix Human Genome U133B Array"),
			new EnumerationTerm("Affymetrix Human Genome U95 Version 2 Array", "Affymetrix Human Genome U95 Version 2 Array"),
			new EnumerationTerm("Affymetrix Human Genome U95A Array", "Affymetrix Human Genome U95A Array"),
			new EnumerationTerm("Affymetrix Human Genome U95B Array", "Affymetrix Human Genome U95B Array"),
			new EnumerationTerm("Affymetrix Human Genome U95C Array", "Affymetrix Human Genome U95C Array"),
			new EnumerationTerm("Affymetrix Human Genome U95D Array", "Affymetrix Human Genome U95D Array"),
			new EnumerationTerm("Affymetrix Human Genome U95E Array", "Affymetrix Human Genome U95E Array"),
			new EnumerationTerm("Affymetrix Human HG-Focus Target Array", "Affymetrix Human HG-Focus Target Array"),
			new EnumerationTerm("Affymetrix human INDEL genotyping array", "Affymetrix human INDEL genotyping array"),
			new EnumerationTerm("Affymetrix Human Mapping 10K 2.0 Array", "Affymetrix Human Mapping 10K 2.0 Array"),
			new EnumerationTerm("Affymetrix Human Mapping 10K SNP Array", "Affymetrix Human Mapping 10K SNP Array"),
			new EnumerationTerm("Affymetrix Human Mapping 50K Hind240 SNP Array", "Affymetrix Human Mapping 50K Hind240 SNP Array"),
			new EnumerationTerm("Affymetrix Human Mapping 50K Xba240 SNP Array", "Affymetrix Human Mapping 50K Xba240 SNP Array"),
			new EnumerationTerm("Affymetrix human mitochondrial array [CDF: FATMITO1a520158F]", "Affymetrix human mitochondrial array [CDF: FATMITO1a520158F]"),
			new EnumerationTerm("Affymetrix Human Promoter 1.0R Array", "Affymetrix Human Promoter 1.0R Array"),
			new EnumerationTerm("Affymetrix Human Tiling 2.0R Set, Array 1", "Affymetrix Human Tiling 2.0R Set, Array 1"),
			new EnumerationTerm("Affymetrix Human Tiling 2.0R Set, Array 2", "Affymetrix Human Tiling 2.0R Set, Array 2"),
			new EnumerationTerm("Affymetrix Human Tiling 2.0R Set, Array 3", "Affymetrix Human Tiling 2.0R Set, Array 3"),
			new EnumerationTerm("Affymetrix Human Tiling 2.0R Set, Array 4", "Affymetrix Human Tiling 2.0R Set, Array 4"),
			new EnumerationTerm("Affymetrix Human Tiling 2.0R Set, Array 5", "Affymetrix Human Tiling 2.0R Set, Array 5"),
			new EnumerationTerm("Affymetrix Human Tiling 2.0R Set, Array 6", "Affymetrix Human Tiling 2.0R Set, Array 6"),
			new EnumerationTerm("Affymetrix Human Tiling 2.0R Set, Array 7", "Affymetrix Human Tiling 2.0R Set, Array 7"),
			new EnumerationTerm("Affymetrix Human X3P Array", "Affymetrix Human X3P Array"),
			new EnumerationTerm("Affymetrix Maize Genome Array", "Affymetrix Maize Genome Array"),
			new EnumerationTerm("Affymetrix Mapping 250K Nsp SNP Array", "Affymetrix Mapping 250K Nsp SNP Array"),
			new EnumerationTerm("Affymetrix Mapping 250K Sty2 SNP Array", "Affymetrix Mapping 250K Sty2 SNP Array"),
			new EnumerationTerm("Affymetrix Medicago Genome Array", "Affymetrix Medicago Genome Array"),
			new EnumerationTerm("Affymetrix Mouse Exon 1.0 ST Array [probe set (exon) version]", "Affymetrix Mouse Exon 1.0 ST Array [probe set (exon) version]"),
			new EnumerationTerm("Affymetrix Mouse Exon 1.0 ST Array [transcript (gene) version]", "Affymetrix Mouse Exon 1.0 ST Array [transcript (gene) version]"),
			new EnumerationTerm("Affymetrix Mouse Expression 430A Array", "Affymetrix Mouse Expression 430A Array"),
			new EnumerationTerm("Affymetrix Mouse Expression 430B Array", "Affymetrix Mouse Expression 430B Array"),
			new EnumerationTerm("Affymetrix Mouse Gene 1.0 ST Array [CDF: MoGene10stv1_Mm_ENSG]", "Affymetrix Mouse Gene 1.0 ST Array [CDF: MoGene10stv1_Mm_ENSG]"),
			new EnumerationTerm("Affymetrix Mouse Gene 1.0 ST Array [CDF: MoGene10stv1_Mm_ENST]", "Affymetrix Mouse Gene 1.0 ST Array [CDF: MoGene10stv1_Mm_ENST]"),
			new EnumerationTerm("Affymetrix Mouse Gene 1.0 ST Array [transcript (gene) version]", "Affymetrix Mouse Gene 1.0 ST Array [transcript (gene) version]"),
			new EnumerationTerm("Affymetrix Mouse Genome 430 2.0 Array", "Affymetrix Mouse Genome 430 2.0 Array"),
			new EnumerationTerm("Affymetrix Mouse Genome 430A 2.0 Array", "Affymetrix Mouse Genome 430A 2.0 Array"),
			new EnumerationTerm("Affymetrix Murine 11K SubA Array", "Affymetrix Murine 11K SubA Array"),
			new EnumerationTerm("Affymetrix Murine 11K SubB Array", "Affymetrix Murine 11K SubB Array"),
			new EnumerationTerm("Affymetrix Murine Genome U74 Version 2 Array", "Affymetrix Murine Genome U74 Version 2 Array"),
			new EnumerationTerm("Affymetrix Murine Genome U74 Version 2 Array", "Affymetrix Murine Genome U74 Version 2 Array"),
			new EnumerationTerm("Affymetrix Murine Genome U74 Version 2 Array", "Affymetrix Murine Genome U74 Version 2 Array"),
			new EnumerationTerm("Affymetrix Murine Genome U74A Array", "Affymetrix Murine Genome U74A Array"),
			new EnumerationTerm("Affymetrix Plasmodium/Anopheles Genome Array", "Affymetrix Plasmodium/Anopheles Genome Array"),
			new EnumerationTerm("Affymetrix Poplar Genome Array", "Affymetrix Poplar Genome Array"),
			new EnumerationTerm("Affymetrix Porcine Genome Array", "Affymetrix Porcine Genome Array"),
			new EnumerationTerm("Affymetrix Pseudomonas aeruginosa Array", "Affymetrix Pseudomonas aeruginosa Array"),
			new EnumerationTerm("Affymetrix Rat Exon 1.0 ST Array [probe set (exon) version]", "Affymetrix Rat Exon 1.0 ST Array [probe set (exon) version]"),
			new EnumerationTerm("Affymetrix Rat Expression 230A Array", "Affymetrix Rat Expression 230A Array"),
			new EnumerationTerm("Affymetrix Rat Gene 1.0 ST Array [transcript (gene) version]", "Affymetrix Rat Gene 1.0 ST Array [transcript (gene) version]"),
			new EnumerationTerm("Affymetrix Rat Genome 230 2.0 Array", "Affymetrix Rat Genome 230 2.0 Array"),
			new EnumerationTerm("Affymetrix Rat Genome U34 Array", "Affymetrix Rat Genome U34 Array"),
			new EnumerationTerm("Affymetrix Rat Genome U34 Array", "Affymetrix Rat Genome U34 Array"),
			new EnumerationTerm("Affymetrix Rat Genome U34 Array", "Affymetrix Rat Genome U34 Array"),
			new EnumerationTerm("Affymetrix Rat Neurobiology U34 Array", "Affymetrix Rat Neurobiology U34 Array"),
			new EnumerationTerm("Affymetrix Rhesus Macaque Genome Array", "Affymetrix Rhesus Macaque Genome Array"),
			new EnumerationTerm("Affymetrix Rice Genome Array", "Affymetrix Rice Genome Array"),
			new EnumerationTerm("Affymetrix RML Custom Pathogenic chip 1", "Affymetrix RML Custom Pathogenic chip 1"),
			new EnumerationTerm("Affymetrix RML Custom Pathogenic chip 3", "Affymetrix RML Custom Pathogenic chip 3"),
			new EnumerationTerm("Affymetrix S. aureus Genome Array", "Affymetrix S. aureus Genome Array"),
			new EnumerationTerm("Affymetrix Soybean Genome Array", "Affymetrix Soybean Genome Array"),
			new EnumerationTerm("Affymetrix Tomato Genome Array", "Affymetrix Tomato Genome Array"),
			new EnumerationTerm("Affymetrix Toxoplasma gondii Custom GeneChip (CDF: ToxoDB version 4)", "Affymetrix Toxoplasma gondii Custom GeneChip (CDF: ToxoDB version 4)"),
			new EnumerationTerm("Affymetrix Vitis vinifera (Grape) Genome Array", "Affymetrix Vitis vinifera (Grape) Genome Array"),
			new EnumerationTerm("Affymetrix Wheat Genome Array", "Affymetrix Wheat Genome Array"),
			new EnumerationTerm("Affymetrix Xenopus laevis Genome Array", "Affymetrix Xenopus laevis Genome Array"),
			new EnumerationTerm("Affymetrix Yeast Genome 2.0 Array", "Affymetrix Yeast Genome 2.0 Array"),
			new EnumerationTerm("Affymetrix Yeast Genome S98 Array", "Affymetrix Yeast Genome S98 Array"),
			new EnumerationTerm("Affymetrix Zebrafish Genome Array", "Affymetrix Zebrafish Genome Array"),
			new EnumerationTerm("AGENAE_PigGeneric2_9216", "AGENAE_PigGeneric2_9216"),
			new EnumerationTerm("AGENAE_TroutGeneric2_9216", "AGENAE_TroutGeneric2_9216"),
			new EnumerationTerm("Agendia_DiscoverPrint_v2", "Agendia_DiscoverPrint_v2"),
			new EnumerationTerm("Agilent Custom Brassica 60-mer two-color microarray", "Agilent Custom Brassica 60-mer two-color microarray"),
			new EnumerationTerm("Agilent custom-designed CpG island 60mer microarray 8x15k", "Agilent custom-designed CpG island 60mer microarray 8x15k"),
			new EnumerationTerm("Agilent Eichler Human CNP 180K v2.1", "Agilent Eichler Human CNP 180K v2.1"),
			new EnumerationTerm("Agilent Eichler Human CNP 180K v3.0", "Agilent Eichler Human CNP 180K v3.0"),
			new EnumerationTerm("Agilent Homo sapiens 21.6K custom array", "Agilent Homo sapiens 21.6K custom array"),
			new EnumerationTerm("Agilent Human 1 cDNA Microarray (G4100A) [layout C]", "Agilent Human 1 cDNA Microarray (G4100A) [layout C]"),
			new EnumerationTerm("Agilent Human 1A Oligo UNC custom Microarrays", "Agilent Human 1A Oligo UNC custom Microarrays"),
			new EnumerationTerm("Agilent RISET 2.0 8x15K 60mer oligonucleotide microarray", "Agilent RISET 2.0 8x15K 60mer oligonucleotide microarray"),
			new EnumerationTerm("Agilent UNC Perou Lab Homo sapiens 1X44K Custom Array", "Agilent UNC Perou Lab Homo sapiens 1X44K Custom Array"),
			new EnumerationTerm("Agilent-011447 Yeast Oligo Microarray G4140A (Feature Number version)", "Agilent-011447 Yeast Oligo Microarray G4140A (Feature Number version)"),
			new EnumerationTerm("Agilent-011521 Human 1A Microarray G4110A (Feature Number version)", "Agilent-011521 Human 1A Microarray G4110A (Feature Number version)"),
			new EnumerationTerm("Agilent-011868 Rat Oligo Microarray G4130A (Feature Number version)", "Agilent-011868 Rat Oligo Microarray G4130A (Feature Number version)"),
			new EnumerationTerm("Agilent-011868_D_WithSGCtrls_20030627 Rat Oligo Microarray", "Agilent-011868_D_WithSGCtrls_20030627 Rat Oligo Microarray"),
			new EnumerationTerm("Agilent-011978 Mouse Microarray G4121A (Feature Number version)", "Agilent-011978 Mouse Microarray G4121A (Feature Number version)"),
			new EnumerationTerm("Agilent-011978 Mouse Microarray G4121A (Probe Name version)", "Agilent-011978 Mouse Microarray G4121A (Probe Name version)"),
			new EnumerationTerm("Agilent-012097 Human 1A Microarray (V2) G4110B (Feature Number version)", "Agilent-012097 Human 1A Microarray (V2) G4110B (Feature Number version)"),
			new EnumerationTerm("Agilent-012097 Human 1A Microarray (V2) G4110B (Probe Name version)", "Agilent-012097 Human 1A Microarray (V2) G4110B (Probe Name version)"),
			new EnumerationTerm("Agilent-012106 Rice Oligo Microarray G4138A (Feature Number version)", "Agilent-012106 Rice Oligo Microarray G4138A (Feature Number version)"),
			new EnumerationTerm("Agilent-012391 Whole Human Genome Oligo Microarray G4112A (Feature Number version)", "Agilent-012391 Whole Human Genome Oligo Microarray G4112A (Feature Number version)"),
			new EnumerationTerm("Agilent-012391 Whole Human Genome Oligo Microarray G4112A (Probe Name version)", "Agilent-012391 Whole Human Genome Oligo Microarray G4112A (Probe Name version)"),
			new EnumerationTerm("Agilent-012694 Whole Mouse Genome G4122A (Feature Number version)", "Agilent-012694 Whole Mouse Genome G4122A (Feature Number version)"),
			new EnumerationTerm("Agilent-013162 Whole Rat Genome Microarray G4131A (Feature Number version)", "Agilent-013162 Whole Rat Genome Microarray G4131A (Feature Number version)"),
			new EnumerationTerm("Agilent-013282 Human Genome CGH Microarray 44B (Feature number version)", "Agilent-013282 Human Genome CGH Microarray 44B (Feature number version)"),
			new EnumerationTerm("Agilent-013326 Mouse Oligo Microarray (V2) G4121B (Feature Number version)", "Agilent-013326 Mouse Oligo Microarray (V2) G4121B (Feature Number version)"),
			new EnumerationTerm("Agilent-013384 Yeast Oligo Microarray (V2) G4140B (Feature Number version)", "Agilent-013384 Yeast Oligo Microarray (V2) G4140B (Feature Number version)"),
			new EnumerationTerm("Agilent-014693 Human Genome CGH Microarray 244A (Feature number version)", "Agilent-014693 Human Genome CGH Microarray 244A (Feature number version)"),
			new EnumerationTerm("Agilent-014693 Human Genome CGH Microarray 244A (Probe name version)", "Agilent-014693 Human Genome CGH Microarray 244A (Probe name version)"),
			new EnumerationTerm("Agilent-014695 Mouse Genome CGH Microarray 244A (G4415A)", "Agilent-014695 Mouse Genome CGH Microarray 244A (G4415A)"),
			new EnumerationTerm("Agilent-014698 Human Genome CGH Microarray 105A (G4412A)", "Agilent-014698 Human Genome CGH Microarray 105A (G4412A)"),
			new EnumerationTerm("Agilent-014810 Yeast Whole Genome ChIP-on-Chip Microarray 4x44K (G4493A)", "Agilent-014810 Yeast Whole Genome ChIP-on-Chip Microarray 4x44K (G4493A)"),
			new EnumerationTerm("Agilent-014850 Whole Human Genome Microarray 4x44K G4112F (Feature Number version)", "Agilent-014850 Whole Human Genome Microarray 4x44K G4112F (Feature Number version)"),
			new EnumerationTerm("Agilent-014850 Whole Human Genome Microarray 4x44K G4112F (Probe Name version)", "Agilent-014850 Whole Human Genome Microarray 4x44K G4112F (Probe Name version)"),
			new EnumerationTerm("Agilent-014868 Whole Mouse Genome Microarray 4x44K G4122F (Feature Number version)", "Agilent-014868 Whole Mouse Genome Microarray 4x44K G4122F (Feature Number version)"),
			new EnumerationTerm("Agilent-014868 Whole Mouse Genome Microarray 4x44K G4122F (Probe Name version)", "Agilent-014868 Whole Mouse Genome Microarray 4x44K G4122F (Probe Name version)"),
			new EnumerationTerm("Agilent-014879 Whole Rat Genome Microarray 4x44K G4131F (Feature Number version)", "Agilent-014879 Whole Rat Genome Microarray 4x44K G4131F (Feature Number version)"),
			new EnumerationTerm("Agilent-014879 Whole Rat Genome Microarray 4x44K G4131F (Probe Name version)", "Agilent-014879 Whole Rat Genome Microarray 4x44K G4131F (Probe Name version)"),
			new EnumerationTerm("Agilent-015061 C. elegans Oligo Microarray 4x44K G2519F", "Agilent-015061 C. elegans Oligo Microarray 4x44K G2519F"),
			new EnumerationTerm("Agilent-015241 Rice Gene Expression 4x44K Microarray (Feature Number version)", "Agilent-015241 Rice Gene Expression 4x44K Microarray (Feature Number version)"),
			new EnumerationTerm("Agilent-016436 Human miRNA Microarray 1.0 (Feature Number version)", "Agilent-016436 Human miRNA Microarray 1.0 (Feature Number version)"),
			new EnumerationTerm("Agilent-016436 Human miRNA Microarray 1.0 G4472A (miRNA ID version)", "Agilent-016436 Human miRNA Microarray 1.0 G4472A (miRNA ID version)"),
			new EnumerationTerm("Agilent-019118 Human miRNA Microarray 2.0 G4470B (Feature Number version)", "Agilent-019118 Human miRNA Microarray 2.0 G4470B (Feature Number version)"),
			new EnumerationTerm("Agilent-019118 Human miRNA Microarray 2.0 G4470B (miRNA ID version)", "Agilent-019118 Human miRNA Microarray 2.0 G4470B (miRNA ID version)"),
			new EnumerationTerm("Agilent-019161 D. rerio (Zebrafish) Oligo Microarray (V2) G2519F (Feature Number version)", "Agilent-019161 D. rerio (Zebrafish) Oligo Microarray (V2) G2519F (Feature Number version)"),
			new EnumerationTerm("Agilent-019182 Drosophila melanogaster Whole Genome ChIP-on-Chip Set 244K, Microarray 1 of 3", "Agilent-019182 Drosophila melanogaster Whole Genome ChIP-on-Chip Set 244K, Microarray 1 of 3"),
			new EnumerationTerm("Agilent-019183 Drosophila melanogaster Whole Genome ChIP-on-Chip Set 244K, Microarray 2 of 3", "Agilent-019183 Drosophila melanogaster Whole Genome ChIP-on-Chip Set 244K, Microarray 2 of 3"),
			new EnumerationTerm("Agilent-019184 Drosophila melanogaster Whole Genome ChIP-on-Chip Set 244K, Microarray 3 of 3", "Agilent-019184 Drosophila melanogaster Whole Genome ChIP-on-Chip Set 244K, Microarray 3 of 3"),
			new EnumerationTerm("Agilent-021219 New15K60mer-EfetidaArray", "Agilent-021219 New15K60mer-EfetidaArray"),
			new EnumerationTerm("Agilent-022589 Clostridium_botulinum_species_cgh_array 022588", "Agilent-022589 Clostridium_botulinum_species_cgh_array 022588"),
			new EnumerationTerm("Agilent-022689 Custom BCM-Beaudet Human 1M Exon Autism Array", "Agilent-022689 Custom BCM-Beaudet Human 1M Exon Autism Array"),
			new EnumerationTerm("Agilent-023456 Custom BCM-Beaudet Human 180K V8cleaned aCGH Array", "Agilent-023456 Custom BCM-Beaudet Human 180K V8cleaned aCGH Array"),
			new EnumerationTerm("Agilent-024154 human hg18 45K array", "Agilent-024154 human hg18 45K array"),
			new EnumerationTerm("Agilent-024504 Yersinia_CGH_20090707", "Agilent-024504 Yersinia_CGH_20090707"),
			new EnumerationTerm("Agilent-029784 ETEC_CGH", "Agilent-029784 ETEC_CGH"),
			new EnumerationTerm("Agilent-031422 S_pneumoniae_CGH", "Agilent-031422 S_pneumoniae_CGH"),
			new EnumerationTerm("Agilent-032741 Neisseria_CGH", "Agilent-032741 Neisseria_CGH"),
			new EnumerationTerm("Applied Biosystems TaqMan Gene Expression Assays (human)", "Applied Biosystems TaqMan Gene Expression Assays (human)"),
			new EnumerationTerm("Applied Biosystems TaqMan human microRNA_Array v1.0 early access", "Applied Biosystems TaqMan human microRNA_Array v1.0 early access"),
			new EnumerationTerm("Arizona Gallus gallus 20.7K Oligo Array v1.0", "Arizona Gallus gallus 20.7K Oligo Array v1.0"),
			new EnumerationTerm("ARK-Genomics G. gallus 20K v1.0", "ARK-Genomics G. gallus 20K v1.0"),
			new EnumerationTerm("Arthropod Pathogen Microarray 1.5K v 1.0", "Arthropod Pathogen Microarray 1.5K v 1.0"),
			new EnumerationTerm("Atlas Human 1.2 Array (Cat. #7850-1)", "Atlas Human 1.2 Array (Cat. #7850-1)"),
			new EnumerationTerm("Atlas Rat 1.2 Array (Cat. #7854-1)", "Atlas Rat 1.2 Array (Cat. #7854-1)"),
			new EnumerationTerm("AtTile1F to Arabidopsis Tiling 1.0F", "AtTile1F to Arabidopsis Tiling 1.0F"),
			new EnumerationTerm("BCCRC Lam SMRTr array", "BCCRC Lam SMRTr array"),
			new EnumerationTerm("Bead-based microRNA profiling platform version 1", "Bead-based microRNA profiling platform version 1"),
			new EnumerationTerm("Biomphalaria glabrata 70-mer oligo array version 1", "Biomphalaria glabrata 70-mer oligo array version 1"),
			new EnumerationTerm("BOMC Bovine 25K v1.0", "BOMC Bovine 25K v1.0"),
			new EnumerationTerm("bthetaa511044F", "bthetaa511044F"),
			new EnumerationTerm("C. elegans 22k 60 mer array", "C. elegans 22k 60 mer array"),
			new EnumerationTerm("Caltech 16K cDNA Mouse Array", "Caltech 16K cDNA Mouse Array"),
			new EnumerationTerm("Caltech 16K Oligo Mouse Array", "Caltech 16K Oligo Mouse Array"),
			new EnumerationTerm("CapitalBio Mammalian miRNA Array Services V1[1].0", "CapitalBio Mammalian miRNA Array Services V1[1].0"),
			new EnumerationTerm("CapitalBio Silkworm microRNA _microarray Release 1", "CapitalBio Silkworm microRNA _microarray Release 1"),
			new EnumerationTerm("CCDTM Hs_CCDTM36k - version 1", "CCDTM Hs_CCDTM36k - version 1"),
			new EnumerationTerm("CCDTM miRNA700-V3 (H. sapiens and EBV subset; condensed)", "CCDTM miRNA700-V3 (H. sapiens and EBV subset; condensed)"),
			new EnumerationTerm("CDMC_Drosophila_12k1", "CDMC_Drosophila_12k1"),
			new EnumerationTerm("CDMC_Drosophila_Oligo14kv1/Oligo14kv2", "CDMC_Drosophila_Oligo14kv1/Oligo14kv2"),
			new EnumerationTerm("CEA - DSV/DRR/SGF : Human 25k oligo v1.0", "CEA - DSV/DRR/SGF : Human 25k oligo v1.0"),
			new EnumerationTerm("CERI Rat 6.7K ToxArrayIII", "CERI Rat 6.7K ToxArrayIII"),
			new EnumerationTerm("cGRASP Salmon 16k cDNA array", "cGRASP Salmon 16k cDNA array"),
			new EnumerationTerm("Chick Pineal 2006", "Chick Pineal 2006"),
			new EnumerationTerm("Chinnaiyan Human 20K Hs6", "Chinnaiyan Human 20K Hs6"),
			new EnumerationTerm("CHUGAI 41K", "CHUGAI 41K"),
			new EnumerationTerm("CME-Human-3K6_7", "CME-Human-3K6_7"),
			new EnumerationTerm("CNIO Human Oncochip 1.0 , 1.2 and 2.0", "CNIO Human Oncochip 1.0 , 1.2 and 2.0"),
			new EnumerationTerm("CRUKDMF_22K_v1.0.0", "CRUKDMF_22K_v1.0.0"),
			new EnumerationTerm("Custom Affymetrix Glyco v1 GeneChip", "Custom Affymetrix Glyco v1 GeneChip"),
			new EnumerationTerm("Custom Affymetrix Glyco v2 GeneChip", "Custom Affymetrix Glyco v2 GeneChip"),
			new EnumerationTerm("Custom Affymetrix Glyco v3 GeneChip", "Custom Affymetrix Glyco v3 GeneChip"),
			new EnumerationTerm("Custom human colon-CDMR DNA methylation array (384 CpG)", "Custom human colon-CDMR DNA methylation array (384 CpG)"),
			new EnumerationTerm("Custom Yeast Genomic 70-mer Oligonucleotide Microarray", "Custom Yeast Genomic 70-mer Oligonucleotide Microarray"),
			new EnumerationTerm("DASL Custom Prostate Panel by Gene", "DASL Custom Prostate Panel by Gene"),
			new EnumerationTerm("DASL Human Cancer Panel by Gene", "DASL Human Cancer Panel by Gene"),
			new EnumerationTerm("DEL-MAR 14K Integrated Systems", "DEL-MAR 14K Integrated Systems"),
			new EnumerationTerm("DGRC-D. melanogaster-DGRC2-17328-v1", "DGRC-D. melanogaster-DGRC2-17328-v1"),
			new EnumerationTerm("DIAS_PIG_55K3_v1", "DIAS_PIG_55K3_v1"),
			new EnumerationTerm("DiSteBa_Homo sapiens_Glioblastoma miRNA 340_v1.0", "DiSteBa_Homo sapiens_Glioblastoma miRNA 340_v1.0"),
			new EnumerationTerm("DJF Pig 55K v1", "DJF Pig 55K v1"),
			new EnumerationTerm("DKFZ/Operon Human Oligo Set v2.1", "DKFZ/Operon Human Oligo Set v2.1"),
			new EnumerationTerm("Dmel_arrayplatform", "Dmel_arrayplatform"),
			new EnumerationTerm("Drosophila_Life_Cycle", "Drosophila_Life_Cycle"),
			new EnumerationTerm("DualChip human SBCL", "DualChip human SBCL"),
			new EnumerationTerm("Duke Cryptococcus neoformans serotype D (JEC21) 8K", "Duke Cryptococcus neoformans serotype D (JEC21) 8K"),
			new EnumerationTerm("Duke Operon Porcine 10.5K Oligo Array", "Duke Operon Porcine 10.5K Oligo Array"),
			new EnumerationTerm("Eichler Segmental Duplication BAC array", "Eichler Segmental Duplication BAC array"),
			new EnumerationTerm("EMBL Mycoplasma pneumoniae Operon Oligonucleotide Array", "EMBL Mycoplasma pneumoniae Operon Oligonucleotide Array"),
			new EnumerationTerm("Emory University Custom Breast Cancer DASL Panel", "Emory University Custom Breast Cancer DASL Panel"),
			new EnumerationTerm("FAP-Human-4.8K03", "FAP-Human-4.8K03"),
			new EnumerationTerm("febit Homo Sapiens miRBase 13.0", "febit Homo Sapiens miRBase 13.0"),
			new EnumerationTerm("FH_yeast_cDNA", "FH_yeast_cDNA"),
			new EnumerationTerm("FHCRC Fly 12K v1.0", "FHCRC Fly 12K v1.0"),
			new EnumerationTerm("FHCRC Yeast Amplicon v1.1", "FHCRC Yeast Amplicon v1.1"),
			new EnumerationTerm("FHCRC-Francisella tularensis subsp. novicida-2K OligoArray Version 1", "FHCRC-Francisella tularensis subsp. novicida-2K OligoArray Version 1"),
			new EnumerationTerm("Focused Phage Epitope Microarray", "Focused Phage Epitope Microarray"),
			new EnumerationTerm("Fundulus heteroclitus array #1", "Fundulus heteroclitus array #1"),
			new EnumerationTerm("GE Healthcare/Amersham Biosciences CodeLink Human Whole Genome Bioarray", "GE Healthcare/Amersham Biosciences CodeLink Human Whole Genome Bioarray"),
			new EnumerationTerm("GE Healthcare/Amersham Biosciences CodeLink UniSet Rat I Bioarray, layout EXP5280X2-584", "GE Healthcare/Amersham Biosciences CodeLink UniSet Rat I Bioarray, layout EXP5280X2-584"),
			new EnumerationTerm("GE Healthcare/Amersham Biosciences CodeLink UniSet Rat I Bioarray, layout EXP5280X2-613", "GE Healthcare/Amersham Biosciences CodeLink UniSet Rat I Bioarray, layout EXP5280X2-613"),
			new EnumerationTerm("GE Healthcare/Amersham Biosciences CodeLink Mouse Whole Genome Bioarray", "GE Healthcare/Amersham Biosciences CodeLink Mouse Whole Genome Bioarray"),
			new EnumerationTerm("GE Healthcare/Amersham Biosciences CodeLink Rat Whole Genome Bioarray", "GE Healthcare/Amersham Biosciences CodeLink Rat Whole Genome Bioarray"),
			new EnumerationTerm("GE Healthcare/Amersham Biosciences CodeLink UniSet Human 20K I Bioarray", "GE Healthcare/Amersham Biosciences CodeLink UniSet Human 20K I Bioarray"),
			new EnumerationTerm("GE Healthcare/Amersham Biosciences CodeLink UniSet Rat I Bioarray, layout EXP5280X2-648", "GE Healthcare/Amersham Biosciences CodeLink UniSet Rat I Bioarray, layout EXP5280X2-648"),
			new EnumerationTerm("GNF1H", "GNF1H"),
			new EnumerationTerm("GNF1M", "GNF1M"),
			new EnumerationTerm("GRASP 16K version 2", "GRASP 16K version 2"),
			new EnumerationTerm("GRASP salmonid array, 16k v2.0 chip, updated data files 15 July 2005", "GRASP salmonid array, 16k v2.0 chip, updated data files 15 July 2005"),
			new EnumerationTerm("GSF/IEG mouse 21K array (+RZPD)", "GSF/IEG mouse 21K array (+RZPD)"),
			new EnumerationTerm("GSF/IEG mouse array", "GSF/IEG mouse array"),
			new EnumerationTerm("GUTHRIE_YEAST_SPLICINGARRAY_v20040216a", "GUTHRIE_YEAST_SPLICINGARRAY_v20040216a"),
			new EnumerationTerm("HartlLab Drosophilamelanogaster PCRproducts 22k", "HartlLab Drosophilamelanogaster PCRproducts 22k"),
			new EnumerationTerm("Helicos Heliscope (Homo sapiens)", "Helicos Heliscope (Homo sapiens)"),
			new EnumerationTerm("HG17_HELP_Promoter", "HG17_HELP_Promoter"),
			new EnumerationTerm("HG17_Human_60mer_1in2", "HG17_Human_60mer_1in2"),
			new EnumerationTerm("High density Euphorbia esula and Manihot esculenta array", "High density Euphorbia esula and Manihot esculenta array"),
			new EnumerationTerm("Hitachisoft AceGene Human Oligo Chip 30K 1 Chip Version", "Hitachisoft AceGene Human Oligo Chip 30K 1 Chip Version"),
			new EnumerationTerm("Hollings Marine Laboratory Crassostrea cDNA Array", "Hollings Marine Laboratory Crassostrea cDNA Array"),
			new EnumerationTerm("Homo sapiens 0.9 K allele specific expression 1", "Homo sapiens 0.9 K allele specific expression 1"),
			new EnumerationTerm("Homo sapiens 1.2 K allele specific expression 2", "Homo sapiens 1.2 K allele specific expression 2"),
			new EnumerationTerm("Homo sapiens 4.8K 02-01 amplified cDNA", "Homo sapiens 4.8K 02-01 amplified cDNA"),
			new EnumerationTerm("Hopkins Tag Array", "Hopkins Tag Array"),
			new EnumerationTerm("HP_002", "HP_002"),
			new EnumerationTerm("HP_Hutcharray_6-03", "HP_Hutcharray_6-03"),
			new EnumerationTerm("Hughes Lab Saccharomyces cerevisiae cDNA ORF array", "Hughes Lab Saccharomyces cerevisiae cDNA ORF array"),
			new EnumerationTerm("Human 3.0 A1", "Human 3.0 A1"),
			new EnumerationTerm("Human 30K 60-mer oligo array", "Human 30K 60-mer oligo array"),
			new EnumerationTerm("Human 32k tiling BAC array", "Human 32k tiling BAC array"),
			new EnumerationTerm("Human 6k Transcriptionally Informative Gene Panel for DASL", "Human 6k Transcriptionally Informative Gene Panel for DASL"),
			new EnumerationTerm("Human LymphDx 2.7k GeneChip", "Human LymphDx 2.7k GeneChip"),
			new EnumerationTerm("Human Unigene I, part 1", "Human Unigene I, part 1"),
			new EnumerationTerm("Human Unigene I, part 2", "Human Unigene I, part 2"),
			new EnumerationTerm("Human Unigene3.1 cDNA Array 37.5K v1.0", "Human Unigene3.1 cDNA Array 37.5K v1.0"),
			new EnumerationTerm("Illumina Custom Prostate Cancer DASL Panel 1.5K expression beadchip", "Illumina Custom Prostate Cancer DASL Panel 1.5K expression beadchip"),
			new EnumerationTerm("Illumina Custom Prostate Cancer DASL Panel miRNA", "Illumina Custom Prostate Cancer DASL Panel miRNA"),
			new EnumerationTerm("Illumina Genome Analyzer (Caenorhabditis elegans)", "Illumina Genome Analyzer (Caenorhabditis elegans)"),
			new EnumerationTerm("Illumina Genome Analyzer (Drosophila melanogaster)", "Illumina Genome Analyzer (Drosophila melanogaster)"),
			new EnumerationTerm("Illumina Genome Analyzer (Homo sapiens)", "Illumina Genome Analyzer (Homo sapiens)"),
			new EnumerationTerm("Illumina Genome Analyzer (Mus musculus)", "Illumina Genome Analyzer (Mus musculus)"),
			new EnumerationTerm("Illumina Genome Analyzer (Saccharomyces cerevisiae)", "Illumina Genome Analyzer (Saccharomyces cerevisiae)"),
			new EnumerationTerm("Illumina Genome Analyzer II (Bacteria)", "Illumina Genome Analyzer II (Bacteria)"),
			new EnumerationTerm("Illumina Genome Analyzer II (Caenorhabditis elegans)", "Illumina Genome Analyzer II (Caenorhabditis elegans)"),
			new EnumerationTerm("Illumina Genome Analyzer II (Drosophila melanogaster)", "Illumina Genome Analyzer II (Drosophila melanogaster)"),
			new EnumerationTerm("Illumina Genome Analyzer II (Homo sapiens)", "Illumina Genome Analyzer II (Homo sapiens)"),
			new EnumerationTerm("Illumina Genome Analyzer II (Mus musculus)", "Illumina Genome Analyzer II (Mus musculus)"),
			new EnumerationTerm("Illumina Genome Analyzer IIx (Homo sapiens)", "Illumina Genome Analyzer IIx (Homo sapiens)"),
			new EnumerationTerm("Illumina GoldenGate Methylation Cancer Panel I", "Illumina GoldenGate Methylation Cancer Panel I"),
			new EnumerationTerm("Illumina Human v1 MicroRNA expression beadchip", "Illumina Human v1 MicroRNA expression beadchip"),
			new EnumerationTerm("Illumina human-6 v2.0 expression beadchip (extended)", "Illumina human-6 v2.0 expression beadchip (extended)"),
			new EnumerationTerm("Illumina human-6 v2.0 expression beadchip", "Illumina human-6 v2.0 expression beadchip"),
			new EnumerationTerm("Illumina Human1M-Duov3 DNA Analysis BeadChip (Human1M-Duov3_B)", "Illumina Human1M-Duov3 DNA Analysis BeadChip (Human1M-Duov3_B)"),
			new EnumerationTerm("Illumina Human1Mv1 DNA Analysis BeadChip (Human1Mv1_C)", "Illumina Human1Mv1 DNA Analysis BeadChip (Human1Mv1_C)"),
			new EnumerationTerm("Illumina Human610-Quad v1.0 BeadChip", "Illumina Human610-Quad v1.0 BeadChip"),
			new EnumerationTerm("Illumina Human660W-Quad v1.0 BeadChip", "Illumina Human660W-Quad v1.0 BeadChip"),
			new EnumerationTerm("Illumina HumanCNV100W v1.0 BeadChip", "Illumina HumanCNV100W v1.0 BeadChip"),
			new EnumerationTerm("Illumina HumanCNV370-Duov1 DNA Analysis BeadChip (HumanCNV370v1)", "Illumina HumanCNV370-Duov1 DNA Analysis BeadChip (HumanCNV370v1)"),
			new EnumerationTerm("Illumina HumanCNV370-QuadV3 DNA Analysis BeadChip (HumanCNV370-QuadV3_C)", "Illumina HumanCNV370-QuadV3 DNA Analysis BeadChip (HumanCNV370-QuadV3_C)"),
			new EnumerationTerm("Illumina HumanCytoSnp-12 Beadchip version 1.0", "Illumina HumanCytoSnp-12 Beadchip version 1.0"),
			new EnumerationTerm("Illumina HumanCytoSnp-12 Beadchip version 2.0", "Illumina HumanCytoSnp-12 Beadchip version 2.0"),
			new EnumerationTerm("Illumina HumanExon510-Sv1 DNA Analysis BeadChip (HumanExon510Sv1_D)", "Illumina HumanExon510-Sv1 DNA Analysis BeadChip (HumanExon510Sv1_D)"),
			new EnumerationTerm("Illumina HumanHap300-Duov2 Genotyping BeadChip (HumanHap300v2_A)", "Illumina HumanHap300-Duov2 Genotyping BeadChip (HumanHap300v2_A)"),
			new EnumerationTerm("Illumina HumanHap550 Genotyping BeadChip v1", "Illumina HumanHap550 Genotyping BeadChip v1"),
			new EnumerationTerm("Illumina HumanHap550 Genotyping BeadChip v3", "Illumina HumanHap550 Genotyping BeadChip v3"),
			new EnumerationTerm("Illumina HumanHap550-Duov3 Genotyping BeadChip (HumanHap550-2v3_B)", "Illumina HumanHap550-Duov3 Genotyping BeadChip (HumanHap550-2v3_B)"),
			new EnumerationTerm("Illumina HumanHap650Yv3 Genotyping BeadChip (HumanHap650Yv3_A)", "Illumina HumanHap650Yv3 Genotyping BeadChip (HumanHap650Yv3_A)"),
			new EnumerationTerm("Illumina HumanHT-12 V3.0 expression beadchip", "Illumina HumanHT-12 V3.0 expression beadchip"),
			new EnumerationTerm("Illumina HumanHT-12 V4.0 expression beadchip", "Illumina HumanHT-12 V4.0 expression beadchip"),
			new EnumerationTerm("Illumina HumanMethylation27 BeadChip (HumanMethylation27_270596_v.1.2)", "Illumina HumanMethylation27 BeadChip (HumanMethylation27_270596_v.1.2)"),
			new EnumerationTerm("Illumina HumanOmni1-Quad BeadChip", "Illumina HumanOmni1-Quad BeadChip"),
			new EnumerationTerm("Illumina humanRef-8 v1.0 expression beadchip", "Illumina humanRef-8 v1.0 expression beadchip"),
			new EnumerationTerm("Illumina humanRef-8 v2.0 expression beadchip", "Illumina humanRef-8 v2.0 expression beadchip"),
			new EnumerationTerm("Illumina humanRef-8 v2.0 expression beadchip", "Illumina humanRef-8 v2.0 expression beadchip"),
			new EnumerationTerm("Illumina HumanRef-8 v3.0 expression beadchip", "Illumina HumanRef-8 v3.0 expression beadchip"),
			new EnumerationTerm("Illumina HumanRef-8 WG-DASL v3.0", "Illumina HumanRef-8 WG-DASL v3.0"),
			new EnumerationTerm("Illumina HumanWG-6 v3.0 expression beadchip", "Illumina HumanWG-6 v3.0 expression beadchip"),
			new EnumerationTerm("Illumina Mouse Ref-6 V1", "Illumina Mouse Ref-6 V1"),
			new EnumerationTerm("Illumina mouse-6 v1.0 expression beadchip", "Illumina mouse-6 v1.0 expression beadchip"),
			new EnumerationTerm("Illumina mouse-6 v1.1 expression beadchip [Array_Address_Id version]", "Illumina mouse-6 v1.1 expression beadchip [Array_Address_Id version]"),
			new EnumerationTerm("Illumina mouse-6 v1.1 expression beadchip", "Illumina mouse-6 v1.1 expression beadchip"),
			new EnumerationTerm("Illumina mouseRef-8 v1.1 expression beadchip", "Illumina mouseRef-8 v1.1 expression beadchip"),
			new EnumerationTerm("Illumina MouseRef-8 v2.0 expression beadchip", "Illumina MouseRef-8 v2.0 expression beadchip"),
			new EnumerationTerm("Illumina MouseWG-6 v2.0 expression beadchip", "Illumina MouseWG-6 v2.0 expression beadchip"),
			new EnumerationTerm("Illumina ratRef-12 v1.0 expression beadchip", "Illumina ratRef-12 v1.0 expression beadchip"),
			new EnumerationTerm("Incyte Drosophila LifeArray v1.0", "Incyte Drosophila LifeArray v1.0"),
			new EnumerationTerm("IncyteMouseGEM1", "IncyteMouseGEM1"),
			new EnumerationTerm("INSERM Homo sapiens 14K array Liverpool3", "INSERM Homo sapiens 14K array Liverpool3"),
			new EnumerationTerm("INSERM Homo sapiens 14K array_Liverpool2", "INSERM Homo sapiens 14K array_Liverpool2"),
			new EnumerationTerm("INSERM MWG human 23k oligo array_version 3", "INSERM MWG human 23k oligo array_version 3"),
			new EnumerationTerm("IntegraChip genome-wide BAC arrays", "IntegraChip genome-wide BAC arrays"),
			new EnumerationTerm("Invitrogen ProtoArray v5.0", "Invitrogen ProtoArray v5.0"),
			new EnumerationTerm("ISB Halobacterium Spotted Microarray", "ISB Halobacterium Spotted Microarray"),
			new EnumerationTerm("ISQ Chip Folsomia candida Collembola VU 15.7K version 2.0", "ISQ Chip Folsomia candida Collembola VU 15.7K version 2.0"),
			new EnumerationTerm("J.Kim Yeast Operon (2005,2006,2007)", "J.Kim Yeast Operon (2005,2006,2007)"),
			new EnumerationTerm("JCVI PFGRC Bacillus anthracis 23K vt3a array designed primarily based on strain Sterne", "JCVI PFGRC Bacillus anthracis 23K vt3a array designed primarily based on strain Sterne"),
			new EnumerationTerm("JCVI PFGRC Bacillus anthracis 25K vt3b array designed primarily based on strain Sterne", "JCVI PFGRC Bacillus anthracis 25K vt3b array designed primarily based on strain Sterne"),
			new EnumerationTerm("JCVI PFGRC Staphylococcus aureus 16K v9 array designed primarily based on strain USA300", "JCVI PFGRC Staphylococcus aureus 16K v9 array designed primarily based on strain USA300"),
			new EnumerationTerm("Keck Glycine max 18kA cDNA Prints101-108", "Keck Glycine max 18kA cDNA Prints101-108"),
			new EnumerationTerm("Khodursky Lab E. coli B 4290 ORFs Microarray", "Khodursky Lab E. coli B 4290 ORFs Microarray"),
			new EnumerationTerm("Li UCSF yeast 14062 v1.0", "Li UCSF yeast 14062 v1.0"),
			new EnumerationTerm("Lieb Lab at UNC-CH_Yeast Whole-genome Array (PCR-based)_for Buck MJ et al.", "Lieb Lab at UNC-CH_Yeast Whole-genome Array (PCR-based)_for Buck MJ et al."),
			new EnumerationTerm("Lovett_WUSTL_TFarray_v2", "Lovett_WUSTL_TFarray_v2"),
			new EnumerationTerm("Lovett/WUSTL_TFarray_v4", "Lovett/WUSTL_TFarray_v4"),
			new EnumerationTerm("Maize cDNA Generation II Version B", "Maize cDNA Generation II Version B"),
			new EnumerationTerm("Maize oligo array version 1.9 array A", "Maize oligo array version 1.9 array A"),
			new EnumerationTerm("Maize oligo array version 1.9 array B", "Maize oligo array version 1.9 array B"),
			new EnumerationTerm("Maize oligonucleotide array 46K version", "Maize oligonucleotide array 46K version"),
			new EnumerationTerm("Maize Pioneer Hi-Bred 105K mRNA Microarray", "Maize Pioneer Hi-Bred 105K mRNA Microarray"),
			new EnumerationTerm("MDL human 3k oligo array", "MDL human 3k oligo array"),
			new EnumerationTerm("MEEBO Mus musculus Oligo 70mer Array V1.0", "MEEBO Mus musculus Oligo 70mer Array V1.0"),
			new EnumerationTerm("MEEBO Mus musculus Oligo 70mer Array V1.1", "MEEBO Mus musculus Oligo 70mer Array V1.1"),
			new EnumerationTerm("Microarray lab/BRI-NRC Solanum chacoense 7.7K V1.0 array", "Microarray lab/BRI-NRC Solanum chacoense 7.7K V1.0 array"),
			new EnumerationTerm("miRCURY LNA microRNA Array, v.11.0 - hsa, mmu & rno", "miRCURY LNA microRNA Array, v.11.0 - hsa, mmu & rno"),
			new EnumerationTerm("mirVANA miRNA Bioarray V2", "mirVANA miRNA Bioarray V2"),
			new EnumerationTerm("MLRG Human 21K V12.0", "MLRG Human 21K V12.0"),
			new EnumerationTerm("MMRRC", "MMRRC"),
			new EnumerationTerm("Mouse oligo array using Operon 17K set", "Mouse oligo array using Operon 17K set"),
			new EnumerationTerm("mouse-6 v1.1 (Illumina)", "mouse-6 v1.1 (Illumina)"),
			new EnumerationTerm("MPIMG Homo sapiens 36k_arrayCGH8", "MPIMG Homo sapiens 36k_arrayCGH8"),
			new EnumerationTerm("MPIMG Homo sapiens 44K ArrayCGH4", "MPIMG Homo sapiens 44K ArrayCGH4"),
			new EnumerationTerm("MSU Dworkin Drosophila melanogaster wing 1400 V1", "MSU Dworkin Drosophila melanogaster wing 1400 V1"),
			new EnumerationTerm("MWG rat 10k oligo set", "MWG rat 10k oligo set"),
			new EnumerationTerm("Mycobacterium tuberculosis H37Rv proteome microarray", "Mycobacterium tuberculosis H37Rv proteome microarray"),
			new EnumerationTerm("National Engineering Research Center mammalian microRNA microarray", "National Engineering Research Center mammalian microRNA microarray"),
			new EnumerationTerm("NCI NimbleGen Homo sapiens HG17 Whole Genome 385K Tiling Set version 1", "NCI NimbleGen Homo sapiens HG17 Whole Genome 385K Tiling Set version 1"),
			new EnumerationTerm("NCI-60 cell line Reverse Phase Protein Lysate Array_modified", "NCI-60 cell line Reverse Phase Protein Lysate Array_modified"),
			new EnumerationTerm("NCI/ATC Hs-OperonV2", "NCI/ATC Hs-OperonV2"),
			new EnumerationTerm("NCI/ATC Mm-MEEBO", "NCI/ATC Mm-MEEBO"),
			new EnumerationTerm("NCI/LMT Mm_FCRF_UniGEM2", "NCI/LMT Mm_FCRF_UniGEM2"),
			new EnumerationTerm("NCI/Staudt human 15K v13", "NCI/Staudt human 15K v13"),
			new EnumerationTerm("NCSU_chicken_JS2 (312 oligos)", "NCSU_chicken_JS2 (312 oligos)"),
			new EnumerationTerm("Netherlands Cancer Institute human 3.5k BAC array", "Netherlands Cancer Institute human 3.5k BAC array"),
			new EnumerationTerm("NHGRI 12k cDNA Custom Array", "NHGRI 12k cDNA Custom Array"),
			new EnumerationTerm("NHICU Human 19K v1.0", "NHICU Human 19K v1.0"),
			new EnumerationTerm("NIA MGC, Mammalian Genome Collection", "NIA MGC, Mammalian Genome Collection"),
			new EnumerationTerm("NIA Mouse 17K_A", "NIA Mouse 17K_A"),
			new EnumerationTerm("NIA Mouse 17K_B", "NIA Mouse 17K_B"),
			new EnumerationTerm("NIA Mouse 22K Microarray v1.0 (Development 60-mer Oligo)", "NIA Mouse 22K Microarray v1.0 (Development 60-mer Oligo)"),
			new EnumerationTerm("NIA Mouse 44K Microarray v3.0 (Whole Genome 60-mer Oligo) [Agilent 015087]", "NIA Mouse 44K Microarray v3.0 (Whole Genome 60-mer Oligo) [Agilent 015087]"),
			new EnumerationTerm("NIAID - Mta[a,b,c]", "NIAID - Mta[a,b,c]"),
			new EnumerationTerm("NIAID Mycobacterium tuberculosis microarray Mtbb", "NIAID Mycobacterium tuberculosis microarray Mtbb"),
			new EnumerationTerm("NimbleGen Drosophila 385k array rel4 300bp", "NimbleGen Drosophila 385k array rel4 300bp"),
			new EnumerationTerm("NimbleGen Human 2.1M array [080131_HG18_WG_CGH_v2DCR_HX1]", "NimbleGen Human 2.1M array [080131_HG18_WG_CGH_v2DCR_HX1]"),
			new EnumerationTerm("NimbleGen Human 2.1M array", "NimbleGen Human 2.1M array"),
			new EnumerationTerm("Nimblegen Maize Whole-Genome Microarray 385K (VersionV1_4a.53)", "Nimblegen Maize Whole-Genome Microarray 385K (VersionV1_4a.53)"),
			new EnumerationTerm("NKI-CMF Homo sapiens 35k oligo array with DamID annotations", "NKI-CMF Homo sapiens 35k oligo array with DamID annotations"),
			new EnumerationTerm("NKI-CMF Homo sapiens 35k oligo array", "NKI-CMF Homo sapiens 35k oligo array"),
			new EnumerationTerm("NSF Rice Oligonucleotide Array 45K One Chip Version", "NSF Rice Oligonucleotide Array 45K One Chip Version"),
			new EnumerationTerm("Nuclear Chloroplast Transcriptome GST Macroarray", "Nuclear Chloroplast Transcriptome GST Macroarray"),
			new EnumerationTerm("NuGO array (human) NuGO_Hs1a520180 [CDF: Hs_ENTREZG_10]", "NuGO array (human) NuGO_Hs1a520180 [CDF: Hs_ENTREZG_10]"),
			new EnumerationTerm("NuGO array (mouse) NuGO_Mm1a520177", "NuGO array (mouse) NuGO_Mm1a520177"),
			new EnumerationTerm("Operon human v3 ~35K 70-mer two-color oligonucleotide microarrays.", "Operon human v3 ~35K 70-mer two-color oligonucleotide microarrays."),
			new EnumerationTerm("OSU-CCC MicroRNA Microarray Version 2.0", "OSU-CCC MicroRNA Microarray Version 2.0"),
			new EnumerationTerm("Penn/CHOP Homo sapiens 4.5K (BAC array for studying Neuroblastoma)", "Penn/CHOP Homo sapiens 4.5K (BAC array for studying Neuroblastoma)"),
			new EnumerationTerm("Phalanx Human OneArray", "Phalanx Human OneArray"),
			new EnumerationTerm("Potato 10k cDNA array version 2", "Potato 10k cDNA array version 2"),
			new EnumerationTerm("Potato 10k cDNA array version 3", "Potato 10k cDNA array version 3"),
			new EnumerationTerm("Potato 10k cDNA array version 4", "Potato 10k cDNA array version 4"),
			new EnumerationTerm("PRHU05-S1-0006 (PC Human Operon v2 21k)", "PRHU05-S1-0006 (PC Human Operon v2 21k)"),
			new EnumerationTerm("Protein Design Labs Hu03 Custom Affymetrix GeneChip Array", "Protein Design Labs Hu03 Custom Affymetrix GeneChip Array"),
			new EnumerationTerm("Prove-it Bacteria v 0.1", "Prove-it Bacteria v 0.1"),
			new EnumerationTerm("Qiagen-NRSP-8 porcine oligo array", "Qiagen-NRSP-8 porcine oligo array"),
			new EnumerationTerm("Rat Uniset 10K", "Rat Uniset 10K"),
			new EnumerationTerm("RenLab ENCODE PCR tiling array", "RenLab ENCODE PCR tiling array"),
			new EnumerationTerm("Research Genetics (Invitrogen) - GF211 Microarray Filter", "Research Genetics (Invitrogen) - GF211 Microarray Filter"),
			new EnumerationTerm("Rice Genome Oligo Set V1.0", "Rice Genome Oligo Set V1.0"),
			new EnumerationTerm("rikDacFC6", "rikDacFC6"),
			new EnumerationTerm("Riken Thermus thermophilus HB8 4K mRNA array", "Riken Thermus thermophilus HB8 4K mRNA array"),
			new EnumerationTerm("Riken Thermus thermophilus HB8 4K mRNA custom array, library Rev.2", "Riken Thermus thermophilus HB8 4K mRNA custom array, library Rev.2"),
			new EnumerationTerm("RNA Processing", "RNA Processing"),
			new EnumerationTerm("RNG-MRC_HU25k_NICE", "RNG-MRC_HU25k_NICE"),
			new EnumerationTerm("Roche AmpliChip Leukemia Custom Microarray", "Roche AmpliChip Leukemia Custom Microarray"),
			new EnumerationTerm("ROMA-mouse-85K-v1.0", "ROMA-mouse-85K-v1.0"),
			new EnumerationTerm("Rosenstiel Fundulus heteroclitus 7K array", "Rosenstiel Fundulus heteroclitus 7K array"),
			new EnumerationTerm("Rosetta (Merck) Blood donor experiment", "Rosetta (Merck) Blood donor experiment"),
			new EnumerationTerm("Rosetta (Merck) GEL Breast Tumor Profiles", "Rosetta (Merck) GEL Breast Tumor Profiles"),
			new EnumerationTerm("Rosetta human miRNA qPCR array", "Rosetta human miRNA qPCR array"),
			new EnumerationTerm("Rosetta/Merck (C57BL/6J X C3H/HeJ)F2 on ApoE null backgrounds 75K oligio array 1", "Rosetta/Merck (C57BL/6J X C3H/HeJ)F2 on ApoE null backgrounds 75K oligio array 1"),
			new EnumerationTerm("Rosetta/Merck Human 25k v2.2.1 microarray", "Rosetta/Merck Human 25k v2.2.1 microarray"),
			new EnumerationTerm("Rosetta/Merck Human 44k 1.1 microarray", "Rosetta/Merck Human 44k 1.1 microarray"),
			new EnumerationTerm("Rosetta/Merck Human RSTA Affymetrix 1.0 microarray, Custom CDF", "Rosetta/Merck Human RSTA Affymetrix 1.0 microarray, Custom CDF"),
			new EnumerationTerm("Rosetta/Merck Human RSTA Custom Affymetrix 1.0 microarray", "Rosetta/Merck Human RSTA Custom Affymetrix 1.0 microarray"),
			new EnumerationTerm("Rosetta/Merck Mouse 25k_v3", "Rosetta/Merck Mouse 25k_v3"),
			new EnumerationTerm("Rosetta/Merck Mouse 38.4K RSTA Custom Affymetrix 1.0 microarray Custom CDF", "Rosetta/Merck Mouse 38.4K RSTA Custom Affymetrix 1.0 microarray Custom CDF"),
			new EnumerationTerm("Rosetta/Merck Mouse 430 2.0 RSTA Custom CDF microarray", "Rosetta/Merck Mouse 430 2.0 RSTA Custom CDF microarray"),
			new EnumerationTerm("Rosetta/Merck Mouse 44k 1.0 microarray", "Rosetta/Merck Mouse 44k 1.0 microarray"),
			new EnumerationTerm("Rosetta/Merck Mouse TOE 75k Array 1 microarray", "Rosetta/Merck Mouse TOE 75k Array 1 microarray"),
			new EnumerationTerm("Rosetta/Merck Rat 50k v2.1 Array 1 microarray", "Rosetta/Merck Rat 50k v2.1 Array 1 microarray"),
			new EnumerationTerm("S. pombe 10K long oligonucleotide array", "S. pombe 10K long oligonucleotide array"),
			new EnumerationTerm("SAGE:10:NlaIII:Homo sapiens", "SAGE:10:NlaIII:Homo sapiens"),
			new EnumerationTerm("SAGE:10:NlaIII:Mus musculus", "SAGE:10:NlaIII:Mus musculus"),
			new EnumerationTerm("SAGE:17:NlaIII:Homo sapiens", "SAGE:17:NlaIII:Homo sapiens"),
			new EnumerationTerm("SAGE:17:NlaIII:Mus musculus", "SAGE:17:NlaIII:Mus musculus"),
			new EnumerationTerm("SAM1.1a", "SAM1.1a"),
			new EnumerationTerm("SAM3.0", "SAM3.0"),
			new EnumerationTerm("Sanger human ver 1", "Sanger human ver 1"),
			new EnumerationTerm("Sanger Pilot Study V1", "Sanger Pilot Study V1"),
			new EnumerationTerm("Scoelicolor_UMN_Def_v1.0", "Scoelicolor_UMN_Def_v1.0"),
			new EnumerationTerm("Sentrix Human-6 Expression BeadChip", "Sentrix Human-6 Expression BeadChip"),
			new EnumerationTerm("Sentrix Human-6 v2 Expression BeadChip", "Sentrix Human-6 v2 Expression BeadChip"),
			new EnumerationTerm("Sentrix HumanRef-8 Expression BeadChip", "Sentrix HumanRef-8 Expression BeadChip"),
			new EnumerationTerm("Sentrix HumanRef-8 v2 Expression BeadChip", "Sentrix HumanRef-8 v2 Expression BeadChip"),
			new EnumerationTerm("Sentrix Mouse-6 Expression BeadChip", "Sentrix Mouse-6 Expression BeadChip"),
			new EnumerationTerm("Sentrix MouseRef-8 Expression BeadChip", "Sentrix MouseRef-8 Expression BeadChip"),
			new EnumerationTerm("SFGF HEEBO Human Set v1.00 with custom orthopox oligos", "SFGF HEEBO Human Set v1.00 with custom orthopox oligos"),
			new EnumerationTerm("Sigma/Compugen custom rat 70-mer oligonucleotide 8k microarray", "Sigma/Compugen custom rat 70-mer oligonucleotide 8k microarray"),
			new EnumerationTerm("SNU_Breast_CGH_v1.0", "SNU_Breast_CGH_v1.0"),
			new EnumerationTerm("Stillman Lab CrabChip01", "Stillman Lab CrabChip01"),
			new EnumerationTerm("STv2_MMCC", "STv2_MMCC"),
			new EnumerationTerm("STv4_MMCC", "STv4_MMCC"),
			new EnumerationTerm("STv5B_MMCC", "STv5B_MMCC"),
			new EnumerationTerm("SU Homo sapiens 912", "SU Homo sapiens 912"),
			new EnumerationTerm("SWEGENE H_v2.1.1 55K", "SWEGENE H_v2.1.1 55K"),
			new EnumerationTerm("Swegene Human 27K RAP (positions from file)", "Swegene Human 27K RAP (positions from file)"),
			new EnumerationTerm("Swegene Human 27K RAP UniGene188 array", "Swegene Human 27K RAP UniGene188 array"),
			new EnumerationTerm("SWEGENE_BAC_32K_Full", "SWEGENE_BAC_32K_Full"),
			new EnumerationTerm("Swine Protein-Annotated Oligonucleotide Microarray", "Swine Protein-Annotated Oligonucleotide Microarray"),
			new EnumerationTerm("TAGC_H.Sapiens_9K_20041223", "TAGC_H.Sapiens_9K_20041223"),
			new EnumerationTerm("TB-1", "TB-1"),
			new EnumerationTerm("The miniarray (Arabidopsis Pathoarray) 464_001", "The miniarray (Arabidopsis Pathoarray) 464_001"),
			new EnumerationTerm("TIGR 40K Human array", "TIGR 40K Human array"),
			new EnumerationTerm("Treenomix poplar 15.5K cDNA microarray", "Treenomix poplar 15.5K cDNA microarray"),
			new EnumerationTerm("Treenomix spruce 21.8K cDNA microarray", "Treenomix spruce 21.8K cDNA microarray"),
			new EnumerationTerm("Tsinghua University mammalian 2K microRNA microarray", "Tsinghua University mammalian 2K microRNA microarray"),
			new EnumerationTerm("UCSF Cancer Center HumArray2.0", "UCSF Cancer Center HumArray2.0"),
			new EnumerationTerm("UCSF Homo sapiens 2.5K", "UCSF Homo sapiens 2.5K"),
			new EnumerationTerm("UCSF_HumArray", "UCSF_HumArray"),
			new EnumerationTerm("UCSF/Chanlab_Human_40986_MENS", "UCSF/Chanlab_Human_40986_MENS"),
			new EnumerationTerm("UF Nimblegen Populus trichocarpa Array", "UF Nimblegen Populus trichocarpa Array"),
			new EnumerationTerm("UHN Human CpG 12K Array (HCGI12K)", "UHN Human CpG 12K Array (HCGI12K)"),
			new EnumerationTerm("UHN Yeast 6.4kv6", "UHN Yeast 6.4kv6"),
			new EnumerationTerm("UHNMAC Human 19K v7", "UHNMAC Human 19K v7"),
			new EnumerationTerm("UIUC Bos taurus 13.2K 70-mer oligoarray", "UIUC Bos taurus 13.2K 70-mer oligoarray"),
			new EnumerationTerm("UIUC Cattle 7,872-element cDNA - alternate version", "UIUC Cattle 7,872-element cDNA - alternate version"),
			new EnumerationTerm("UMDNJ Human SNP Array", "UMDNJ Human SNP Array"),
			new EnumerationTerm("UMGC-IRCNA 9k A", "UMGC-IRCNA 9k A"),
			new EnumerationTerm("UMGC-IRCNA 9k B", "UMGC-IRCNA 9k B"),
			new EnumerationTerm("UniMuenster-HomoSapiens-30K-Promoter_v1", "UniMuenster-HomoSapiens-30K-Promoter_v1"),
			new EnumerationTerm("University of North Carolina School of Medicine Whole Human Genome Oligo Microarray G4112A (Probe Name version)", "University of North Carolina School of Medicine Whole Human Genome Oligo Microarray G4112A (Probe Name version)"),
			new EnumerationTerm("URGV Arabidopsis thaliana 25K CATMA_v2.1", "URGV Arabidopsis thaliana 25K CATMA_v2.1"),
			new EnumerationTerm("URGV Arabidopsis thaliana 25K CATMA_v2.2", "URGV Arabidopsis thaliana 25K CATMA_v2.2"),
			new EnumerationTerm("URGV Arabidopsis thaliana 25K CATMA_v2.3", "URGV Arabidopsis thaliana 25K CATMA_v2.3"),
			new EnumerationTerm("URGV Arabidopsis thaliana 34.6K CATMA_v5", "URGV Arabidopsis thaliana 34.6K CATMA_v5"),
			new EnumerationTerm("USP Blastocladiella emersonii 4.6 K Blasto3773 v2", "USP Blastocladiella emersonii 4.6 K Blasto3773 v2"),
			new EnumerationTerm("UT Austin Iyer yeast 6.4k ORF-only cDNA platform", "UT Austin Iyer yeast 6.4k ORF-only cDNA platform"),
			new EnumerationTerm("UT Austin Iyer yeast whole genome platform", "UT Austin Iyer yeast whole genome platform"),
			new EnumerationTerm("UT/TH_all-8mer-v1", "UT/TH_all-8mer-v1"),
			new EnumerationTerm("UWAPG Yeast 6K v1.0", "UWAPG Yeast 6K v1.0"),
			new EnumerationTerm("Valencia yeast v4", "Valencia yeast v4"),
			new EnumerationTerm("VCholerae_A", "VCholerae_A"),
			new EnumerationTerm("VDX_Homo_sapiens_Breast_2", "VDX_Homo_sapiens_Breast_2"),
			new EnumerationTerm("Viro3", "Viro3"),
			new EnumerationTerm("VMSR Mus 20K version 2", "VMSR Mus 20K version 2"),
			new EnumerationTerm("VUMC MACF human 6K BAC v45", "VUMC MACF human 6K BAC v45"),
			new EnumerationTerm("Walbot Zea mays 4x44K Agilent array", "Walbot Zea mays 4x44K Agilent array"),
			new EnumerationTerm("Whole Genome, Alternative Splicing Drosophila Chip v3", "Whole Genome, Alternative Splicing Drosophila Chip v3"),
			new EnumerationTerm("WiCell HG18 WG CGH 385K v2", "WiCell HG18 WG CGH 385K v2"),
			new EnumerationTerm("Yeast 70mer oligoset by4742", "Yeast 70mer oligoset by4742"),
			new EnumerationTerm("Yeast spotted cDNA microarray", "Yeast spotted cDNA microarray"),
			new EnumerationTerm("yeast_nucleosome_positioning_microarray 6-9", "yeast_nucleosome_positioning_microarray 6-9"),
			new EnumerationTerm("ZB/SBS-NTU Plasmodium falciparum 3D7 10.4K v1.0", "ZB/SBS-NTU Plasmodium falciparum 3D7 10.4K v1.0"),
			new EnumerationTerm("Zhejiang university human 449 oligonucleotide array", "Zhejiang university human 449 oligonucleotide array")
			});

	
}
