package org.sagebionetworks.web.client.ontology;

import java.util.HashMap;
import java.util.Map;

import org.sagebionetworks.web.client.DisplayConstants;

public class StaticOntologies {

	/**
	 * This is a temporary solution until we have an ontology service, as well
	 * as a mapping from annotation key to ontologies.
	 */
	private final Map<String, Ontology> annotationToOntology;

	public StaticOntologies() {
		annotationToOntology = new HashMap<String, Ontology>();
		annotationToOntology.put(StaticOntologies.STATUS.getDisplayName(),
				StaticOntologies.STATUS);
		annotationToOntology.put(StaticOntologies.LAYER_TYPES.getDisplayName(),
				StaticOntologies.LAYER_TYPES);
		annotationToOntology.put(StaticOntologies.LAYER_TYPE.getDisplayName(),
				StaticOntologies.LAYER_TYPE);
		annotationToOntology.put(StaticOntologies.VENDOR.getDisplayName(),
				StaticOntologies.VENDOR);
		annotationToOntology.put(StaticOntologies.PLATFORM.getDisplayName(),
				StaticOntologies.PLATFORM);
	}

	public Map<String, Ontology> getAnnotationToOntology() {
		return annotationToOntology;
	}

	public static final Ontology STATUS = new Ontology(
			DisplayConstants.SERVICE_STATUS_KEY, new OntologyTerm[] {
					new OntologyTerm("Active", "Active"),
					new OntologyTerm("Complete", "Complete") });

	public static final Ontology LAYER_TYPES = new Ontology(
			DisplayConstants.SERVICE_LAYER_TYPE_KEY, new OntologyTerm[] {
					new OntologyTerm("Genetic Sequence Data", "G"),
					new OntologyTerm("Clinical / Phenotypic", "C"),
					new OntologyTerm("Molecular Expression Data", "E"),
					new OntologyTerm("Media", "M")});

	public static final Ontology LAYER_TYPE = new Ontology("Layer Type",
			new OntologyTerm[] { new OntologyTerm("Expression", "Expression"),
					new OntologyTerm("Genotype", "Genotype"),
					new OntologyTerm("miRNA", "miRNA"),
					new OntologyTerm("CNV", "CNV"),
					new OntologyTerm("Phenotype", "Phenotype"),
					new OntologyTerm("Image", "Image"),
					new OntologyTerm("Analysis Result", "Analysis Result") });

	public static final Ontology VENDOR = new Ontology("Vendor",
			new OntologyTerm[] { new OntologyTerm("Expression", "Expression"),
					new OntologyTerm("Affymetrix", "Affymetrix"),
					new OntologyTerm("Agilent", "Agilent"),
					new OntologyTerm("Illumina", "Illumina"),
					new OntologyTerm("Nimblegen", "Nimblegen"),
					new OntologyTerm("Custom", "Custom") });

	public static final Ontology PLATFORM = new Ontology("platform",
			new OntologyTerm[] {			
			new OntologyTerm("ABI Human Genome Survey Microarray Version 2", "ABI Human Genome Survey Microarray Version 2"),
			new OntologyTerm("ABI Mouse Genome Survey Microarray", "ABI Mouse Genome Survey Microarray"),
			new OntologyTerm("Affymetrix Arabidopsis ATH1 Genome Array", "Affymetrix Arabidopsis ATH1 Genome Array"),
			new OntologyTerm("Affymetrix Arabidopsis Tiling 1.0R Array", "Affymetrix Arabidopsis Tiling 1.0R Array"),
			new OntologyTerm("Affymetrix Barley Genome Array", "Affymetrix Barley Genome Array"),
			new OntologyTerm("Affymetrix Bovine Genome Array", "Affymetrix Bovine Genome Array"),
			new OntologyTerm("Affymetrix C. elegans Genome Array", "Affymetrix C. elegans Genome Array"),
			new OntologyTerm("Affymetrix C. elegans Tiling 1.0R Array", "Affymetrix C. elegans Tiling 1.0R Array"),
			new OntologyTerm("Affymetrix Canine Genome 1.0 Array", "Affymetrix Canine Genome 1.0 Array"),
			new OntologyTerm("Affymetrix Canine Genome 2.0 Array", "Affymetrix Canine Genome 2.0 Array"),
			new OntologyTerm("Affymetrix Chicken Genome Array", "Affymetrix Chicken Genome Array"),
			new OntologyTerm("Affymetrix Chinese Hamster Ovary (CHO)-specific custom array", "Affymetrix Chinese Hamster Ovary (CHO)-specific custom array"),
			new OntologyTerm("Affymetrix custom Bradyrhizobium japonicum strain USDA 110 19K array", "Affymetrix custom Bradyrhizobium japonicum strain USDA 110 19K array"),
			new OntologyTerm("Affymetrix Drosophila Genome 2.0 Array", "Affymetrix Drosophila Genome 2.0 Array"),
			new OntologyTerm("Affymetrix Drosophila Genome Array", "Affymetrix Drosophila Genome Array"),
			new OntologyTerm("Affymetrix Drosophila Tiling 2.0R Array", "Affymetrix Drosophila Tiling 2.0R Array"),
			new OntologyTerm("Affymetrix E. coli Antisense Genome Array", "Affymetrix E. coli Antisense Genome Array"),
			new OntologyTerm("Affymetrix E. coli Genome 2.0 Array", "Affymetrix E. coli Genome 2.0 Array"),
			new OntologyTerm("Affymetrix GeneChip Early Access Mapping 500K Set Array (250K_Nsp_SNP)", "Affymetrix GeneChip Early Access Mapping 500K Set Array (250K_Nsp_SNP)"),
			new OntologyTerm("Affymetrix GeneChip HT-HG_U133A Early Access Array", "Affymetrix GeneChip HT-HG_U133A Early Access Array"),
			new OntologyTerm("Affymetrix GeneChip Human Genome HG-U133 Plus 2 Array [Brainarray Version 12]", "Affymetrix GeneChip Human Genome HG-U133 Plus 2 Array [Brainarray Version 12]"),
			new OntologyTerm("Affymetrix GeneChip Human Genome U133 Array Set HG-U133A [CDF: Hs133A_Hs_UG_3]", "Affymetrix GeneChip Human Genome U133 Array Set HG-U133A [CDF: Hs133A_Hs_UG_3]"),
			new OntologyTerm("Affymetrix GeneChip Human Genome U133 Plus 2.0 Array (MBNI v11 Entrez Gene ID CDF)", "Affymetrix GeneChip Human Genome U133 Plus 2.0 Array (MBNI v11 Entrez Gene ID CDF)"),
			new OntologyTerm("Affymetrix GeneChip Human Genome U133 Plus 2.0 Array [CDF: Hs133P_Hs_ENTREZG.cdf]", "Affymetrix GeneChip Human Genome U133 Plus 2.0 Array [CDF: Hs133P_Hs_ENTREZG.cdf]"),
			new OntologyTerm("Affymetrix GeneChip Human Genome U133A 2.0 Array [CDF: Brainarray Version 10, Hs133Av2_Hs_ENTREZG]", "Affymetrix GeneChip Human Genome U133A 2.0 Array [CDF: Brainarray Version 10, Hs133Av2_Hs_ENTREZG]"),
			new OntologyTerm("Affymetrix GeneChip Mapping 500K Early Access Array (250K_Sty_SNP)", "Affymetrix GeneChip Mapping 500K Early Access Array (250K_Sty_SNP)"),
			new OntologyTerm("Affymetrix GeneChip S. cerevisiae Tiling 1.0R Array", "Affymetrix GeneChip S. cerevisiae Tiling 1.0R Array"),
			new OntologyTerm("Affymetrix GeneChip Universal 70K Tag Array", "Affymetrix GeneChip Universal 70K Tag Array"),
			new OntologyTerm("Affymetrix Genome-Wide Human SNP 5.0 Array", "Affymetrix Genome-Wide Human SNP 5.0 Array"),
			new OntologyTerm("Affymetrix Genome-Wide Human SNP 6.0 Array", "Affymetrix Genome-Wide Human SNP 6.0 Array"),
			new OntologyTerm("Affymetrix Glyco v3 GeneChip", "Affymetrix Glyco v3 GeneChip"),
			new OntologyTerm("Affymetrix HT HG-U133+ PM Array Plate", "Affymetrix HT HG-U133+ PM Array Plate"),
			new OntologyTerm("Affymetrix HT Human Genome U133A Array", "Affymetrix HT Human Genome U133A Array"),
			new OntologyTerm("Affymetrix HT Mouse Genome 430A Array", "Affymetrix HT Mouse Genome 430A Array"),
			new OntologyTerm("Affymetrix Human CentHindAv2 SNP Array", "Affymetrix Human CentHindAv2 SNP Array"),
			new OntologyTerm("Affymetrix Human CentXbaAv2 SNP Array", "Affymetrix Human CentXbaAv2 SNP Array"),
			new OntologyTerm("AFFYMETRIX Human Chromosomes 21 & 22 v2.0", "AFFYMETRIX Human Chromosomes 21 & 22 v2.0"),
			new OntologyTerm("Affymetrix Human Exon 1.0 ST Array [CDF: HuEx_1_0_st_v2_main_A20071112_EP.cdf]", "Affymetrix Human Exon 1.0 ST Array [CDF: HuEx_1_0_st_v2_main_A20071112_EP.cdf]"),
			new OntologyTerm("Affymetrix Human Exon 1.0 ST Array [HuEx-1_0-st-v2,coreR3,A20071112,EP.cdf]", "Affymetrix Human Exon 1.0 ST Array [HuEx-1_0-st-v2,coreR3,A20071112,EP.cdf]"),
			new OntologyTerm("Affymetrix Human Exon 1.0 ST Array [probe set (exon) version]", "Affymetrix Human Exon 1.0 ST Array [probe set (exon) version]"),
			new OntologyTerm("Affymetrix Human Exon 1.0 ST Array [transcript (gene) version]", "Affymetrix Human Exon 1.0 ST Array [transcript (gene) version]"),
			new OntologyTerm("Affymetrix Human Full Length HuGeneFL Array", "Affymetrix Human Full Length HuGeneFL Array"),
			new OntologyTerm("Affymetrix Human Gene 1.0 ST Array [transcript (gene) version]", "Affymetrix Human Gene 1.0 ST Array [transcript (gene) version]"),
			new OntologyTerm("Affymetrix Human Genome U133 Plus 2.0 Array [MBNI v12 Entrez Gene ID CDF]", "Affymetrix Human Genome U133 Plus 2.0 Array [MBNI v12 Entrez Gene ID CDF]"),
			new OntologyTerm("Affymetrix Human Genome U133 Plus 2.0 Array", "Affymetrix Human Genome U133 Plus 2.0 Array"),
			new OntologyTerm("Affymetrix Human Genome U133A 2.0 Array", "Affymetrix Human Genome U133A 2.0 Array"),
			new OntologyTerm("Affymetrix Human Genome U133A Array", "Affymetrix Human Genome U133A Array"),
			new OntologyTerm("Affymetrix Human Genome U133B Array", "Affymetrix Human Genome U133B Array"),
			new OntologyTerm("Affymetrix Human Genome U95 Version 2 Array", "Affymetrix Human Genome U95 Version 2 Array"),
			new OntologyTerm("Affymetrix Human Genome U95A Array", "Affymetrix Human Genome U95A Array"),
			new OntologyTerm("Affymetrix Human Genome U95B Array", "Affymetrix Human Genome U95B Array"),
			new OntologyTerm("Affymetrix Human Genome U95C Array", "Affymetrix Human Genome U95C Array"),
			new OntologyTerm("Affymetrix Human Genome U95D Array", "Affymetrix Human Genome U95D Array"),
			new OntologyTerm("Affymetrix Human Genome U95E Array", "Affymetrix Human Genome U95E Array"),
			new OntologyTerm("Affymetrix Human HG-Focus Target Array", "Affymetrix Human HG-Focus Target Array"),
			new OntologyTerm("Affymetrix human INDEL genotyping array", "Affymetrix human INDEL genotyping array"),
			new OntologyTerm("Affymetrix Human Mapping 10K 2.0 Array", "Affymetrix Human Mapping 10K 2.0 Array"),
			new OntologyTerm("Affymetrix Human Mapping 10K SNP Array", "Affymetrix Human Mapping 10K SNP Array"),
			new OntologyTerm("Affymetrix Human Mapping 50K Hind240 SNP Array", "Affymetrix Human Mapping 50K Hind240 SNP Array"),
			new OntologyTerm("Affymetrix Human Mapping 50K Xba240 SNP Array", "Affymetrix Human Mapping 50K Xba240 SNP Array"),
			new OntologyTerm("Affymetrix human mitochondrial array [CDF: FATMITO1a520158F]", "Affymetrix human mitochondrial array [CDF: FATMITO1a520158F]"),
			new OntologyTerm("Affymetrix Human Promoter 1.0R Array", "Affymetrix Human Promoter 1.0R Array"),
			new OntologyTerm("Affymetrix Human Tiling 2.0R Set, Array 1", "Affymetrix Human Tiling 2.0R Set, Array 1"),
			new OntologyTerm("Affymetrix Human Tiling 2.0R Set, Array 2", "Affymetrix Human Tiling 2.0R Set, Array 2"),
			new OntologyTerm("Affymetrix Human Tiling 2.0R Set, Array 3", "Affymetrix Human Tiling 2.0R Set, Array 3"),
			new OntologyTerm("Affymetrix Human Tiling 2.0R Set, Array 4", "Affymetrix Human Tiling 2.0R Set, Array 4"),
			new OntologyTerm("Affymetrix Human Tiling 2.0R Set, Array 5", "Affymetrix Human Tiling 2.0R Set, Array 5"),
			new OntologyTerm("Affymetrix Human Tiling 2.0R Set, Array 6", "Affymetrix Human Tiling 2.0R Set, Array 6"),
			new OntologyTerm("Affymetrix Human Tiling 2.0R Set, Array 7", "Affymetrix Human Tiling 2.0R Set, Array 7"),
			new OntologyTerm("Affymetrix Human X3P Array", "Affymetrix Human X3P Array"),
			new OntologyTerm("Affymetrix Maize Genome Array", "Affymetrix Maize Genome Array"),
			new OntologyTerm("Affymetrix Mapping 250K Nsp SNP Array", "Affymetrix Mapping 250K Nsp SNP Array"),
			new OntologyTerm("Affymetrix Mapping 250K Sty2 SNP Array", "Affymetrix Mapping 250K Sty2 SNP Array"),
			new OntologyTerm("Affymetrix Medicago Genome Array", "Affymetrix Medicago Genome Array"),
			new OntologyTerm("Affymetrix Mouse Exon 1.0 ST Array [probe set (exon) version]", "Affymetrix Mouse Exon 1.0 ST Array [probe set (exon) version]"),
			new OntologyTerm("Affymetrix Mouse Exon 1.0 ST Array [transcript (gene) version]", "Affymetrix Mouse Exon 1.0 ST Array [transcript (gene) version]"),
			new OntologyTerm("Affymetrix Mouse Expression 430A Array", "Affymetrix Mouse Expression 430A Array"),
			new OntologyTerm("Affymetrix Mouse Expression 430B Array", "Affymetrix Mouse Expression 430B Array"),
			new OntologyTerm("Affymetrix Mouse Gene 1.0 ST Array [CDF: MoGene10stv1_Mm_ENSG]", "Affymetrix Mouse Gene 1.0 ST Array [CDF: MoGene10stv1_Mm_ENSG]"),
			new OntologyTerm("Affymetrix Mouse Gene 1.0 ST Array [CDF: MoGene10stv1_Mm_ENST]", "Affymetrix Mouse Gene 1.0 ST Array [CDF: MoGene10stv1_Mm_ENST]"),
			new OntologyTerm("Affymetrix Mouse Gene 1.0 ST Array [transcript (gene) version]", "Affymetrix Mouse Gene 1.0 ST Array [transcript (gene) version]"),
			new OntologyTerm("Affymetrix Mouse Genome 430 2.0 Array", "Affymetrix Mouse Genome 430 2.0 Array"),
			new OntologyTerm("Affymetrix Mouse Genome 430A 2.0 Array", "Affymetrix Mouse Genome 430A 2.0 Array"),
			new OntologyTerm("Affymetrix Murine 11K SubA Array", "Affymetrix Murine 11K SubA Array"),
			new OntologyTerm("Affymetrix Murine 11K SubB Array", "Affymetrix Murine 11K SubB Array"),
			new OntologyTerm("Affymetrix Murine Genome U74 Version 2 Array", "Affymetrix Murine Genome U74 Version 2 Array"),
			new OntologyTerm("Affymetrix Murine Genome U74 Version 2 Array", "Affymetrix Murine Genome U74 Version 2 Array"),
			new OntologyTerm("Affymetrix Murine Genome U74 Version 2 Array", "Affymetrix Murine Genome U74 Version 2 Array"),
			new OntologyTerm("Affymetrix Murine Genome U74A Array", "Affymetrix Murine Genome U74A Array"),
			new OntologyTerm("Affymetrix Plasmodium/Anopheles Genome Array", "Affymetrix Plasmodium/Anopheles Genome Array"),
			new OntologyTerm("Affymetrix Poplar Genome Array", "Affymetrix Poplar Genome Array"),
			new OntologyTerm("Affymetrix Porcine Genome Array", "Affymetrix Porcine Genome Array"),
			new OntologyTerm("Affymetrix Pseudomonas aeruginosa Array", "Affymetrix Pseudomonas aeruginosa Array"),
			new OntologyTerm("Affymetrix Rat Exon 1.0 ST Array [probe set (exon) version]", "Affymetrix Rat Exon 1.0 ST Array [probe set (exon) version]"),
			new OntologyTerm("Affymetrix Rat Expression 230A Array", "Affymetrix Rat Expression 230A Array"),
			new OntologyTerm("Affymetrix Rat Gene 1.0 ST Array [transcript (gene) version]", "Affymetrix Rat Gene 1.0 ST Array [transcript (gene) version]"),
			new OntologyTerm("Affymetrix Rat Genome 230 2.0 Array", "Affymetrix Rat Genome 230 2.0 Array"),
			new OntologyTerm("Affymetrix Rat Genome U34 Array", "Affymetrix Rat Genome U34 Array"),
			new OntologyTerm("Affymetrix Rat Genome U34 Array", "Affymetrix Rat Genome U34 Array"),
			new OntologyTerm("Affymetrix Rat Genome U34 Array", "Affymetrix Rat Genome U34 Array"),
			new OntologyTerm("Affymetrix Rat Neurobiology U34 Array", "Affymetrix Rat Neurobiology U34 Array"),
			new OntologyTerm("Affymetrix Rhesus Macaque Genome Array", "Affymetrix Rhesus Macaque Genome Array"),
			new OntologyTerm("Affymetrix Rice Genome Array", "Affymetrix Rice Genome Array"),
			new OntologyTerm("Affymetrix RML Custom Pathogenic chip 1", "Affymetrix RML Custom Pathogenic chip 1"),
			new OntologyTerm("Affymetrix RML Custom Pathogenic chip 3", "Affymetrix RML Custom Pathogenic chip 3"),
			new OntologyTerm("Affymetrix S. aureus Genome Array", "Affymetrix S. aureus Genome Array"),
			new OntologyTerm("Affymetrix Soybean Genome Array", "Affymetrix Soybean Genome Array"),
			new OntologyTerm("Affymetrix Tomato Genome Array", "Affymetrix Tomato Genome Array"),
			new OntologyTerm("Affymetrix Toxoplasma gondii Custom GeneChip (CDF: ToxoDB version 4)", "Affymetrix Toxoplasma gondii Custom GeneChip (CDF: ToxoDB version 4)"),
			new OntologyTerm("Affymetrix Vitis vinifera (Grape) Genome Array", "Affymetrix Vitis vinifera (Grape) Genome Array"),
			new OntologyTerm("Affymetrix Wheat Genome Array", "Affymetrix Wheat Genome Array"),
			new OntologyTerm("Affymetrix Xenopus laevis Genome Array", "Affymetrix Xenopus laevis Genome Array"),
			new OntologyTerm("Affymetrix Yeast Genome 2.0 Array", "Affymetrix Yeast Genome 2.0 Array"),
			new OntologyTerm("Affymetrix Yeast Genome S98 Array", "Affymetrix Yeast Genome S98 Array"),
			new OntologyTerm("Affymetrix Zebrafish Genome Array", "Affymetrix Zebrafish Genome Array"),
			new OntologyTerm("AGENAE_PigGeneric2_9216", "AGENAE_PigGeneric2_9216"),
			new OntologyTerm("AGENAE_TroutGeneric2_9216", "AGENAE_TroutGeneric2_9216"),
			new OntologyTerm("Agendia_DiscoverPrint_v2", "Agendia_DiscoverPrint_v2"),
			new OntologyTerm("Agilent Custom Brassica 60-mer two-color microarray", "Agilent Custom Brassica 60-mer two-color microarray"),
			new OntologyTerm("Agilent custom-designed CpG island 60mer microarray 8x15k", "Agilent custom-designed CpG island 60mer microarray 8x15k"),
			new OntologyTerm("Agilent Eichler Human CNP 180K v2.1", "Agilent Eichler Human CNP 180K v2.1"),
			new OntologyTerm("Agilent Eichler Human CNP 180K v3.0", "Agilent Eichler Human CNP 180K v3.0"),
			new OntologyTerm("Agilent Homo sapiens 21.6K custom array", "Agilent Homo sapiens 21.6K custom array"),
			new OntologyTerm("Agilent Human 1 cDNA Microarray (G4100A) [layout C]", "Agilent Human 1 cDNA Microarray (G4100A) [layout C]"),
			new OntologyTerm("Agilent Human 1A Oligo UNC custom Microarrays", "Agilent Human 1A Oligo UNC custom Microarrays"),
			new OntologyTerm("Agilent RISET 2.0 8x15K 60mer oligonucleotide microarray", "Agilent RISET 2.0 8x15K 60mer oligonucleotide microarray"),
			new OntologyTerm("Agilent UNC Perou Lab Homo sapiens 1X44K Custom Array", "Agilent UNC Perou Lab Homo sapiens 1X44K Custom Array"),
			new OntologyTerm("Agilent-011447 Yeast Oligo Microarray G4140A (Feature Number version)", "Agilent-011447 Yeast Oligo Microarray G4140A (Feature Number version)"),
			new OntologyTerm("Agilent-011521 Human 1A Microarray G4110A (Feature Number version)", "Agilent-011521 Human 1A Microarray G4110A (Feature Number version)"),
			new OntologyTerm("Agilent-011868 Rat Oligo Microarray G4130A (Feature Number version)", "Agilent-011868 Rat Oligo Microarray G4130A (Feature Number version)"),
			new OntologyTerm("Agilent-011868_D_WithSGCtrls_20030627 Rat Oligo Microarray", "Agilent-011868_D_WithSGCtrls_20030627 Rat Oligo Microarray"),
			new OntologyTerm("Agilent-011978 Mouse Microarray G4121A (Feature Number version)", "Agilent-011978 Mouse Microarray G4121A (Feature Number version)"),
			new OntologyTerm("Agilent-011978 Mouse Microarray G4121A (Probe Name version)", "Agilent-011978 Mouse Microarray G4121A (Probe Name version)"),
			new OntologyTerm("Agilent-012097 Human 1A Microarray (V2) G4110B (Feature Number version)", "Agilent-012097 Human 1A Microarray (V2) G4110B (Feature Number version)"),
			new OntologyTerm("Agilent-012097 Human 1A Microarray (V2) G4110B (Probe Name version)", "Agilent-012097 Human 1A Microarray (V2) G4110B (Probe Name version)"),
			new OntologyTerm("Agilent-012106 Rice Oligo Microarray G4138A (Feature Number version)", "Agilent-012106 Rice Oligo Microarray G4138A (Feature Number version)"),
			new OntologyTerm("Agilent-012391 Whole Human Genome Oligo Microarray G4112A (Feature Number version)", "Agilent-012391 Whole Human Genome Oligo Microarray G4112A (Feature Number version)"),
			new OntologyTerm("Agilent-012391 Whole Human Genome Oligo Microarray G4112A (Probe Name version)", "Agilent-012391 Whole Human Genome Oligo Microarray G4112A (Probe Name version)"),
			new OntologyTerm("Agilent-012694 Whole Mouse Genome G4122A (Feature Number version)", "Agilent-012694 Whole Mouse Genome G4122A (Feature Number version)"),
			new OntologyTerm("Agilent-013162 Whole Rat Genome Microarray G4131A (Feature Number version)", "Agilent-013162 Whole Rat Genome Microarray G4131A (Feature Number version)"),
			new OntologyTerm("Agilent-013282 Human Genome CGH Microarray 44B (Feature number version)", "Agilent-013282 Human Genome CGH Microarray 44B (Feature number version)"),
			new OntologyTerm("Agilent-013326 Mouse Oligo Microarray (V2) G4121B (Feature Number version)", "Agilent-013326 Mouse Oligo Microarray (V2) G4121B (Feature Number version)"),
			new OntologyTerm("Agilent-013384 Yeast Oligo Microarray (V2) G4140B (Feature Number version)", "Agilent-013384 Yeast Oligo Microarray (V2) G4140B (Feature Number version)"),
			new OntologyTerm("Agilent-014693 Human Genome CGH Microarray 244A (Feature number version)", "Agilent-014693 Human Genome CGH Microarray 244A (Feature number version)"),
			new OntologyTerm("Agilent-014693 Human Genome CGH Microarray 244A (Probe name version)", "Agilent-014693 Human Genome CGH Microarray 244A (Probe name version)"),
			new OntologyTerm("Agilent-014695 Mouse Genome CGH Microarray 244A (G4415A)", "Agilent-014695 Mouse Genome CGH Microarray 244A (G4415A)"),
			new OntologyTerm("Agilent-014698 Human Genome CGH Microarray 105A (G4412A)", "Agilent-014698 Human Genome CGH Microarray 105A (G4412A)"),
			new OntologyTerm("Agilent-014810 Yeast Whole Genome ChIP-on-Chip Microarray 4x44K (G4493A)", "Agilent-014810 Yeast Whole Genome ChIP-on-Chip Microarray 4x44K (G4493A)"),
			new OntologyTerm("Agilent-014850 Whole Human Genome Microarray 4x44K G4112F (Feature Number version)", "Agilent-014850 Whole Human Genome Microarray 4x44K G4112F (Feature Number version)"),
			new OntologyTerm("Agilent-014850 Whole Human Genome Microarray 4x44K G4112F (Probe Name version)", "Agilent-014850 Whole Human Genome Microarray 4x44K G4112F (Probe Name version)"),
			new OntologyTerm("Agilent-014868 Whole Mouse Genome Microarray 4x44K G4122F (Feature Number version)", "Agilent-014868 Whole Mouse Genome Microarray 4x44K G4122F (Feature Number version)"),
			new OntologyTerm("Agilent-014868 Whole Mouse Genome Microarray 4x44K G4122F (Probe Name version)", "Agilent-014868 Whole Mouse Genome Microarray 4x44K G4122F (Probe Name version)"),
			new OntologyTerm("Agilent-014879 Whole Rat Genome Microarray 4x44K G4131F (Feature Number version)", "Agilent-014879 Whole Rat Genome Microarray 4x44K G4131F (Feature Number version)"),
			new OntologyTerm("Agilent-014879 Whole Rat Genome Microarray 4x44K G4131F (Probe Name version)", "Agilent-014879 Whole Rat Genome Microarray 4x44K G4131F (Probe Name version)"),
			new OntologyTerm("Agilent-015061 C. elegans Oligo Microarray 4x44K G2519F", "Agilent-015061 C. elegans Oligo Microarray 4x44K G2519F"),
			new OntologyTerm("Agilent-015241 Rice Gene Expression 4x44K Microarray (Feature Number version)", "Agilent-015241 Rice Gene Expression 4x44K Microarray (Feature Number version)"),
			new OntologyTerm("Agilent-016436 Human miRNA Microarray 1.0 (Feature Number version)", "Agilent-016436 Human miRNA Microarray 1.0 (Feature Number version)"),
			new OntologyTerm("Agilent-016436 Human miRNA Microarray 1.0 G4472A (miRNA ID version)", "Agilent-016436 Human miRNA Microarray 1.0 G4472A (miRNA ID version)"),
			new OntologyTerm("Agilent-019118 Human miRNA Microarray 2.0 G4470B (Feature Number version)", "Agilent-019118 Human miRNA Microarray 2.0 G4470B (Feature Number version)"),
			new OntologyTerm("Agilent-019118 Human miRNA Microarray 2.0 G4470B (miRNA ID version)", "Agilent-019118 Human miRNA Microarray 2.0 G4470B (miRNA ID version)"),
			new OntologyTerm("Agilent-019161 D. rerio (Zebrafish) Oligo Microarray (V2) G2519F (Feature Number version)", "Agilent-019161 D. rerio (Zebrafish) Oligo Microarray (V2) G2519F (Feature Number version)"),
			new OntologyTerm("Agilent-019182 Drosophila melanogaster Whole Genome ChIP-on-Chip Set 244K, Microarray 1 of 3", "Agilent-019182 Drosophila melanogaster Whole Genome ChIP-on-Chip Set 244K, Microarray 1 of 3"),
			new OntologyTerm("Agilent-019183 Drosophila melanogaster Whole Genome ChIP-on-Chip Set 244K, Microarray 2 of 3", "Agilent-019183 Drosophila melanogaster Whole Genome ChIP-on-Chip Set 244K, Microarray 2 of 3"),
			new OntologyTerm("Agilent-019184 Drosophila melanogaster Whole Genome ChIP-on-Chip Set 244K, Microarray 3 of 3", "Agilent-019184 Drosophila melanogaster Whole Genome ChIP-on-Chip Set 244K, Microarray 3 of 3"),
			new OntologyTerm("Agilent-021219 New15K60mer-EfetidaArray", "Agilent-021219 New15K60mer-EfetidaArray"),
			new OntologyTerm("Agilent-022589 Clostridium_botulinum_species_cgh_array 022588", "Agilent-022589 Clostridium_botulinum_species_cgh_array 022588"),
			new OntologyTerm("Agilent-022689 Custom BCM-Beaudet Human 1M Exon Autism Array", "Agilent-022689 Custom BCM-Beaudet Human 1M Exon Autism Array"),
			new OntologyTerm("Agilent-023456 Custom BCM-Beaudet Human 180K V8cleaned aCGH Array", "Agilent-023456 Custom BCM-Beaudet Human 180K V8cleaned aCGH Array"),
			new OntologyTerm("Agilent-024154 human hg18 45K array", "Agilent-024154 human hg18 45K array"),
			new OntologyTerm("Agilent-024504 Yersinia_CGH_20090707", "Agilent-024504 Yersinia_CGH_20090707"),
			new OntologyTerm("Agilent-029784 ETEC_CGH", "Agilent-029784 ETEC_CGH"),
			new OntologyTerm("Agilent-031422 S_pneumoniae_CGH", "Agilent-031422 S_pneumoniae_CGH"),
			new OntologyTerm("Agilent-032741 Neisseria_CGH", "Agilent-032741 Neisseria_CGH"),
			new OntologyTerm("Applied Biosystems TaqMan Gene Expression Assays (human)", "Applied Biosystems TaqMan Gene Expression Assays (human)"),
			new OntologyTerm("Applied Biosystems TaqMan human microRNA_Array v1.0 early access", "Applied Biosystems TaqMan human microRNA_Array v1.0 early access"),
			new OntologyTerm("Arizona Gallus gallus 20.7K Oligo Array v1.0", "Arizona Gallus gallus 20.7K Oligo Array v1.0"),
			new OntologyTerm("ARK-Genomics G. gallus 20K v1.0", "ARK-Genomics G. gallus 20K v1.0"),
			new OntologyTerm("Arthropod Pathogen Microarray 1.5K v 1.0", "Arthropod Pathogen Microarray 1.5K v 1.0"),
			new OntologyTerm("Atlas Human 1.2 Array (Cat. #7850-1)", "Atlas Human 1.2 Array (Cat. #7850-1)"),
			new OntologyTerm("Atlas Rat 1.2 Array (Cat. #7854-1)", "Atlas Rat 1.2 Array (Cat. #7854-1)"),
			new OntologyTerm("AtTile1F to Arabidopsis Tiling 1.0F", "AtTile1F to Arabidopsis Tiling 1.0F"),
			new OntologyTerm("BCCRC Lam SMRTr array", "BCCRC Lam SMRTr array"),
			new OntologyTerm("Bead-based microRNA profiling platform version 1", "Bead-based microRNA profiling platform version 1"),
			new OntologyTerm("Biomphalaria glabrata 70-mer oligo array version 1", "Biomphalaria glabrata 70-mer oligo array version 1"),
			new OntologyTerm("BOMC Bovine 25K v1.0", "BOMC Bovine 25K v1.0"),
			new OntologyTerm("bthetaa511044F", "bthetaa511044F"),
			new OntologyTerm("C. elegans 22k 60 mer array", "C. elegans 22k 60 mer array"),
			new OntologyTerm("Caltech 16K cDNA Mouse Array", "Caltech 16K cDNA Mouse Array"),
			new OntologyTerm("Caltech 16K Oligo Mouse Array", "Caltech 16K Oligo Mouse Array"),
			new OntologyTerm("CapitalBio Mammalian miRNA Array Services V1[1].0", "CapitalBio Mammalian miRNA Array Services V1[1].0"),
			new OntologyTerm("CapitalBio Silkworm microRNA _microarray Release 1", "CapitalBio Silkworm microRNA _microarray Release 1"),
			new OntologyTerm("CCDTM Hs_CCDTM36k - version 1", "CCDTM Hs_CCDTM36k - version 1"),
			new OntologyTerm("CCDTM miRNA700-V3 (H. sapiens and EBV subset; condensed)", "CCDTM miRNA700-V3 (H. sapiens and EBV subset; condensed)"),
			new OntologyTerm("CDMC_Drosophila_12k1", "CDMC_Drosophila_12k1"),
			new OntologyTerm("CDMC_Drosophila_Oligo14kv1/Oligo14kv2", "CDMC_Drosophila_Oligo14kv1/Oligo14kv2"),
			new OntologyTerm("CEA - DSV/DRR/SGF : Human 25k oligo v1.0", "CEA - DSV/DRR/SGF : Human 25k oligo v1.0"),
			new OntologyTerm("CERI Rat 6.7K ToxArrayIII", "CERI Rat 6.7K ToxArrayIII"),
			new OntologyTerm("cGRASP Salmon 16k cDNA array", "cGRASP Salmon 16k cDNA array"),
			new OntologyTerm("Chick Pineal 2006", "Chick Pineal 2006"),
			new OntologyTerm("Chinnaiyan Human 20K Hs6", "Chinnaiyan Human 20K Hs6"),
			new OntologyTerm("CHUGAI 41K", "CHUGAI 41K"),
			new OntologyTerm("CME-Human-3K6_7", "CME-Human-3K6_7"),
			new OntologyTerm("CNIO Human Oncochip 1.0 , 1.2 and 2.0", "CNIO Human Oncochip 1.0 , 1.2 and 2.0"),
			new OntologyTerm("CRUKDMF_22K_v1.0.0", "CRUKDMF_22K_v1.0.0"),
			new OntologyTerm("Custom Affymetrix Glyco v1 GeneChip", "Custom Affymetrix Glyco v1 GeneChip"),
			new OntologyTerm("Custom Affymetrix Glyco v2 GeneChip", "Custom Affymetrix Glyco v2 GeneChip"),
			new OntologyTerm("Custom Affymetrix Glyco v3 GeneChip", "Custom Affymetrix Glyco v3 GeneChip"),
			new OntologyTerm("Custom human colon-CDMR DNA methylation array (384 CpG)", "Custom human colon-CDMR DNA methylation array (384 CpG)"),
			new OntologyTerm("Custom Yeast Genomic 70-mer Oligonucleotide Microarray", "Custom Yeast Genomic 70-mer Oligonucleotide Microarray"),
			new OntologyTerm("DASL Custom Prostate Panel by Gene", "DASL Custom Prostate Panel by Gene"),
			new OntologyTerm("DASL Human Cancer Panel by Gene", "DASL Human Cancer Panel by Gene"),
			new OntologyTerm("DEL-MAR 14K Integrated Systems", "DEL-MAR 14K Integrated Systems"),
			new OntologyTerm("DGRC-D. melanogaster-DGRC2-17328-v1", "DGRC-D. melanogaster-DGRC2-17328-v1"),
			new OntologyTerm("DIAS_PIG_55K3_v1", "DIAS_PIG_55K3_v1"),
			new OntologyTerm("DiSteBa_Homo sapiens_Glioblastoma miRNA 340_v1.0", "DiSteBa_Homo sapiens_Glioblastoma miRNA 340_v1.0"),
			new OntologyTerm("DJF Pig 55K v1", "DJF Pig 55K v1"),
			new OntologyTerm("DKFZ/Operon Human Oligo Set v2.1", "DKFZ/Operon Human Oligo Set v2.1"),
			new OntologyTerm("Dmel_arrayplatform", "Dmel_arrayplatform"),
			new OntologyTerm("Drosophila_Life_Cycle", "Drosophila_Life_Cycle"),
			new OntologyTerm("DualChip human SBCL", "DualChip human SBCL"),
			new OntologyTerm("Duke Cryptococcus neoformans serotype D (JEC21) 8K", "Duke Cryptococcus neoformans serotype D (JEC21) 8K"),
			new OntologyTerm("Duke Operon Porcine 10.5K Oligo Array", "Duke Operon Porcine 10.5K Oligo Array"),
			new OntologyTerm("Eichler Segmental Duplication BAC array", "Eichler Segmental Duplication BAC array"),
			new OntologyTerm("EMBL Mycoplasma pneumoniae Operon Oligonucleotide Array", "EMBL Mycoplasma pneumoniae Operon Oligonucleotide Array"),
			new OntologyTerm("Emory University Custom Breast Cancer DASL Panel", "Emory University Custom Breast Cancer DASL Panel"),
			new OntologyTerm("FAP-Human-4.8K03", "FAP-Human-4.8K03"),
			new OntologyTerm("febit Homo Sapiens miRBase 13.0", "febit Homo Sapiens miRBase 13.0"),
			new OntologyTerm("FH_yeast_cDNA", "FH_yeast_cDNA"),
			new OntologyTerm("FHCRC Fly 12K v1.0", "FHCRC Fly 12K v1.0"),
			new OntologyTerm("FHCRC Yeast Amplicon v1.1", "FHCRC Yeast Amplicon v1.1"),
			new OntologyTerm("FHCRC-Francisella tularensis subsp. novicida-2K OligoArray Version 1", "FHCRC-Francisella tularensis subsp. novicida-2K OligoArray Version 1"),
			new OntologyTerm("Focused Phage Epitope Microarray", "Focused Phage Epitope Microarray"),
			new OntologyTerm("Fundulus heteroclitus array #1", "Fundulus heteroclitus array #1"),
			new OntologyTerm("GE Healthcare/Amersham Biosciences CodeLink Human Whole Genome Bioarray", "GE Healthcare/Amersham Biosciences CodeLink Human Whole Genome Bioarray"),
			new OntologyTerm("GE Healthcare/Amersham Biosciences CodeLink UniSet Rat I Bioarray, layout EXP5280X2-584", "GE Healthcare/Amersham Biosciences CodeLink UniSet Rat I Bioarray, layout EXP5280X2-584"),
			new OntologyTerm("GE Healthcare/Amersham Biosciences CodeLink UniSet Rat I Bioarray, layout EXP5280X2-613", "GE Healthcare/Amersham Biosciences CodeLink UniSet Rat I Bioarray, layout EXP5280X2-613"),
			new OntologyTerm("GE Healthcare/Amersham Biosciences CodeLink Mouse Whole Genome Bioarray", "GE Healthcare/Amersham Biosciences CodeLink Mouse Whole Genome Bioarray"),
			new OntologyTerm("GE Healthcare/Amersham Biosciences CodeLink Rat Whole Genome Bioarray", "GE Healthcare/Amersham Biosciences CodeLink Rat Whole Genome Bioarray"),
			new OntologyTerm("GE Healthcare/Amersham Biosciences CodeLink UniSet Human 20K I Bioarray", "GE Healthcare/Amersham Biosciences CodeLink UniSet Human 20K I Bioarray"),
			new OntologyTerm("GE Healthcare/Amersham Biosciences CodeLink UniSet Rat I Bioarray, layout EXP5280X2-648", "GE Healthcare/Amersham Biosciences CodeLink UniSet Rat I Bioarray, layout EXP5280X2-648"),
			new OntologyTerm("GNF1H", "GNF1H"),
			new OntologyTerm("GNF1M", "GNF1M"),
			new OntologyTerm("GRASP 16K version 2", "GRASP 16K version 2"),
			new OntologyTerm("GRASP salmonid array, 16k v2.0 chip, updated data files 15 July 2005", "GRASP salmonid array, 16k v2.0 chip, updated data files 15 July 2005"),
			new OntologyTerm("GSF/IEG mouse 21K array (+RZPD)", "GSF/IEG mouse 21K array (+RZPD)"),
			new OntologyTerm("GSF/IEG mouse array", "GSF/IEG mouse array"),
			new OntologyTerm("GUTHRIE_YEAST_SPLICINGARRAY_v20040216a", "GUTHRIE_YEAST_SPLICINGARRAY_v20040216a"),
			new OntologyTerm("HartlLab Drosophilamelanogaster PCRproducts 22k", "HartlLab Drosophilamelanogaster PCRproducts 22k"),
			new OntologyTerm("Helicos Heliscope (Homo sapiens)", "Helicos Heliscope (Homo sapiens)"),
			new OntologyTerm("HG17_HELP_Promoter", "HG17_HELP_Promoter"),
			new OntologyTerm("HG17_Human_60mer_1in2", "HG17_Human_60mer_1in2"),
			new OntologyTerm("High density Euphorbia esula and Manihot esculenta array", "High density Euphorbia esula and Manihot esculenta array"),
			new OntologyTerm("Hitachisoft AceGene Human Oligo Chip 30K 1 Chip Version", "Hitachisoft AceGene Human Oligo Chip 30K 1 Chip Version"),
			new OntologyTerm("Hollings Marine Laboratory Crassostrea cDNA Array", "Hollings Marine Laboratory Crassostrea cDNA Array"),
			new OntologyTerm("Homo sapiens 0.9 K allele specific expression 1", "Homo sapiens 0.9 K allele specific expression 1"),
			new OntologyTerm("Homo sapiens 1.2 K allele specific expression 2", "Homo sapiens 1.2 K allele specific expression 2"),
			new OntologyTerm("Homo sapiens 4.8K 02-01 amplified cDNA", "Homo sapiens 4.8K 02-01 amplified cDNA"),
			new OntologyTerm("Hopkins Tag Array", "Hopkins Tag Array"),
			new OntologyTerm("HP_002", "HP_002"),
			new OntologyTerm("HP_Hutcharray_6-03", "HP_Hutcharray_6-03"),
			new OntologyTerm("Hughes Lab Saccharomyces cerevisiae cDNA ORF array", "Hughes Lab Saccharomyces cerevisiae cDNA ORF array"),
			new OntologyTerm("Human 3.0 A1", "Human 3.0 A1"),
			new OntologyTerm("Human 30K 60-mer oligo array", "Human 30K 60-mer oligo array"),
			new OntologyTerm("Human 32k tiling BAC array", "Human 32k tiling BAC array"),
			new OntologyTerm("Human 6k Transcriptionally Informative Gene Panel for DASL", "Human 6k Transcriptionally Informative Gene Panel for DASL"),
			new OntologyTerm("Human LymphDx 2.7k GeneChip", "Human LymphDx 2.7k GeneChip"),
			new OntologyTerm("Human Unigene I, part 1", "Human Unigene I, part 1"),
			new OntologyTerm("Human Unigene I, part 2", "Human Unigene I, part 2"),
			new OntologyTerm("Human Unigene3.1 cDNA Array 37.5K v1.0", "Human Unigene3.1 cDNA Array 37.5K v1.0"),
			new OntologyTerm("Illumina Custom Prostate Cancer DASL Panel 1.5K expression beadchip", "Illumina Custom Prostate Cancer DASL Panel 1.5K expression beadchip"),
			new OntologyTerm("Illumina Custom Prostate Cancer DASL Panel miRNA", "Illumina Custom Prostate Cancer DASL Panel miRNA"),
			new OntologyTerm("Illumina Genome Analyzer (Caenorhabditis elegans)", "Illumina Genome Analyzer (Caenorhabditis elegans)"),
			new OntologyTerm("Illumina Genome Analyzer (Drosophila melanogaster)", "Illumina Genome Analyzer (Drosophila melanogaster)"),
			new OntologyTerm("Illumina Genome Analyzer (Homo sapiens)", "Illumina Genome Analyzer (Homo sapiens)"),
			new OntologyTerm("Illumina Genome Analyzer (Mus musculus)", "Illumina Genome Analyzer (Mus musculus)"),
			new OntologyTerm("Illumina Genome Analyzer (Saccharomyces cerevisiae)", "Illumina Genome Analyzer (Saccharomyces cerevisiae)"),
			new OntologyTerm("Illumina Genome Analyzer II (Bacteria)", "Illumina Genome Analyzer II (Bacteria)"),
			new OntologyTerm("Illumina Genome Analyzer II (Caenorhabditis elegans)", "Illumina Genome Analyzer II (Caenorhabditis elegans)"),
			new OntologyTerm("Illumina Genome Analyzer II (Drosophila melanogaster)", "Illumina Genome Analyzer II (Drosophila melanogaster)"),
			new OntologyTerm("Illumina Genome Analyzer II (Homo sapiens)", "Illumina Genome Analyzer II (Homo sapiens)"),
			new OntologyTerm("Illumina Genome Analyzer II (Mus musculus)", "Illumina Genome Analyzer II (Mus musculus)"),
			new OntologyTerm("Illumina Genome Analyzer IIx (Homo sapiens)", "Illumina Genome Analyzer IIx (Homo sapiens)"),
			new OntologyTerm("Illumina GoldenGate Methylation Cancer Panel I", "Illumina GoldenGate Methylation Cancer Panel I"),
			new OntologyTerm("Illumina Human v1 MicroRNA expression beadchip", "Illumina Human v1 MicroRNA expression beadchip"),
			new OntologyTerm("Illumina human-6 v2.0 expression beadchip (extended)", "Illumina human-6 v2.0 expression beadchip (extended)"),
			new OntologyTerm("Illumina human-6 v2.0 expression beadchip", "Illumina human-6 v2.0 expression beadchip"),
			new OntologyTerm("Illumina Human1M-Duov3 DNA Analysis BeadChip (Human1M-Duov3_B)", "Illumina Human1M-Duov3 DNA Analysis BeadChip (Human1M-Duov3_B)"),
			new OntologyTerm("Illumina Human1Mv1 DNA Analysis BeadChip (Human1Mv1_C)", "Illumina Human1Mv1 DNA Analysis BeadChip (Human1Mv1_C)"),
			new OntologyTerm("Illumina Human610-Quad v1.0 BeadChip", "Illumina Human610-Quad v1.0 BeadChip"),
			new OntologyTerm("Illumina Human660W-Quad v1.0 BeadChip", "Illumina Human660W-Quad v1.0 BeadChip"),
			new OntologyTerm("Illumina HumanCNV100W v1.0 BeadChip", "Illumina HumanCNV100W v1.0 BeadChip"),
			new OntologyTerm("Illumina HumanCNV370-Duov1 DNA Analysis BeadChip (HumanCNV370v1)", "Illumina HumanCNV370-Duov1 DNA Analysis BeadChip (HumanCNV370v1)"),
			new OntologyTerm("Illumina HumanCNV370-QuadV3 DNA Analysis BeadChip (HumanCNV370-QuadV3_C)", "Illumina HumanCNV370-QuadV3 DNA Analysis BeadChip (HumanCNV370-QuadV3_C)"),
			new OntologyTerm("Illumina HumanCytoSnp-12 Beadchip version 1.0", "Illumina HumanCytoSnp-12 Beadchip version 1.0"),
			new OntologyTerm("Illumina HumanCytoSnp-12 Beadchip version 2.0", "Illumina HumanCytoSnp-12 Beadchip version 2.0"),
			new OntologyTerm("Illumina HumanExon510-Sv1 DNA Analysis BeadChip (HumanExon510Sv1_D)", "Illumina HumanExon510-Sv1 DNA Analysis BeadChip (HumanExon510Sv1_D)"),
			new OntologyTerm("Illumina HumanHap300-Duov2 Genotyping BeadChip (HumanHap300v2_A)", "Illumina HumanHap300-Duov2 Genotyping BeadChip (HumanHap300v2_A)"),
			new OntologyTerm("Illumina HumanHap550 Genotyping BeadChip v1", "Illumina HumanHap550 Genotyping BeadChip v1"),
			new OntologyTerm("Illumina HumanHap550 Genotyping BeadChip v3", "Illumina HumanHap550 Genotyping BeadChip v3"),
			new OntologyTerm("Illumina HumanHap550-Duov3 Genotyping BeadChip (HumanHap550-2v3_B)", "Illumina HumanHap550-Duov3 Genotyping BeadChip (HumanHap550-2v3_B)"),
			new OntologyTerm("Illumina HumanHap650Yv3 Genotyping BeadChip (HumanHap650Yv3_A)", "Illumina HumanHap650Yv3 Genotyping BeadChip (HumanHap650Yv3_A)"),
			new OntologyTerm("Illumina HumanHT-12 V3.0 expression beadchip", "Illumina HumanHT-12 V3.0 expression beadchip"),
			new OntologyTerm("Illumina HumanHT-12 V4.0 expression beadchip", "Illumina HumanHT-12 V4.0 expression beadchip"),
			new OntologyTerm("Illumina HumanMethylation27 BeadChip (HumanMethylation27_270596_v.1.2)", "Illumina HumanMethylation27 BeadChip (HumanMethylation27_270596_v.1.2)"),
			new OntologyTerm("Illumina HumanOmni1-Quad BeadChip", "Illumina HumanOmni1-Quad BeadChip"),
			new OntologyTerm("Illumina humanRef-8 v1.0 expression beadchip", "Illumina humanRef-8 v1.0 expression beadchip"),
			new OntologyTerm("Illumina humanRef-8 v2.0 expression beadchip", "Illumina humanRef-8 v2.0 expression beadchip"),
			new OntologyTerm("Illumina humanRef-8 v2.0 expression beadchip", "Illumina humanRef-8 v2.0 expression beadchip"),
			new OntologyTerm("Illumina HumanRef-8 v3.0 expression beadchip", "Illumina HumanRef-8 v3.0 expression beadchip"),
			new OntologyTerm("Illumina HumanRef-8 WG-DASL v3.0", "Illumina HumanRef-8 WG-DASL v3.0"),
			new OntologyTerm("Illumina HumanWG-6 v3.0 expression beadchip", "Illumina HumanWG-6 v3.0 expression beadchip"),
			new OntologyTerm("Illumina Mouse Ref-6 V1", "Illumina Mouse Ref-6 V1"),
			new OntologyTerm("Illumina mouse-6 v1.0 expression beadchip", "Illumina mouse-6 v1.0 expression beadchip"),
			new OntologyTerm("Illumina mouse-6 v1.1 expression beadchip [Array_Address_Id version]", "Illumina mouse-6 v1.1 expression beadchip [Array_Address_Id version]"),
			new OntologyTerm("Illumina mouse-6 v1.1 expression beadchip", "Illumina mouse-6 v1.1 expression beadchip"),
			new OntologyTerm("Illumina mouseRef-8 v1.1 expression beadchip", "Illumina mouseRef-8 v1.1 expression beadchip"),
			new OntologyTerm("Illumina MouseRef-8 v2.0 expression beadchip", "Illumina MouseRef-8 v2.0 expression beadchip"),
			new OntologyTerm("Illumina MouseWG-6 v2.0 expression beadchip", "Illumina MouseWG-6 v2.0 expression beadchip"),
			new OntologyTerm("Illumina ratRef-12 v1.0 expression beadchip", "Illumina ratRef-12 v1.0 expression beadchip"),
			new OntologyTerm("Incyte Drosophila LifeArray v1.0", "Incyte Drosophila LifeArray v1.0"),
			new OntologyTerm("IncyteMouseGEM1", "IncyteMouseGEM1"),
			new OntologyTerm("INSERM Homo sapiens 14K array Liverpool3", "INSERM Homo sapiens 14K array Liverpool3"),
			new OntologyTerm("INSERM Homo sapiens 14K array_Liverpool2", "INSERM Homo sapiens 14K array_Liverpool2"),
			new OntologyTerm("INSERM MWG human 23k oligo array_version 3", "INSERM MWG human 23k oligo array_version 3"),
			new OntologyTerm("IntegraChip genome-wide BAC arrays", "IntegraChip genome-wide BAC arrays"),
			new OntologyTerm("Invitrogen ProtoArray v5.0", "Invitrogen ProtoArray v5.0"),
			new OntologyTerm("ISB Halobacterium Spotted Microarray", "ISB Halobacterium Spotted Microarray"),
			new OntologyTerm("ISQ Chip Folsomia candida Collembola VU 15.7K version 2.0", "ISQ Chip Folsomia candida Collembola VU 15.7K version 2.0"),
			new OntologyTerm("J.Kim Yeast Operon (2005,2006,2007)", "J.Kim Yeast Operon (2005,2006,2007)"),
			new OntologyTerm("JCVI PFGRC Bacillus anthracis 23K vt3a array designed primarily based on strain Sterne", "JCVI PFGRC Bacillus anthracis 23K vt3a array designed primarily based on strain Sterne"),
			new OntologyTerm("JCVI PFGRC Bacillus anthracis 25K vt3b array designed primarily based on strain Sterne", "JCVI PFGRC Bacillus anthracis 25K vt3b array designed primarily based on strain Sterne"),
			new OntologyTerm("JCVI PFGRC Staphylococcus aureus 16K v9 array designed primarily based on strain USA300", "JCVI PFGRC Staphylococcus aureus 16K v9 array designed primarily based on strain USA300"),
			new OntologyTerm("Keck Glycine max 18kA cDNA Prints101-108", "Keck Glycine max 18kA cDNA Prints101-108"),
			new OntologyTerm("Khodursky Lab E. coli B 4290 ORFs Microarray", "Khodursky Lab E. coli B 4290 ORFs Microarray"),
			new OntologyTerm("Li UCSF yeast 14062 v1.0", "Li UCSF yeast 14062 v1.0"),
			new OntologyTerm("Lieb Lab at UNC-CH_Yeast Whole-genome Array (PCR-based)_for Buck MJ et al.", "Lieb Lab at UNC-CH_Yeast Whole-genome Array (PCR-based)_for Buck MJ et al."),
			new OntologyTerm("Lovett_WUSTL_TFarray_v2", "Lovett_WUSTL_TFarray_v2"),
			new OntologyTerm("Lovett/WUSTL_TFarray_v4", "Lovett/WUSTL_TFarray_v4"),
			new OntologyTerm("Maize cDNA Generation II Version B", "Maize cDNA Generation II Version B"),
			new OntologyTerm("Maize oligo array version 1.9 array A", "Maize oligo array version 1.9 array A"),
			new OntologyTerm("Maize oligo array version 1.9 array B", "Maize oligo array version 1.9 array B"),
			new OntologyTerm("Maize oligonucleotide array 46K version", "Maize oligonucleotide array 46K version"),
			new OntologyTerm("Maize Pioneer Hi-Bred 105K mRNA Microarray", "Maize Pioneer Hi-Bred 105K mRNA Microarray"),
			new OntologyTerm("MDL human 3k oligo array", "MDL human 3k oligo array"),
			new OntologyTerm("MEEBO Mus musculus Oligo 70mer Array V1.0", "MEEBO Mus musculus Oligo 70mer Array V1.0"),
			new OntologyTerm("MEEBO Mus musculus Oligo 70mer Array V1.1", "MEEBO Mus musculus Oligo 70mer Array V1.1"),
			new OntologyTerm("Microarray lab/BRI-NRC Solanum chacoense 7.7K V1.0 array", "Microarray lab/BRI-NRC Solanum chacoense 7.7K V1.0 array"),
			new OntologyTerm("miRCURY LNA microRNA Array, v.11.0 - hsa, mmu & rno", "miRCURY LNA microRNA Array, v.11.0 - hsa, mmu & rno"),
			new OntologyTerm("mirVANA miRNA Bioarray V2", "mirVANA miRNA Bioarray V2"),
			new OntologyTerm("MLRG Human 21K V12.0", "MLRG Human 21K V12.0"),
			new OntologyTerm("MMRRC", "MMRRC"),
			new OntologyTerm("Mouse oligo array using Operon 17K set", "Mouse oligo array using Operon 17K set"),
			new OntologyTerm("mouse-6 v1.1 (Illumina)", "mouse-6 v1.1 (Illumina)"),
			new OntologyTerm("MPIMG Homo sapiens 36k_arrayCGH8", "MPIMG Homo sapiens 36k_arrayCGH8"),
			new OntologyTerm("MPIMG Homo sapiens 44K ArrayCGH4", "MPIMG Homo sapiens 44K ArrayCGH4"),
			new OntologyTerm("MSU Dworkin Drosophila melanogaster wing 1400 V1", "MSU Dworkin Drosophila melanogaster wing 1400 V1"),
			new OntologyTerm("MWG rat 10k oligo set", "MWG rat 10k oligo set"),
			new OntologyTerm("Mycobacterium tuberculosis H37Rv proteome microarray", "Mycobacterium tuberculosis H37Rv proteome microarray"),
			new OntologyTerm("National Engineering Research Center mammalian microRNA microarray", "National Engineering Research Center mammalian microRNA microarray"),
			new OntologyTerm("NCI NimbleGen Homo sapiens HG17 Whole Genome 385K Tiling Set version 1", "NCI NimbleGen Homo sapiens HG17 Whole Genome 385K Tiling Set version 1"),
			new OntologyTerm("NCI-60 cell line Reverse Phase Protein Lysate Array_modified", "NCI-60 cell line Reverse Phase Protein Lysate Array_modified"),
			new OntologyTerm("NCI/ATC Hs-OperonV2", "NCI/ATC Hs-OperonV2"),
			new OntologyTerm("NCI/ATC Mm-MEEBO", "NCI/ATC Mm-MEEBO"),
			new OntologyTerm("NCI/LMT Mm_FCRF_UniGEM2", "NCI/LMT Mm_FCRF_UniGEM2"),
			new OntologyTerm("NCI/Staudt human 15K v13", "NCI/Staudt human 15K v13"),
			new OntologyTerm("NCSU_chicken_JS2 (312 oligos)", "NCSU_chicken_JS2 (312 oligos)"),
			new OntologyTerm("Netherlands Cancer Institute human 3.5k BAC array", "Netherlands Cancer Institute human 3.5k BAC array"),
			new OntologyTerm("NHGRI 12k cDNA Custom Array", "NHGRI 12k cDNA Custom Array"),
			new OntologyTerm("NHICU Human 19K v1.0", "NHICU Human 19K v1.0"),
			new OntologyTerm("NIA MGC, Mammalian Genome Collection", "NIA MGC, Mammalian Genome Collection"),
			new OntologyTerm("NIA Mouse 17K_A", "NIA Mouse 17K_A"),
			new OntologyTerm("NIA Mouse 17K_B", "NIA Mouse 17K_B"),
			new OntologyTerm("NIA Mouse 22K Microarray v1.0 (Development 60-mer Oligo)", "NIA Mouse 22K Microarray v1.0 (Development 60-mer Oligo)"),
			new OntologyTerm("NIA Mouse 44K Microarray v3.0 (Whole Genome 60-mer Oligo) [Agilent 015087]", "NIA Mouse 44K Microarray v3.0 (Whole Genome 60-mer Oligo) [Agilent 015087]"),
			new OntologyTerm("NIAID - Mta[a,b,c]", "NIAID - Mta[a,b,c]"),
			new OntologyTerm("NIAID Mycobacterium tuberculosis microarray Mtbb", "NIAID Mycobacterium tuberculosis microarray Mtbb"),
			new OntologyTerm("NimbleGen Drosophila 385k array rel4 300bp", "NimbleGen Drosophila 385k array rel4 300bp"),
			new OntologyTerm("NimbleGen Human 2.1M array [080131_HG18_WG_CGH_v2DCR_HX1]", "NimbleGen Human 2.1M array [080131_HG18_WG_CGH_v2DCR_HX1]"),
			new OntologyTerm("NimbleGen Human 2.1M array", "NimbleGen Human 2.1M array"),
			new OntologyTerm("Nimblegen Maize Whole-Genome Microarray 385K (VersionV1_4a.53)", "Nimblegen Maize Whole-Genome Microarray 385K (VersionV1_4a.53)"),
			new OntologyTerm("NKI-CMF Homo sapiens 35k oligo array with DamID annotations", "NKI-CMF Homo sapiens 35k oligo array with DamID annotations"),
			new OntologyTerm("NKI-CMF Homo sapiens 35k oligo array", "NKI-CMF Homo sapiens 35k oligo array"),
			new OntologyTerm("NSF Rice Oligonucleotide Array 45K One Chip Version", "NSF Rice Oligonucleotide Array 45K One Chip Version"),
			new OntologyTerm("Nuclear Chloroplast Transcriptome GST Macroarray", "Nuclear Chloroplast Transcriptome GST Macroarray"),
			new OntologyTerm("NuGO array (human) NuGO_Hs1a520180 [CDF: Hs_ENTREZG_10]", "NuGO array (human) NuGO_Hs1a520180 [CDF: Hs_ENTREZG_10]"),
			new OntologyTerm("NuGO array (mouse) NuGO_Mm1a520177", "NuGO array (mouse) NuGO_Mm1a520177"),
			new OntologyTerm("Operon human v3 ~35K 70-mer two-color oligonucleotide microarrays.", "Operon human v3 ~35K 70-mer two-color oligonucleotide microarrays."),
			new OntologyTerm("OSU-CCC MicroRNA Microarray Version 2.0", "OSU-CCC MicroRNA Microarray Version 2.0"),
			new OntologyTerm("Penn/CHOP Homo sapiens 4.5K (BAC array for studying Neuroblastoma)", "Penn/CHOP Homo sapiens 4.5K (BAC array for studying Neuroblastoma)"),
			new OntologyTerm("Phalanx Human OneArray", "Phalanx Human OneArray"),
			new OntologyTerm("Potato 10k cDNA array version 2", "Potato 10k cDNA array version 2"),
			new OntologyTerm("Potato 10k cDNA array version 3", "Potato 10k cDNA array version 3"),
			new OntologyTerm("Potato 10k cDNA array version 4", "Potato 10k cDNA array version 4"),
			new OntologyTerm("PRHU05-S1-0006 (PC Human Operon v2 21k)", "PRHU05-S1-0006 (PC Human Operon v2 21k)"),
			new OntologyTerm("Protein Design Labs Hu03 Custom Affymetrix GeneChip Array", "Protein Design Labs Hu03 Custom Affymetrix GeneChip Array"),
			new OntologyTerm("Prove-it Bacteria v 0.1", "Prove-it Bacteria v 0.1"),
			new OntologyTerm("Qiagen-NRSP-8 porcine oligo array", "Qiagen-NRSP-8 porcine oligo array"),
			new OntologyTerm("Rat Uniset 10K", "Rat Uniset 10K"),
			new OntologyTerm("RenLab ENCODE PCR tiling array", "RenLab ENCODE PCR tiling array"),
			new OntologyTerm("Research Genetics (Invitrogen) - GF211 Microarray Filter", "Research Genetics (Invitrogen) - GF211 Microarray Filter"),
			new OntologyTerm("Rice Genome Oligo Set V1.0", "Rice Genome Oligo Set V1.0"),
			new OntologyTerm("rikDacFC6", "rikDacFC6"),
			new OntologyTerm("Riken Thermus thermophilus HB8 4K mRNA array", "Riken Thermus thermophilus HB8 4K mRNA array"),
			new OntologyTerm("Riken Thermus thermophilus HB8 4K mRNA custom array, library Rev.2", "Riken Thermus thermophilus HB8 4K mRNA custom array, library Rev.2"),
			new OntologyTerm("RNA Processing", "RNA Processing"),
			new OntologyTerm("RNG-MRC_HU25k_NICE", "RNG-MRC_HU25k_NICE"),
			new OntologyTerm("Roche AmpliChip Leukemia Custom Microarray", "Roche AmpliChip Leukemia Custom Microarray"),
			new OntologyTerm("ROMA-mouse-85K-v1.0", "ROMA-mouse-85K-v1.0"),
			new OntologyTerm("Rosenstiel Fundulus heteroclitus 7K array", "Rosenstiel Fundulus heteroclitus 7K array"),
			new OntologyTerm("Rosetta (Merck) Blood donor experiment", "Rosetta (Merck) Blood donor experiment"),
			new OntologyTerm("Rosetta (Merck) GEL Breast Tumor Profiles", "Rosetta (Merck) GEL Breast Tumor Profiles"),
			new OntologyTerm("Rosetta human miRNA qPCR array", "Rosetta human miRNA qPCR array"),
			new OntologyTerm("Rosetta/Merck (C57BL/6J X C3H/HeJ)F2 on ApoE null backgrounds 75K oligio array 1", "Rosetta/Merck (C57BL/6J X C3H/HeJ)F2 on ApoE null backgrounds 75K oligio array 1"),
			new OntologyTerm("Rosetta/Merck Human 25k v2.2.1 microarray", "Rosetta/Merck Human 25k v2.2.1 microarray"),
			new OntologyTerm("Rosetta/Merck Human 44k 1.1 microarray", "Rosetta/Merck Human 44k 1.1 microarray"),
			new OntologyTerm("Rosetta/Merck Human RSTA Affymetrix 1.0 microarray, Custom CDF", "Rosetta/Merck Human RSTA Affymetrix 1.0 microarray, Custom CDF"),
			new OntologyTerm("Rosetta/Merck Human RSTA Custom Affymetrix 1.0 microarray", "Rosetta/Merck Human RSTA Custom Affymetrix 1.0 microarray"),
			new OntologyTerm("Rosetta/Merck Mouse 25k_v3", "Rosetta/Merck Mouse 25k_v3"),
			new OntologyTerm("Rosetta/Merck Mouse 38.4K RSTA Custom Affymetrix 1.0 microarray Custom CDF", "Rosetta/Merck Mouse 38.4K RSTA Custom Affymetrix 1.0 microarray Custom CDF"),
			new OntologyTerm("Rosetta/Merck Mouse 430 2.0 RSTA Custom CDF microarray", "Rosetta/Merck Mouse 430 2.0 RSTA Custom CDF microarray"),
			new OntologyTerm("Rosetta/Merck Mouse 44k 1.0 microarray", "Rosetta/Merck Mouse 44k 1.0 microarray"),
			new OntologyTerm("Rosetta/Merck Mouse TOE 75k Array 1 microarray", "Rosetta/Merck Mouse TOE 75k Array 1 microarray"),
			new OntologyTerm("Rosetta/Merck Rat 50k v2.1 Array 1 microarray", "Rosetta/Merck Rat 50k v2.1 Array 1 microarray"),
			new OntologyTerm("S. pombe 10K long oligonucleotide array", "S. pombe 10K long oligonucleotide array"),
			new OntologyTerm("SAGE:10:NlaIII:Homo sapiens", "SAGE:10:NlaIII:Homo sapiens"),
			new OntologyTerm("SAGE:10:NlaIII:Mus musculus", "SAGE:10:NlaIII:Mus musculus"),
			new OntologyTerm("SAGE:17:NlaIII:Homo sapiens", "SAGE:17:NlaIII:Homo sapiens"),
			new OntologyTerm("SAGE:17:NlaIII:Mus musculus", "SAGE:17:NlaIII:Mus musculus"),
			new OntologyTerm("SAM1.1a", "SAM1.1a"),
			new OntologyTerm("SAM3.0", "SAM3.0"),
			new OntologyTerm("Sanger human ver 1", "Sanger human ver 1"),
			new OntologyTerm("Sanger Pilot Study V1", "Sanger Pilot Study V1"),
			new OntologyTerm("Scoelicolor_UMN_Def_v1.0", "Scoelicolor_UMN_Def_v1.0"),
			new OntologyTerm("Sentrix Human-6 Expression BeadChip", "Sentrix Human-6 Expression BeadChip"),
			new OntologyTerm("Sentrix Human-6 v2 Expression BeadChip", "Sentrix Human-6 v2 Expression BeadChip"),
			new OntologyTerm("Sentrix HumanRef-8 Expression BeadChip", "Sentrix HumanRef-8 Expression BeadChip"),
			new OntologyTerm("Sentrix HumanRef-8 v2 Expression BeadChip", "Sentrix HumanRef-8 v2 Expression BeadChip"),
			new OntologyTerm("Sentrix Mouse-6 Expression BeadChip", "Sentrix Mouse-6 Expression BeadChip"),
			new OntologyTerm("Sentrix MouseRef-8 Expression BeadChip", "Sentrix MouseRef-8 Expression BeadChip"),
			new OntologyTerm("SFGF HEEBO Human Set v1.00 with custom orthopox oligos", "SFGF HEEBO Human Set v1.00 with custom orthopox oligos"),
			new OntologyTerm("Sigma/Compugen custom rat 70-mer oligonucleotide 8k microarray", "Sigma/Compugen custom rat 70-mer oligonucleotide 8k microarray"),
			new OntologyTerm("SNU_Breast_CGH_v1.0", "SNU_Breast_CGH_v1.0"),
			new OntologyTerm("Stillman Lab CrabChip01", "Stillman Lab CrabChip01"),
			new OntologyTerm("STv2_MMCC", "STv2_MMCC"),
			new OntologyTerm("STv4_MMCC", "STv4_MMCC"),
			new OntologyTerm("STv5B_MMCC", "STv5B_MMCC"),
			new OntologyTerm("SU Homo sapiens 912", "SU Homo sapiens 912"),
			new OntologyTerm("SWEGENE H_v2.1.1 55K", "SWEGENE H_v2.1.1 55K"),
			new OntologyTerm("Swegene Human 27K RAP (positions from file)", "Swegene Human 27K RAP (positions from file)"),
			new OntologyTerm("Swegene Human 27K RAP UniGene188 array", "Swegene Human 27K RAP UniGene188 array"),
			new OntologyTerm("SWEGENE_BAC_32K_Full", "SWEGENE_BAC_32K_Full"),
			new OntologyTerm("Swine Protein-Annotated Oligonucleotide Microarray", "Swine Protein-Annotated Oligonucleotide Microarray"),
			new OntologyTerm("TAGC_H.Sapiens_9K_20041223", "TAGC_H.Sapiens_9K_20041223"),
			new OntologyTerm("TB-1", "TB-1"),
			new OntologyTerm("The miniarray (Arabidopsis Pathoarray) 464_001", "The miniarray (Arabidopsis Pathoarray) 464_001"),
			new OntologyTerm("TIGR 40K Human array", "TIGR 40K Human array"),
			new OntologyTerm("Treenomix poplar 15.5K cDNA microarray", "Treenomix poplar 15.5K cDNA microarray"),
			new OntologyTerm("Treenomix spruce 21.8K cDNA microarray", "Treenomix spruce 21.8K cDNA microarray"),
			new OntologyTerm("Tsinghua University mammalian 2K microRNA microarray", "Tsinghua University mammalian 2K microRNA microarray"),
			new OntologyTerm("UCSF Cancer Center HumArray2.0", "UCSF Cancer Center HumArray2.0"),
			new OntologyTerm("UCSF Homo sapiens 2.5K", "UCSF Homo sapiens 2.5K"),
			new OntologyTerm("UCSF_HumArray", "UCSF_HumArray"),
			new OntologyTerm("UCSF/Chanlab_Human_40986_MENS", "UCSF/Chanlab_Human_40986_MENS"),
			new OntologyTerm("UF Nimblegen Populus trichocarpa Array", "UF Nimblegen Populus trichocarpa Array"),
			new OntologyTerm("UHN Human CpG 12K Array (HCGI12K)", "UHN Human CpG 12K Array (HCGI12K)"),
			new OntologyTerm("UHN Yeast 6.4kv6", "UHN Yeast 6.4kv6"),
			new OntologyTerm("UHNMAC Human 19K v7", "UHNMAC Human 19K v7"),
			new OntologyTerm("UIUC Bos taurus 13.2K 70-mer oligoarray", "UIUC Bos taurus 13.2K 70-mer oligoarray"),
			new OntologyTerm("UIUC Cattle 7,872-element cDNA - alternate version", "UIUC Cattle 7,872-element cDNA - alternate version"),
			new OntologyTerm("UMDNJ Human SNP Array", "UMDNJ Human SNP Array"),
			new OntologyTerm("UMGC-IRCNA 9k A", "UMGC-IRCNA 9k A"),
			new OntologyTerm("UMGC-IRCNA 9k B", "UMGC-IRCNA 9k B"),
			new OntologyTerm("UniMuenster-HomoSapiens-30K-Promoter_v1", "UniMuenster-HomoSapiens-30K-Promoter_v1"),
			new OntologyTerm("University of North Carolina School of Medicine Whole Human Genome Oligo Microarray G4112A (Probe Name version)", "University of North Carolina School of Medicine Whole Human Genome Oligo Microarray G4112A (Probe Name version)"),
			new OntologyTerm("URGV Arabidopsis thaliana 25K CATMA_v2.1", "URGV Arabidopsis thaliana 25K CATMA_v2.1"),
			new OntologyTerm("URGV Arabidopsis thaliana 25K CATMA_v2.2", "URGV Arabidopsis thaliana 25K CATMA_v2.2"),
			new OntologyTerm("URGV Arabidopsis thaliana 25K CATMA_v2.3", "URGV Arabidopsis thaliana 25K CATMA_v2.3"),
			new OntologyTerm("URGV Arabidopsis thaliana 34.6K CATMA_v5", "URGV Arabidopsis thaliana 34.6K CATMA_v5"),
			new OntologyTerm("USP Blastocladiella emersonii 4.6 K Blasto3773 v2", "USP Blastocladiella emersonii 4.6 K Blasto3773 v2"),
			new OntologyTerm("UT Austin Iyer yeast 6.4k ORF-only cDNA platform", "UT Austin Iyer yeast 6.4k ORF-only cDNA platform"),
			new OntologyTerm("UT Austin Iyer yeast whole genome platform", "UT Austin Iyer yeast whole genome platform"),
			new OntologyTerm("UT/TH_all-8mer-v1", "UT/TH_all-8mer-v1"),
			new OntologyTerm("UWAPG Yeast 6K v1.0", "UWAPG Yeast 6K v1.0"),
			new OntologyTerm("Valencia yeast v4", "Valencia yeast v4"),
			new OntologyTerm("VCholerae_A", "VCholerae_A"),
			new OntologyTerm("VDX_Homo_sapiens_Breast_2", "VDX_Homo_sapiens_Breast_2"),
			new OntologyTerm("Viro3", "Viro3"),
			new OntologyTerm("VMSR Mus 20K version 2", "VMSR Mus 20K version 2"),
			new OntologyTerm("VUMC MACF human 6K BAC v45", "VUMC MACF human 6K BAC v45"),
			new OntologyTerm("Walbot Zea mays 4x44K Agilent array", "Walbot Zea mays 4x44K Agilent array"),
			new OntologyTerm("Whole Genome, Alternative Splicing Drosophila Chip v3", "Whole Genome, Alternative Splicing Drosophila Chip v3"),
			new OntologyTerm("WiCell HG18 WG CGH 385K v2", "WiCell HG18 WG CGH 385K v2"),
			new OntologyTerm("Yeast 70mer oligoset by4742", "Yeast 70mer oligoset by4742"),
			new OntologyTerm("Yeast spotted cDNA microarray", "Yeast spotted cDNA microarray"),
			new OntologyTerm("yeast_nucleosome_positioning_microarray 6-9", "yeast_nucleosome_positioning_microarray 6-9"),
			new OntologyTerm("ZB/SBS-NTU Plasmodium falciparum 3D7 10.4K v1.0", "ZB/SBS-NTU Plasmodium falciparum 3D7 10.4K v1.0"),
			new OntologyTerm("Zhejiang university human 449 oligonucleotide array", "Zhejiang university human 449 oligonucleotide array")
			});

	
}
