CREATE TABLE IF NOT EXISTS `DISCUSSION_THREAD_ENTITY_REFERENCE` (
  `THREAD_ID` BIGINT NOT NULL,
  `ENTITY_ID` BIGINT NOT NULL,
  PRIMARY KEY (`THREAD_ID`, `ENTITY_ID`),
  INDEX `DISCUSSION_THREAD_ENTITY_REFERENCE_ENTITY_ID_INDEX` (`ENTITY_ID`),
  CONSTRAINT `DISCUSSION_THREAD_ENTITY_REFERENCE_THREAD_ID_FK` FOREIGN KEY (`THREAD_ID`) REFERENCES `DISCUSSION_THREAD` (`ID`) ON DELETE CASCADE
)
