CREATE TABLE IF NOT EXISTS `DISCUSSION_SEARCH_INDEX` (
  `FORUM_ID` BIGINT NOT NULL,
  `THREAD_ID` BIGINT NOT NULL,
  `REPLY_ID` BIGINT NOT NULL,
  `SEARCH_CONTENT` TEXT NOT NULL,
  PRIMARY KEY (`FORUM_ID`, `THREAD_ID`, `REPLY_ID`),
  FULLTEXT (`SEARCH_CONTENT`),
  CONSTRAINT `DISCUSSION_SEARCH_INDEX_FORUM_ID_FK` FOREIGN KEY (`FORUM_ID`) REFERENCES `FORUM` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `DISCUSSION_SEARCH_INDEX_THREAD_ID_FK` FOREIGN KEY (`THREAD_ID`) REFERENCES `DISCUSSION_THREAD` (`ID`) ON DELETE CASCADE
)