CREATE TABLE IF NOT EXISTS `FORUM` (
  `ID` BIGINT NOT NULL,
  `OBJECT_ID` BIGINT NOT NULL,
  `OBJECT_TYPE` ENUM('ENTITY','ACCESS_REQUIREMENT') NOT NULL,
  `ETAG` char(36) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE (`OBJECT_ID`, `OBJECT_TYPE`)
)
