CREATE TABLE `PROJECT_STORAGE_LIMIT` (
  `ID` BIGINT NOT NULL,
  `ETAG` CHAR(36) NOT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` TIMESTAMP NOT NULL,
  `MODIFIED_BY` BIGINT NOT NULL,
  `MODIFIED_ON` TIMESTAMP NOT NULL,
  `PROJECT_ID` BIGINT NOT NULL,
  `STORAGE_LOCATION_ID` BIGINT NOT NULL,
  `MAX_BYTES` BIGINT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE(`PROJECT_ID`, `STORAGE_LOCATION_ID`) 
);