CREATE TABLE `PROJECT_STORAGE_DATA` (
  `PROJECT_ID` BIGINT NOT NULL,
  `ETAG` CHAR(36) NOT NULL,
  `MODIFIED_ON` TIMESTAMP NOT NULL,
  `RUNTIME_MS` BIGINT NOT NULL,
  `STORAGE_LOCATION_DATA` JSON NOT NULL,
  PRIMARY KEY (`PROJECT_ID`) 
);