CREATE TABLE JDOCOMPETITION_ADMIN (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `OWNER_ID` bigint(20) DEFAULT NULL,
  `GROUP_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `JDOCOMPETITION_ADMIN_FK` FOREIGN KEY (`OWNER_ID`) REFERENCES `JDOCOMPETITION` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `JDOCOMPETITION_ADMIN_ID_FK` FOREIGN KEY (`GROUP_ID`) REFERENCES `JDOUSERGROUP` (`ID`)
);