CREATE TABLE JDOPARTICIPANT (
    USER_ID bigint(20) NOT NULL,
    COMPETITION_ID bigint(20) NOT NULL,
    CREATED_ON bigint(20) NOT NULL,
    PRIMARY KEY PARTICIPANT_ID (USER_ID, COMPETITION_ID),
    FOREIGN KEY (COMPETITION_ID) REFERENCES JDOCOMPETITION (ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES JDOUSERGROUP (ID) ON DELETE CASCADE
);