CREATE TABLE JDOPARTICIPANT (
    USER_ID bigint(20) NOT NULL,
    COMPETITION_ID bigint(20) NOT NULL,
    JOIN_DATE bigint(20) NOT NULL,
    SCORE bigint(20) DEFAULT NULL,
    PRIMARY KEY (USER_ID, COMPETITION_ID),
    CONSTRAINT COMPETITION_ID_FK FOREIGN KEY (COMPETITION_ID) REFERENCES JDOCOMPETITION (ID),
    CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES JDOUSERGROUP (ID)
);