CREATE TABLE JDOSUBMISSION (
    ID bigint(20) NOT NULL,
    NAME varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    COMPETITION_ID bigint(20) NOT NULL,
    USER_ID bigint(20) NOT NULL,
    ENTITY_ID bigint(20) NOT NULL,
    VERSION bigint(20) NOT NULL,
    CREATED_ON bigint(20) NOT NULL,
    STATUS int NOT NULL,
    SCORE bigint(20) DEFAULT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID, COMPETITION_ID) REFERENCES JDOPARTICIPANT (USER_ID, COMPETITION_ID) ON DELETE CASCADE,
    FOREIGN KEY (ENTITY_ID) REFERENCES JDONODE (ID) ON DELETE CASCADE
);