CREATE TABLE SUBMISSION_STATUS (
    STATUS VARCHAR(20) PRIMARY KEY
);

INSERT INTO SUBMISSION_STATUS (STATUS) VALUES ('SUBMITTED'), ('PROCESSING'), ('SCORED'), ('INVALID');

CREATE TABLE JDOSUBMISSION (
    ID bigint(20) NOT NULL,
    NAME varchar(256)CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    COMPETITION_ID bigint(20) NOT NULL,
    PARTICIPANT_ID bigint(20) NOT NULL,
    ENTITY_ID bigint(20) NOT NULL,
    CREATED_ON bigint(20) NOT NULL,
    STATUS int NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT COMPETITION_ID_FK FOREIGN KEY (COMPETITION_ID)
        REFERENCES JDOCOMPETITION (ID)
        ON DELETE CASCADE,
    CONSTRAINT PARTICIPANT_ID_FK FOREIGN KEY (PARTICIPANT_ID)
        REFERENCES JDOPARTICIPANT (ID)
        ON DELETE CASCADE,
    CONSTRAINT SUBMISSION_STATUS_FK FOREIGN KEY (STATUS)
        REFERENCES SUBMISSION_STATUS (STATUS)
);