CREATE TABLE IF NOT EXISTS `FILES_SCANNER_STATUS` (
  `ID` BIGINT NOT NULL,
  `ETAG` CHAR(36) NOT NULL,
  `STARTED_ON` TIMESTAMP(3) NOT NULL,
  `UPDATED_ON` TIMESTAMP(3) NOT NULL,
  `STATE` ENUM('PROCESSING', 'COMPLETED', 'FAILED') NOT NULL,
  `JOBS_COUNT` BIGINT DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `KEY_STARTED_ON` (`STARTED_ON`)
)
