package org.sagebionetworks.repo.model.jdo.persistence;

import java.io.Serializable;
import java.util.StringTokenizer;

import javax.jdo.identity.LongIdentity;

/**
 * The composite primary key for a revision is its Node.id + RevisionNumber.
 * 
 * @author jmhill
 *
 */
public class RevisionId implements Serializable {
	public LongIdentity owner;
	public Long revisionNumber;

	public RevisionId() {
	}
	
	/**
	 * Create a new RevisionId from the two ids.
	 * @param nodeId
	 * @param revNumber
	 */
	public RevisionId(Long nodeId, Long revNumber) {
		this.owner = new LongIdentity(JDONode.class, nodeId); // field1
		this.revisionNumber = revNumber; // field2
	}

	/**
	 * Constructor accepting same input as generated by toString().
	 */
	public RevisionId(String value) {
		StringTokenizer token = new StringTokenizer(value, "::");
		token.nextToken(); // className
		this.owner = new LongIdentity(JDONode.class, Long.parseLong(token.nextToken())); // field1
		this.revisionNumber = Long.parseLong(token.nextToken()); // field2
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((owner == null) ? 0 : owner.hashCode());
		result = prime * result
				+ ((revisionNumber == null) ? 0 : revisionNumber.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		RevisionId other = (RevisionId) obj;
		if (owner == null) {
			if (other.owner != null)
				return false;
		} else if (!owner.equals(other.owner))
			return false;
		if (revisionNumber == null) {
			if (other.revisionNumber != null)
				return false;
		} else if (!revisionNumber.equals(other.revisionNumber))
			return false;
		return true;
	}

	public String toString() {
		// Give output expected by String constructor
		return this.getClass().getName() + "::" + this.owner + "::"
				+ this.revisionNumber;
	}
}
