package org.sagebionetworks.repo.model.dbo.dao;

import java.io.IOException;
import java.lang.reflect.Field;
import java.util.List;
import java.util.Map;

import org.sagebionetworks.repo.model.Annotations;
import org.sagebionetworks.repo.model.DatastoreException;
import org.sagebionetworks.repo.model.NamedAnnotations;
import org.sagebionetworks.repo.model.jdo.AnnotationUtils;
import org.sagebionetworks.repo.model.jdo.JDOSecondaryPropertyUtils;
import org.sagebionetworks.schema.ObjectSchema;

public class SchemaSerializationUtils {
	
	public static void mapAnnotationsToDtoFields(byte[] compressedProperties, Object dto, ObjectSchema schema) throws DatastoreException {
		NamedAnnotations properties = null;
		try {
			properties = AnnotationUtils.decompressedAnnotations(compressedProperties);
		} catch (IOException e) {
			throw new DatastoreException(e);
		}		
		
		Map<String, ObjectSchema> schemaProperties = schema.getProperties();
		Annotations a = properties.getPrimaryAnnotations();
		Map<String, List<String>> stringAnnots = a.getStringAnnotations();
		for (String propertyName : schemaProperties.keySet()) {
			try {
				Field field = dto.getClass().getDeclaredField(propertyName);
				field.setAccessible(true);
				Class fieldType = field.getType();
				if (!fieldType.equals(String.class)) {
					continue; // Skip fields that are not supported
				}
				List<String> values = stringAnnots.get(propertyName);
				if (values!=null && values.size()>0) {
					field.set(dto, values.get(0));
				}
			} catch (NoSuchFieldException | IllegalAccessException e) {
				// since the object is generated by the schema, this should never happen
				throw new RuntimeException(e);
			}
		}
	}


}
