CREATE TABLE IF NOT EXISTS `AGENT_REGISTRATION_ACT_SETTINGS` (
	`REGISTRATION_ID` BIGINT NOT NULL,
	`ETAG` CHAR(36) NOT NULL,
	`MODIFIED_ON` TIMESTAMP(3) NOT NULL,
	`MODIFIED_BY` BIGINT NOT NULL,
	`SETTINGS` JSON NOT NULL,
	PRIMARY KEY (`REGISTRATION_ID`),
	CONSTRAINT `AGENT_REG_ACT_SETTINGS_FK` FOREIGN KEY (`REGISTRATION_ID`) REFERENCES `AGENT_REGISTRATION` (`REGISTRATION_ID`) ON DELETE CASCADE
)
