CREATE TABLE IF NOT EXISTS `AGENT_REGISTRATION` (
	`REGISTRATION_ID` BIGINT NOT NULL,
	`AWS_AGENT_ID` CHAR(10) NOT NULL,
	`AWS_ALIAS_ID` CHAR(10) NOT NULL,
	`CREATED_ON` TIMESTAMP(3) NOT NULL,
	`AGENT_TYPE` ENUM('CUSTOM','BASELINE'),
	PRIMARY KEY (`REGISTRATION_ID`),
	UNIQUE INDEX `AGENT_REG_AWS_IDS` (`AWS_AGENT_ID`, AWS_ALIAS_ID)
)
