CREATE TABLE IF NOT EXISTS `AGENT_SESSION` (
  `ID` BIGINT NOT NULL,
  `ETAG` CHAR(36) NOT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `MODIFIED_ON` TIMESTAMP(3) NOT NULL,
  `SESSION_ID` CHAR(36) NOT NULL,
  `AGENT_ID` VARCHAR(256) NOT NULL,
  `ACCESS_LEVEL` ENUM('PUBLICLY_ACCESSIBLE','READ_YOUR_PRIVATE_DATA','WRITE_YOUR_PRIVATE_DATA'),
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `AGENT_SESSION_ID` (`SESSION_ID`),
  CONSTRAINT `AGENT_SES_USR_ID_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE CASCADE
)
