package org.sagebionetworks.repo.model.grid;

/**
 * 
 * Defines the source of an event, specifically, patches.
 */
public enum EventSource {

	/*
	 * Patches that from a user via websocket. There can be many user websocket.
	 * connections.
	 */
	WEBSOCKET(false, RequestOrigin.USER),
	/*
	 * Patches generated by the system when a grids session is initialized. DO NOT REUSE THIS FOR WRITING PATCHES.
	 */
	INTERNAL(true, RequestOrigin.SERVICE),
	/*
	 * Patches generated as a result of JSON schema validation.
	 */
	VALIDATION(true, RequestOrigin.SERVICE),
	/*
	 * Agent driven updates to the grid. There can be many agents for a single
	 * session.
	 */
	AGENT(false, RequestOrigin.USER),
	
	/*
	 * Patches generated by the system on the user behalf.
	 */
	USER_SUPPORT(true, RequestOrigin.SERVICE),

	/*
	 * Patches from users via the REST API. There can be many API connections per
	 * session, one per user. Used to attribute REST API updates to the calling user
	 * for cell-level attribution and sync change detection. API clients poll for
	 * results and do not receive real-time push notifications.
	 */
	API(false, RequestOrigin.USER),

	/*
	 * Patches generated by a CSV import performed on behalf of the calling user.
	 * There can be many import connections per session, one per importing user.
	 * User-origin so that imported cells carry user attribution and survive
	 * synchronization; see PLFM-9880.
	 */
	IMPORT(false, RequestOrigin.USER);

	private final boolean isSingleton;
	private final RequestOrigin requestOrigin;

	EventSource(boolean isSingleton, RequestOrigin requestOrigin) {
		this.isSingleton = isSingleton;
		this.requestOrigin = requestOrigin;
	}

	/**
	 * When true there will only be a single instance of the type per grid session.
	 * 
	 * @return
	 */
	public boolean isSingleton() {
		return isSingleton;
	}

	public RequestOrigin getRequestOrigin() {
		return requestOrigin;
	}

}
