package org.sagebionetworks.repo.model.grid;

/**
 * 
 * Defines the source of an event, specifically, patches.
 */
public enum EventSource {

	/*
	 * Patches that from a user via websocket. There can be many user websocket.
	 * connections.
	 */
	WEBSOCKET(false, RequestOrigin.USER),
	/*
	 * Patches generated by the system when a grids session is initialized. DO NOT REUSE THIS FOR WRITING PATCHES.
	 */
	INTERNAL(true, RequestOrigin.SERVICE),
	/*
	 * Patches generated as a result of JSON schema validation.
	 */
	VALIDATION(true, RequestOrigin.SERVICE),
	/*
	 * Agent driven updates to the grid. There can be many agents for a single
	 * session.
	 */
	AGENT(false, RequestOrigin.USER),
	
	/*
	 * Patches generated by the system on the user behalf.
	 */
	USER_SUPPORT(true, RequestOrigin.SERVICE);

	private final boolean isSingleton;
	private final RequestOrigin requestOrigin;

	EventSource(boolean isSingleton, RequestOrigin requestOrigin) {
		this.isSingleton = isSingleton;
		this.requestOrigin = requestOrigin;
	}

	/**
	 * When true there will only be a single instance of the type per grid session.
	 * 
	 * @return
	 */
	public boolean isSingleton() {
		return isSingleton;
	}

	public RequestOrigin getRequestOrigin() {
		return requestOrigin;
	}

}
