SELECT
  gp.SESSION_ID,
  gp.PATCH_ID_REP,
  gp.PATCH_ID_SEQ,
  gp.CREATED_ON,
  gp.EXPIRES_ON,
  gp.S3_KEY,
  gp.SIZE_BYTES
FROM
  GRID_PATCH AS gp
WHERE
  gp.SESSION_ID = ?
  AND (%s)
ORDER BY
  gp.PATCH_ID_SEQ, gp.PATCH_ID_REP
