WITH RECURSIVE CONTAINERS (ID) AS (
	 SELECT ID FROM JDONODE WHERE ID IN (:ids_param) AND NODE_TYPE IN ('project','folder')
	 UNION DISTINCT
	 SELECT N.ID FROM CONTAINERS AS C JOIN JDONODE AS N ON (C.ID = N.PARENT_ID AND N.NODE_TYPE IN ('project','folder'))
)
SELECT C.ID FROM CONTAINERS C LEFT JOIN JDONODE J ON C.ID = J.PARENT_ID WHERE J.ID IS NOT NULL LIMIT :bLimit