WITH RECURSIVE D (DEPENDS_ON_SCHEMA_ID, SCHEMA_ID, VERSION_ID) AS
(
  SELECT A.DEPENDS_ON_SCHEMA_ID, B.SCHEMA_ID, A.VERSION_ID 
  FROM JSON_SCHEMA_DEPENDENCY A JOIN JSON_SCHEMA_VERSION B 
  ON (A.VERSION_ID = B.VERSION_ID AND A.DEPENDS_ON_SCHEMA_ID = ?) 
  UNION 
  SELECT A.DEPENDS_ON_SCHEMA_ID, B.SCHEMA_ID, A.VERSION_ID 
  FROM JSON_SCHEMA_DEPENDENCY A JOIN JSON_SCHEMA_VERSION B JOIN D
  ON (A.VERSION_ID = B.VERSION_ID AND A.DEPENDS_ON_SCHEMA_ID = D.SCHEMA_ID)
)
SELECT DISTINCT VERSION_ID FROM D LIMIT ? OFFSET ?;