/**
 * The first table EI, defines the entity information for a given batch of entity IDs.
 * The second table EAR gathers all of the access restrictions for each entity based on the entity's hierarchy.
 * The third table APS gathers the access approval state for the user for each access restriction on each entity.
 * Finally all of the information is gathered into a single row for each access restriction on each entity.
 */
WITH 
	EI AS (
		SELECT N.ID AS ENTITY_ID, N.PARENT_ID, N.NODE_TYPE, N.CREATED_BY FROM NODE N WHERE N.ID IN(:entityIds)
	),
	EAR AS (
		WITH RECURSIVE EAR (ENTITY_ID, PARENT_ID, REQUIREMENT_ID, DISTANCE) AS (
			SELECT EI.ENTITY_ID, EI.PARENT_ID, NAR.REQUIREMENT_ID, 1 FROM EI 
				LEFT JOIN NODE_ACCESS_REQUIREMENT NAR ON (EI.ENTITY_ID = NAR.SUBJECT_ID AND NAR.SUBJECT_TYPE = 'ENTITY')
			UNION ALL 
			SELECT EAR.ENTITY_ID, N.PARENT_ID, NAR.REQUIREMENT_ID, EAR.DISTANCE+ 1 FROM NODE AS N
				 JOIN EAR ON (N.ID = EAR.PARENT_ID)
				 LEFT JOIN NODE_ACCESS_REQUIREMENT NAR ON (N.ID = NAR.SUBJECT_ID AND NAR.SUBJECT_TYPE = 'ENTITY')
				 	 WHERE N.ID IS NOT NULL AND DISTANCE < :depth
		)
		SELECT distinct ENTITY_ID, REQUIREMENT_ID FROM EAR WHERE REQUIREMENT_ID IS NOT NULL
	), 
	APS AS ( 
		SELECT EAR.*, if(AA.STATE = 'APPROVED', TRUE, FALSE) AS APPROVED FROM EAR
			LEFT JOIN ACCESS_APPROVAL AA
				ON (EAR.REQUIREMENT_ID = AA.REQUIREMENT_ID AND AA.ACCESSOR_ID = :userId AND AA.STATE = 'APPROVED')
	 ),
    AR AS(
        SELECT distinct REQUIREMENT_ID FROM EAR
    ),
    ACA AS(
        SELECT distinct AR.REQUIREMENT_ID AS REQUIREMENT_ID, ARA.ID AS ID FROM AR
          LEFT JOIN ACL ON (AR.REQUIREMENT_ID= ACL.OWNER_ID AND ACL.OWNER_TYPE = 'ACCESS_REQUIREMENT')
          LEFT JOIN ACL_RESOURCE_ACCESS ARA ON (ACL.ID = ARA.OWNER_ID AND ARA.GROUP_ID IN (:usersGroups))
            WHERE ACL.ID is not null
    ),
    ACC AS(
        SELECT distinct ACA.REQUIREMENT_ID AS REQUIREMENT_ID, IF(RAT.STRING_ELE ='EXEMPTION_ELIGIBLE', TRUE, FALSE) AS IS_EXAMPTION_ELIGIBLE FROM ACA
            LEFT JOIN ACL_RESOURCE_ACCESS_TYPE RAT ON (ACA.ID = RAT.ID_OID  AND RAT.STRING_ELE ='EXEMPTION_ELIGIBLE')
                WHERE RAT.STRING_ELE is not null
    )
SELECT 
	EI.ENTITY_ID,
	EI.NODE_TYPE,
	EI.CREATED_BY,
	APS.REQUIREMENT_ID,
	APS.APPROVED,
	AR.CONCRETE_TYPE AS REQUIREMENT_TYPE,
	AR.IS_TWO_FA_REQUIRED,
    ACC.IS_EXAMPTION_ELIGIBLE
		FROM EI LEFT JOIN APS ON (EI.ENTITY_ID = APS.ENTITY_ID)	
	 			LEFT JOIN ACCESS_REQUIREMENT AR ON (APS.REQUIREMENT_ID = AR.ID)
                LEFT JOIN ACC ON (AR.ID = ACC.REQUIREMENT_ID)
