WITH RECURSIVE BEN (ENTITY_ID, PARENT_ID, BENEFACTOR_ID, ACL_ID, DEPTH) AS	(
		SELECT N.ID, N.PARENT_ID, N.ID AS BENEFACTOR_ID, A.ID AS ACL_ID, 1 AS DEPTH
		FROM JDONODE N LEFT JOIN ACL A ON (N.ID = A.OWNER_ID AND A.OWNER_TYPE = 'ENTITY')
		WHERE %s
	UNION DISTINCT
		SELECT BEN.ENTITY_ID, N.PARENT_ID, N.ID AS BENEFACTOR_ID,
		A.ID AS ACL_ID, BEN.DEPTH + 1 AS DEPTH 
		FROM BEN JOIN JDONODE N ON (BEN.PARENT_ID = N.ID) 
		LEFT JOIN ACL A ON (N.ID = A.OWNER_ID AND A.OWNER_TYPE = 'ENTITY')
		WHERE BEN.ACL_ID IS NULL AND DEPTH < :depth
)
SELECT N.ID,
		 SUM(CRC32(CONCAT(':salt','-',N.ETAG,'-',R.NUMBER,'-', B.BENEFACTOR_ID))) AS CHECK_SUM
			FROM  BEN B JOIN JDONODE N ON (N.ID = B.ENTITY_ID) JOIN JDOREVISION R ON (N.ID = R.OWNER_NODE_ID) 
				WHERE B.ACL_ID IS NOT NULL AND B.BENEFACTOR_ID <> :trashId
GROUP BY N.ID
ORDER BY N.ID ASC
  