WITH 
 ALL_TABLES AS (
	SELECT 
		N.ID, 
		N.NODE_TYPE, 
		CASE WHEN N.CURRENT_REV_NUM = R.NUMBER THEN -1 ELSE R.NUMBER END AS VERSION
	FROM NODE N JOIN NODE_REVISION R ON (N.ID = R.OWNER_NODE_ID)
	WHERE N.NODE_TYPE IN (:tableTypes) 
    AND getEntityBenefactorId(N.PARENT_ID) <> :trashId
),
 SCHEMA_INFO AS (
	SELECT distinct OBJECT_ID, OBJECT_VERSION FROM BOUND_COLUMN_ORDINAL
 )
SELECT T.ID AS ID, T.NODE_TYPE AS TYPE, T.VERSION AS VERSION
	FROM ALL_TABLES T 
		LEFT JOIN TABLE_STATUS S 
			ON (T.ID = S.TABLE_ID AND T.VERSION = S.VERSION)
		JOIN SCHEMA_INFO I 
			ON (T.ID = I.OBJECT_ID AND T.VERSION = I.OBJECT_VERSION)
	WHERE S.TABLE_ID IS NULL ORDER BY ID, VERSION, TYPE LIMIT :limit;