CREATE TEMPORARY TABLE %S (
	`FILE_ID` BIGINT NOT NULL,
	`ACTION_TYPE` ENUM('ACCESS_REQUIREMENT', 'DOWNLOAD_PERMISSION') NOT NULL,
	`ACTION_ID` BIGINT NOT NULL,
	PRIMARY KEY (`FILE_ID`, `ACTION_TYPE`, `ACTION_ID`),
)