CREATE TABLE IF NOT EXISTS GRID_REPLICA_VEC (
	SESSION_ID BIGINT NOT NULL,
	REPLICA_ID BIGINT NOT NULL,
    VEC_REP BIGINT NOT NULL,
	VEC_SEQ BIGINT NOT NULL,
	VEC_VAL JSON NOT NULL,
	PRIMARY KEY (SESSION_ID, REPLICA_ID, VEC_REP, VEC_SEQ)
);