CREATE TABLE IF NOT EXISTS GRID_REPLICA_CLOCK (
	SESSION_ID BIGINT NOT NULL,
	REPLICA_ID BIGINT NOT NULL,
    CLOCK_ID_REP BIGINT NOT NULL,
    CLOCK_ID_SEQ BIGINT NOT NULL,
	PRIMARY KEY (SESSION_ID, REPLICA_ID, CLOCK_ID_REP),
	CONSTRAINT `GRID_CLCK_FK` FOREIGN KEY (SESSION_ID, REPLICA_ID) REFERENCES GRID_REPLICA(SESSION_ID, REPLICA_ID) ON DELETE CASCADE
);