CREATE TABLE IF NOT EXISTS GRID_REPLICA_CON (
	SESSION_ID BIGINT NOT NULL,
	REPLICA_ID BIGINT NOT NULL,
    CON_REP BIGINT NOT NULL,
	CON_SEQ BIGINT NOT NULL,
    CON_VAL JSON NOT NULL,
	PRIMARY KEY (SESSION_ID, REPLICA_ID, CON_SEQ, CON_REP),
	CONSTRAINT `GRID_CON_INDEX_FK` FOREIGN KEY (SESSION_ID, REPLICA_ID, CON_REP, CON_SEQ) REFERENCES GRID_REPLICA_INDEX(SESSION_ID, REPLICA_ID, NODE_REP, NODE_SEQ) ON DELETE CASCADE
);