CREATE TABLE IF NOT EXISTS GRID_REPLICA_OBJ (
	SESSION_ID BIGINT NOT NULL,
	REPLICA_ID BIGINT NOT NULL,
    OBJ_REP BIGINT NOT NULL,
	OBJ_SEQ BIGINT NOT NULL,
	OBJ_VAL JSON NOT NULL,
	PRIMARY KEY (SESSION_ID, REPLICA_ID, OBJ_REP, OBJ_SEQ),
    CONSTRAINT `GRID_OBJ_REPLICA_FK` FOREIGN KEY (SESSION_ID, REPLICA_ID) REFERENCES GRID_REPLICA(SESSION_ID, REPLICA_ID) ON DELETE CASCADE
);