CREATE TABLE IF NOT EXISTS GRID_REPLICA (
	SESSION_ID BIGINT NOT NULL,
	REPLICA_ID BIGINT NOT NULL,
	CREATED_ON TIMESTAMP(3) NOT NULL,
	LAST_MESSAGE_ID MEDIUMINT DEFAULT -1,
	PRIMARY KEY (SESSION_ID, REPLICA_ID)
);