CREATE TABLE IF NOT EXISTS GRID_REPLICA_RGA (
	SESSION_ID BIGINT NOT NULL,
	REPLICA_ID BIGINT NOT NULL,
    NODE_REP BIGINT NOT NULL,
    NODE_SEQ BIGINT NOT NULL,
    CTR_REP BIGINT NOT NULL,
    CTR_SEQ BIGINT NOT NULL,
	DATA_REP BIGINT,
    DATA_SEQ BIGINT,
	REF_REP BIGINT,
    REF_SEQ BIGINT,
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE, -- on delete, set to true, indicating that the node was deleted.
	PRIMARY KEY (SESSION_ID, REPLICA_ID, CTR_REP, CTR_SEQ, NODE_REP, NODE_SEQ),
	UNIQUE INDEX (SESSION_ID, REPLICA_ID, CTR_REP, CTR_SEQ, REF_REP, REF_SEQ),
    CONSTRAINT `GRID_RGA_REPLICA_FK` FOREIGN KEY (SESSION_ID, REPLICA_ID) REFERENCES GRID_REPLICA(SESSION_ID, REPLICA_ID) ON DELETE CASCADE
);