CREATE TABLE IF NOT EXISTS GRID_REPLICA_OBJ (
	SESSION_ID BIGINT NOT NULL,
	REPLICA_ID BIGINT NOT NULL,
    OBJ_REP BIGINT NOT NULL,
	OBJ_SEQ BIGINT NOT NULL,
	OBJ_VAL JSON NOT NULL,
	PRIMARY KEY (SESSION_ID, REPLICA_ID, OBJ_REP, OBJ_SEQ)
);