CREATE TABLE IF NOT EXISTS GRID_REPLICA_INDEX (
	SESSION_ID BIGINT NOT NULL,
	REPLICA_ID BIGINT NOT NULL,
    NODE_REP BIGINT NOT NULL,
	NODE_SEQ BIGINT NOT NULL,
    KIND ENUM ('con','obj','vec','arr','val'),
	PRIMARY KEY (SESSION_ID, REPLICA_ID, NODE_REP, NODE_SEQ),
	CONSTRAINT `GRID_INDEX_FK` FOREIGN KEY (SESSION_ID, REPLICA_ID) REFERENCES GRID_REPLICA(SESSION_ID, REPLICA_ID) ON DELETE CASCADE
	)