CREATE TABLE IF NOT EXISTS GRID_REPLICA_OBJ (
	SESSION_ID BIGINT NOT NULL,
	REPLICA_ID BIGINT NOT NULL,
    OBJ_REP BIGINT NOT NULL,
	OBJ_SEQ BIGINT NOT NULL,
	OBJ_VAL JSON NOT NULL,
	PRIMARY KEY (SESSION_ID, REPLICA_ID, OBJ_REP, OBJ_SEQ),
	CONSTRAINT `GRID_OBJ_INDEX_FK` FOREIGN KEY (SESSION_ID, REPLICA_ID, OBJ_REP, OBJ_SEQ) REFERENCES GRID_REPLICA_INDEX(SESSION_ID, REPLICA_ID, NODE_REP, NODE_SEQ) ON DELETE CASCADE
);