CREATE TABLE IF NOT EXISTS GRID_REPLICA_VAL (
	SESSION_ID BIGINT NOT NULL,
	REPLICA_ID BIGINT NOT NULL,
    VAL_REP BIGINT NOT NULL,
	VAL_SEQ BIGINT NOT NULL,
	VAL_REF JSON NOT NULL,
	PRIMARY KEY (SESSION_ID, REPLICA_ID, VAL_REP, VAL_SEQ),
	CONSTRAINT `GRID_VAL_INDEX_FK` FOREIGN KEY (SESSION_ID, REPLICA_ID, VAL_REP, VAL_SEQ) REFERENCES GRID_REPLICA_INDEX(SESSION_ID, REPLICA_ID, NODE_REP, NODE_SEQ) ON DELETE CASCADE
);