CREATE TABLE IF NOT EXISTS GRID_REPLICA_ARR (
	SESSION_ID BIGINT NOT NULL,
	REPLICA_ID BIGINT NOT NULL,
    CHUNK_REP BIGINT NOT NULL,
    CHUNK_SEQ BIGINT NOT NULL,
    NODE_REP BIGINT NOT NULL,
    NODE_SEQ BIGINT NOT NULL,
	PARENT_REP BIGINT,
    PARENT_SEQ BIGINT,
    TOMBSTONE BOOLEAN DEFAULT FALSE, -- on delete, set to true, indicating that the node was deleted.
	PRIMARY KEY (SESSION_ID, REPLICA_ID, CHUNK_REP, CHUNK_SEQ),
	INDEX (SESSION_ID, REPLICA_ID, PARENT_REP, PARENT_SEQ),
    CONSTRAINT `GRID_ARR_PARENT_FK` FOREIGN KEY (SESSION_ID, REPLICA_ID, PARENT_REP, PARENT_SEQ) REFERENCES GRID_REPLICA_ARR(SESSION_ID, REPLICA_ID, CHUNK_REP, CHUNK_SEQ) ON DELETE CASCADE,
	CONSTRAINT `GRID_ARR_NODE_INDEX_FK` FOREIGN KEY (SESSION_ID, REPLICA_ID, NODE_REP, NODE_SEQ) REFERENCES GRID_REPLICA_INDEX(SESSION_ID, REPLICA_ID, NODE_REP, NODE_SEQ) ON DELETE CASCADE
);