CREATE TABLE IF NOT EXISTS GRID_REPLICA_MESSAGE (
	SESSION_ID BIGINT NOT NULL,
	REPLICA_ID BIGINT NOT NULL,
	MESSAGE_ID MEDIUMINT NOT NULL,
	METHOD_NAME VARCHAR(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
	CREATED_ON TIMESTAMP(3) NOT NULL,
	PRIMARY KEY (SESSION_ID, REPLICA_ID, MESSAGE_ID),
	CONSTRAINT `GRID_MESSAGE_FK` FOREIGN KEY (SESSION_ID, REPLICA_ID) REFERENCES GRID_REPLICA(SESSION_ID, REPLICA_ID) ON DELETE CASCADE
)