CREATE TABLE IF NOT EXISTS GRID_REPLICA_ARR (
	SESSION_ID BIGINT NOT NULL,
	REPLICA_ID BIGINT NOT NULL,
    NODE_REP BIGINT NOT NULL,
    NODE_SEQ BIGINT NOT NULL,
    ARR_REP BIGINT NOT NULL,
    ARR_SEQ BIGINT NOT NULL,
	DATA_REP BIGINT,
    DATA_SEQ BIGINT,
	REF_REP BIGINT,
    REF_SEQ BIGINT,
    IS_DELETED BOOLEAN DEFAULT FALSE, -- on delete, set to true, indicating that the node was deleted.
	PRIMARY KEY (SESSION_ID, REPLICA_ID, ARR_REP, ARR_SEQ, NODE_REP, NODE_SEQ),
	UNIQUE INDEX (SESSION_ID, REPLICA_ID, ARR_REP, ARR_SEQ, REF_REP, REF_SEQ),
    CONSTRAINT `GRID_ARR_REPLICA_FK` FOREIGN KEY (SESSION_ID, REPLICA_ID) REFERENCES GRID_REPLICA(SESSION_ID, REPLICA_ID) ON DELETE CASCADE
);