CREATE TABLE IF NOT EXISTS `GRID_SESSION` (
  `ID` BIGINT NOT NULL,
  `ETAG` CHAR(36) NOT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `MODIFIED_ON` TIMESTAMP(3) NOT NULL,
  `SESSION_ID` CHAR(36) NOT NULL,
  `REP_ID_CLIENT` BIGINT NOT NULL,
  `REP_ID_SERVICE` BIGINT NOT NULL,
  `SOURCE_ID` BIGINT DEFAULT NULL,
  `SCHEMA_ID` varchar(600) CHARACTER SET ascii COLLATE ascii_general_ci DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `GRID_SESSION_ID` (`SESSION_ID`),
  CONSTRAINT `GRID_SES_USR_ID_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `GRID_SES_SRC_ID_FK` FOREIGN KEY (`SOURCE_ID`) REFERENCES `NODE` (`ID`) ON DELETE CASCADE
)
