CREATE TABLE IF NOT EXISTS `GRID_CONNECTION` (
  `ID` BIGINT NOT NULL,
  `CONNECTION_ID` CHAR(36) NOT NULL,
  `SESSION_ID` CHAR(36) NOT NULL,
  `REPLICA_ID` BIGINT NOT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `SOURCE` ENUM ('WEBSOCKET','INTERNAL','VALIDATION','AGENT','USER_SUPPORT','API','IMPORT'),
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `GRID_CON_SES_UNI` (`SESSION_ID`, `REPLICA_ID`),
  UNIQUE INDEX (`CONNECTION_ID`),
  CONSTRAINT `GRID_CON_IDS_FK` FOREIGN KEY (`SESSION_ID`,`REPLICA_ID`) REFERENCES `GRID_REPLICA` (`SESSION_ID`,`REPLICA_ID`) ON DELETE CASCADE,
  CONSTRAINT `GRID_CON_USR_ID_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE CASCADE
)