CREATE TABLE IF NOT EXISTS `GRID_REPLICA` (
  `ID` BIGINT NOT NULL,
  `REPLICA_ID` BIGINT NOT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `SESSION_ID` CHAR(36) NOT NULL,
  `IS_AGENT` BOOLEAN NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `GRID_REP_SES_UNI` (`SESSION_ID`, `REPLICA_ID`),
  CONSTRAINT `GRID_REP_SES_ID_FK` FOREIGN KEY (`SESSION_ID`) REFERENCES `GRID_SESSION` (`SESSION_ID`) ON DELETE CASCADE,
  CONSTRAINT `GRID_REP_USR_ID_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE CASCADE
)
