CREATE TABLE IF NOT EXISTS GRID_SNAPSHOT (
  `ID` BIGINT NOT NULL,
  `SESSION_ID` CHAR(36) NOT NULL,
  `CLOCK_TABLE` JSON NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `CREATED_BY` BIGINT,
  `S3_KEY` VARCHAR(700) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `GRID_SNAPSHOT_SESSION_ID_CREATED_ON_IDX` (`SESSION_ID`, `CREATED_ON`),
  CONSTRAINT `GRID_SNAPSHOT_SES_ID_FK` FOREIGN KEY (`SESSION_ID`) REFERENCES `GRID_SESSION` (`SESSION_ID`) ON DELETE CASCADE,
  CONSTRAINT `GRID_SNAPSHOT_CREATED_BY_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE CASCADE
);