CREATE TABLE IF NOT EXISTS `GRID_PATCH` (
  `ID` BIGINT NOT NULL,
  `SESSION_ID` CHAR(36) NOT NULL,
  `PATCH_ID_REP` BIGINT NOT NULL,
  `PATCH_ID_SEQ` BIGINT NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `EXPIRES_ON` TIMESTAMP(3) NOT NULL,
  `S3_KEY` VARCHAR(700) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  PRIMARY KEY `GRID_PAT_ID` (`ID`),
  UNIQUE INDEX `GRID_PAT_UNQ` (`SESSION_ID`,`PATCH_ID_REP`,`PATCH_ID_SEQ`),
  CONSTRAINT `GRID_PAT_SES_ID_FK` FOREIGN KEY (`SESSION_ID`) REFERENCES `GRID_SESSION` (`SESSION_ID`) ON DELETE CASCADE
)