package org.sagebionetworks.upload.multipart;

import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * DTO for a presigned URL generated by the cloud service
 * 
 * @author Marco Marasca
 *
 */
public class PresignedUrl {

	private URL url;
	private Map<String, String> signedHeaders;
	
	public URL getUrl() {
		return url;
	}
	
	public PresignedUrl withUrl(URL url) {
		this.url = url;
		return this;
	}
	
	public Map<String, String> getSignedHeaders() {
		return signedHeaders;
	}

	public PresignedUrl withSignedHeader(String key, String value) {
		if (signedHeaders == null) {
			signedHeaders = new HashMap<>();
		}
		signedHeaders.put(key, value);
		return this;
	}

	@Override
	public int hashCode() {
		return Objects.hash(signedHeaders, url);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		PresignedUrl other = (PresignedUrl) obj;
		return Objects.equals(signedHeaders, other.signedHeaders) && Objects.equals(url, other.url);
	}

	@Override
	public String toString() {
		return "PartPresignedUrl [url=" + url + ", signedHeaders=" + signedHeaders + "]";
	}
	
}
