package org.sagebionetworks.repo.manager.file.preview;

import static org.junit.Assert.*;

import java.io.BufferedInputStream;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FilenameFilter;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import javassist.bytecode.ByteArray;

import org.apache.commons.io.output.ByteArrayOutputStream;
import org.im4java.core.ConvertCmd;
import org.junit.Assume;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Ignore;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.sagebionetworks.repo.manager.S3TestUtils;
import org.sagebionetworks.repo.manager.UserManager;
import org.sagebionetworks.repo.manager.file.FileHandleManager;
import org.sagebionetworks.repo.model.dao.FileHandleDao;
import org.sagebionetworks.repo.model.file.FileHandle;
import org.sagebionetworks.repo.model.file.S3FileHandle;
import org.sagebionetworks.repo.web.ServiceUnavailableException;
import org.sagebionetworks.util.TestStreams;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.util.StreamUtils;

import com.amazonaws.services.s3.AmazonS3Client;
import com.amazonaws.services.s3.model.GetObjectRequest;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath:test-context.xml" })
public class OfficePreviewAutowireTest {
	private static final String TEST_DOC_GIF = "images/testdoc_result.gif";

	@Autowired
	private FileHandleManager fileUploadManager;

	@Autowired
	private PreviewManager previewManager;

	@Autowired
	public UserManager userManager;

	@Autowired
	private AmazonS3Client s3Client;

	@Autowired
	private FileHandleDao fileMetadataDao;

	@BeforeClass
	public static void beforeClass() throws Exception {
		try {
			OfficePreviewGenerator.initialize();
		} catch (FileNotFoundException e) {
			Assume.assumeNoException(e);
		} catch (Exception e) {
			throw e;
		}
	}

	@Before
	public void before() throws IOException, ServiceUnavailableException {
	}

	Object[][] files = {
			new Object[] { 4597270, "UIHC.OtherB.HandE.07.14.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4597222, "UIHC.CLL.HandE.2015.07.14.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4595650, "ASD_sample_and_RNAseq_metadata.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4595600, "2015.07.14.UIHC.HL.TMABLOCK.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4595553, "TMABLOCK Manifest.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4595552, "SLIDE.HandE.Manifest.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4595551, "LEO Pathology Block Fax Template.doc", "application/msword" },
			new Object[] { 4595550, "LEO Pathology Slides Fax Template.doc", "application/msword" },
			new Object[] { 4595132, "HS11_run3_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4595121, "HS01_run3_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4595100, "HS11_run3_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4595095, "HS11_run3_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4595091, "HS01_run3_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4595086, "HS01_run3_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4594189, "FINAL_PsychENCODE_RNA-seq pipelines_summary.xlsx (3).xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4594188, "FINAL_PsychENCODE_Regulatory regions_methods summary_5_14_15.xlsx (8).xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4594187, "FINAL_PsychENCODE_Regulatory regions pipelines_summary.xlsx (2).xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4594186, "FINAL_DataElements_SynapseRelease_July 2015.xlsx (3).xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4584854, "Hafner LINCS Talk_OHSU_Standards.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4584853, "Hafner LINCS Talk_OHSU_L1000.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4584851, "DREAM for LINCS Stolovitzky.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4584850, "DANE_LINCsMEP_MD.pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4584849, "CCC_LINCS_Presentation Foley, Intel.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4584842, "2015_05_18_LINCS Carpenter.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4584682, "spa150710_SYNODOS_Syn5_CUDC_Test_75coisolation_proteingroups.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4584672, "HS01_run3_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4584671, "HS11_run3_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4584662, "Package + Ship LEO Bloods v1 2015 04 27.doc", "application/msword" },
			new Object[] { 4584661, "Package & Ship LEO Bloods v1 2015 04 27.doc", "application/msword" },
			new Object[] { 4584660, "Package & Ship LEO Bloods v1 2015 04 27.doc", "application/msword" },
			new Object[] { 4584644, "URMC.Sample.Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4584643, "UofMiami.Sample.Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4584642, "Iowa.Sample.Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4584641, "MDAnderson.Sample.Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4584640, "Emory.Sample.Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4584639, "Cornell.Sample.Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4583730, "PsychENCODE membership list.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4561403, "Test file.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4560970, "MGH_NF2_mRNA_libraries.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4560943, "UCF_updates.pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4560941, "Gary Johnson synodos update.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4560550, "SynapseAuditReport_May2015.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4560513, "PsychENCODE Assay Workgroup Call_07-09-2015(Final)_NN-LAB.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4560505, "SynapseAuditReport_May2015.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4560495, "jhulieber-psychencode-20150708.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4560394, "NPC Data (received) Summary.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4560393, "DataFormats_Dobson.pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4560392, "ADBiomarkers_Legido.pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4560391, "ADBiomarkers_HyeSnowden.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4560390, "ADBiomarkers_Hye&Snowden.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4554472, "Suppl PRO- ACT data_fin.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4554458, "Suppl PRO- ACT data.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4554226, "Suppl PRO- ACT data_fin.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4554213, "Suppl PRO- ACT data.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4554157, "Synados_June8_OmicsMeeting.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4546354, "TouretteSyndrome_Demographic.Clinical_Metadata_S1 .xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4546175, "MS02_run3_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4546171, "MS02_run3_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4546169, "MS03_run3_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4546168, "MS03_run3_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4546167, "MS12_run3_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4546163, "MS12_run3_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4545919, "Suppl PRO- ACT data_fin.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4545906, "Suppl PRO- ACT data.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4545827, "ALS Stratification Challenge Webinar_ July 8 2015 v2.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4545815, "ALS Stratification Challenge Webinar_ July 8 2015 v2.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4545715, "Suppl PRO- ACT data_fin.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4545702, "Suppl PRO- ACT data.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4537526, "AM2015 Top-Rated Abstracts_MAI Indexing 7-2-15.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4528712, "PCDC_Webinar_7-6-15.pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4526759, "Writeup_06.07.2015.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4526754, "Wrtieup_30.06.2015.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4520726, "Q1A_Scores_V1.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4520571, "L34004_0001_GIMA_NGS_SM_150617_AC.xls", "application/vnd.ms-excel" },
			new Object[] { 4520570, "L26006_0001_SOPA_NGS_SM_150617_AC.xls", "application/vnd.ms-excel" },
			new Object[] { 4519929, "Supplementary information about predcitiors.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4505424, "Suppl PRO- ACT data_fin.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4497666, "468 PULVERIZED_DLPFC_CMC_BrainInfo.xls", "application/vnd.ms-excel" },
			new Object[] { 4497592, "TB Abstracts_Top 15 Percent.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4497591, "MCB Abstracts_Top 14 Percent.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4497590, "ET Abstracts_Top 17 Percent.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4497588, "CL Abstracts_Top 12 Percent.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4497587, "AM2015 Top-Rated Abstracts_MAI Indexing 7-2-15.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4487608, "RefusalNonResponder Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4487607, "RefusalNonResponder Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4487606, "RefusalNonResponder Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4477377, "PDMS-PrivacyPolicy-132589590.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4477367, "Challenge RUS_040215v2.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4477359, "SFBCS-dbGaP Collaboration Form 1-21-2015.doc", "application/msword" },
			new Object[] { 4477358, "phs000912_COL_DRAFT_5.28.2015.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4477324, "Challenge RUS_040215v2.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4477218, "Challenge RUS_040215v2.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4477210, "SFBCS-dbGaP Collaboration Form 1-21-2015.doc", "application/msword" },
			new Object[] { 4477209, "phs000912_COL_DRAFT_5.28.2015.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4477176, "Challenge RUS_040215v2.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4476403, "Challenge RUS_040215v2.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4476388, "SFBCS-dbGaP Collaboration Form 1-21-2015.doc", "application/msword" },
			new Object[] { 4476387, "phs000912_COL_DRAFT_5.28.2015.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4476337, "Challenge RUS_040215v2.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4475038, "150630_1b_1.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4475024, "GoldStandard_with_AffyIds.xls", "application/vnd.ms-excel" },
			new Object[] { 4460617, "WIRB-approved elements-Tracking.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4460588, "AppendixK-PDMS-Howthisworks-125454323.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4460586, "AppendixB-PDMS-AdvertisementFlier-121602633.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4460578, "RefusalNonResponder Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4460577, "RefusalNonResponder Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4460575, "RefusalNonResponder Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4460574, "RefusalNonResponder Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4460571, "RefusalNonResponder Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4460569, "RefusalNonResponder Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4460565, "RefusalNonResponder Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4460564, "17795505_InitialStudySurvey121625651AsSubmitted.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4460546, "17808653_Friend_ConsentFormU4_Rendition.doc", "application/msword" },
			new Object[] { 4440506, "5-AKESDREAM-LongTail-Julio.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4417694, "Challenge RUS_040215v2.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4417669, "SFBCS-dbGaP Collaboration Form 1-21-2015.doc", "application/msword" },
			new Object[] { 4417666, "phs000912_COL_DRAFT_5.28.2015.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4417587, "Challenge RUS_040215v2.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4417277, "Challenge RUS_040215v2.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4417252, "SFBCS-dbGaP Collaboration Form 1-21-2015.doc", "application/msword" },
			new Object[] { 4417250, "phs000912_COL_DRAFT_5.28.2015.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4417175, "Challenge RUS_040215v2.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4415736, "4-AKESDREAM-scoring-Pablo.ppt", "application/vnd.ms-powerpoint" },
			new Object[] { 4411950, "MS03_run2_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4411942, "MS03_run2_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4411932, "MS12_run2_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4411923, "MS12_run2_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4411915, "MS02_run2_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4411900, "MS02_run2_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4411898, "HS01_run2_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4411890, "HS01_run2_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4411882, "HS11_run2_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4411874, "HS11_run2_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4411481, "LEO CRF Packet FINAL-ish 20150626.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4411207, "UHIC.Tcell.HandE.06.26.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4411201, "UIHC.DLCBLC.HandE.06.26.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4411035, "UHIC.Tcell.HandE.06.11.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4411034, "UIHC.OtherB.HandE.06.11.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4411033, "UIHC.DLCBLC.HandE.06.11.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4399354, "4-AKESDREAM-scoring-Pablo.ppt", "application/vnd.ms-powerpoint" },
			new Object[] { 4399202, "UIHC.FL.HandE.06.25.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4399197, "4b-AKESDREAM-WisdomOfCrowds-Gustavo_revised.ppt", "application/vnd.ms-powerpoint" },
			new Object[] { 4399195, "1-AKESDREAM-Introduction-Gustavo-revised.ppt", "application/vnd.ms-powerpoint" },
			new Object[] { 4399152, "LEO-preliminaryTest.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4399120, "RefusalNonResponder Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4399119, "RefusalNonResponder Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4399118, "RefusalNonResponder Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4399117, "RefusalNonResponder Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4399112, "RefusalNonResponder Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4399110, "RefusalNonResponder Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4399105, "RefusalNonResponder Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4399096, "RefusalNonResponder Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4399093, "RefusalNonResponder Tracking.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4386396, "pathway_enrichment.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4386098, "B17020_0002_HUMI_NGS_ER_150601_AC.xls", "application/vnd.ms-excel" },
			new Object[] { 4385916, "PsychENCODE membership list.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4367311, "Suppl PRO- ACT data_fin.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4367289, "Suppl PRO- ACT data.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4366981, "4_5_Cell Plating and Treatment_8 well_SOP_v1.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4366716, "4_5_Cell Plating and Treatment_8 well_SOP_v0.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4366012, "2_Plate-preparation_SOP_v1.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4365971, "7_Image_acquisition_SOP_v1.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4365970, "6_Cell Staining_and_Imaging_SOP_v2.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4365969, "6_Cell Staining_and_Imaging_SOP_v1.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4365966, "3_Printing 8 well _A-P-01_1_06_11_2015_SOP v1.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4365961, "1_Protein_SOP_v1.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4365523, "Suppl PRO- ACT data_fin.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4365510, "Suppl PRO- ACT data.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4352680, "Suppl PRO- ACT data_fin.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4352669, "Suppl PRO- ACT data.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4352663, "PTLD.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4352623, "UIHC.HL.TMABLOCK.06.22.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4352407, "AD_SCZ_top_All_Info.xls", "application/vnd.ms-excel" },
			new Object[] { 4352406, "AD_SCZ_top_All_Info.xls", "application/vnd.ms-excel" },
			new Object[] { 4351600, "2015 Agenda LEO Operations.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4351599, "LEO Case Flow 2016 06 17.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4351598, "Manually assign LEO ID 20150622.doc", "application/msword" },
			new Object[] { 4351597, "Package & Ship LEO Bloods v1 2015 04 27.doc", "application/msword" },
			new Object[] { 4351596, "LEO Baseline Blood Draw and Sample Processingv1 2015 04 21.doc", "application/msword" },
			new Object[] { 4351595, "Manually assign LEO ID 20150622.doc", "application/msword" },
			new Object[] { 4351594, "WU Washington University LEO ID Manifest JULY 2015.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4351593, "WC Cornell University LEO ID Manifest JULY 2015.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4351592, "UR University of Rochester LEO ID Manifest JULY 2015.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4351591, "UM University of Miami LEO ID Manifest JULY 2015.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4351590, "MD MD Anderson LEO ID Manifest JULY 2015.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4351589, "MC Mayo LEO ID Manifest JULY 2015.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4351588, "IA University of Iowa LEO ID Manifest JULY 2015.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4351587, "EU Emory University LEO ID Manifest JULY 2015.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4351535, "LEO ID by site assigned 20150622.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4351534, "WU Washington University LEO ID Manifest JULY 2015.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4351533, "WC Cornell University LEO ID Manifest JULY 2015.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4351532, "UR University of Rochester LEO ID Manifest JULY 2015.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4351530, "MD MD Anderson LEO ID Manifest JULY 2015.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4351529, "MD MD Anderson LEO ID Manifest JULY 2015.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4351528, "MC Mayo LEO ID Manifest JULY 2015.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4351527, "IA University of Iowa LEO ID Manifest JULY 2015.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4351525, "EU Emory University LEO ID Manifest JULY 2015.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4342306, "Syn6_run2_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4342261, "Suppl PRO- ACT data_fin.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4329304, "AD_SCZ_top_All_Info.xls", "application/vnd.ms-excel" },
			new Object[] { 4329295, "Syn1_run2_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4329292, "Syn5_run2_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4329289, "Syn1_run2_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4329284, "Syn6_run2_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4329279, "Syn5_run2_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4318230, "softwaresummerschoolchemisty_assignment.xls", "application/vnd.ms-excel" },
			new Object[] { 4317978, "Suppl PRO- ACT data.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4317478, "CMC_DNAIsolationfromTRIzolSOP.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4317261, "PsychENCODE membership list.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4300964, "CT_gov all_id_studies with outcomes.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4300603, "Syn1_run2_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4300601, "Syn1_run2_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4300598, "Syn5_run2_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4299876, "LEO Baseline Blood Draw and Sample Processingv1 2015 04 21.doc", "application/msword" },
			new Object[] { 4299839, "LEO FFPE BLOCK Handling-Processing 2015 05 13 v1.doc", "application/msword" },
			new Object[] { 4299836, "LEO FFPE Process Flow 20150609lbejjl.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4299818, "LEO FFPE Process Flow 20150609lbe&jjl.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4299814, "TMABLOCK Manifest.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4299798, "LEO CRF Packet 2015 06 16.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4284297, "Suppl PRO- ACT data.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4265430, "FIMM_FO3D_MOLM14_Raw_Data.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4265428, "FIMM_FO3D_K562_Raw_Data.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4250777, "Challenge RUS_040215v2.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4250765, "SFBCS-dbGaP Collaboration Form 1-21-2015.doc", "application/msword" },
			new Object[] { 4250764, "phs000912_COL_DRAFT_5.28.2015.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4250696, "Challenge RUS_040215v2.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4250605, "PsychENCODE_AssaySubgroup_06-11-2015_Notes(Final)2.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4249640, "PsychENCODE_AssaySubgroup_06-11-2015_Notes(Final).docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4238490, "survivetimepre.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4238380, "coxphMPL_submit.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4215060, "Challenge RUS_040215v2.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4215052, "SFBCS-dbGaP Collaboration Form 1-21-2015.doc", "application/msword" },
			new Object[] { 4215051, "phs000912_COL_DRAFT_5.28.2015.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4214996, "Challenge RUS_040215v2.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4214913, "Challenge RUS_040215v2.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4214860, "OHSU_MarcTest123_v6_Phoenix_DA_02-03-15_K562_set3_MTS3_PAR1_4hr_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214859, "OHSU_MarcTest123_v6_Phoenix_DA_02-03-15_K562_set3_MTS3_ENV1_4hr_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214858, "OHSU_MarcTest123_v6_Phoenix_DA_01-27-15_K562_set2_MTS2_PAR1_1hr_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214857, "OHSU_MarcTest123_v6_Phoenix_DA_01-27-15_K562_set2_MTS2_ENV1_1hr_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214856, "OHSU_MarcTest123_v6_Phoenix_DA_01-20-15_K562_set1_MTS1_PAR1_1hr_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214855, "OHSU_MarcTest123_v6_Phoenix_DA_01-20-15_K562_set1_MTS1_ENV1_1hr_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214854, "OHSU_MarcTest123_v6_Phoenix_DA_02-03-15_MOLM14_set3_MTS3_PAR1_4hr_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214853, "OHSU_MarcTest123_v6_Phoenix_DA_02-03-15_MOLM14_set3_MTS3_ENV1_4hr_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214852, "OHSU_MarcTest123_v6_Phoenix_DA_01-27-15_MOLM14_set2_MTS2_PAR1_4hr_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214851, "OHSU_MarcTest123_v6_Phoenix_DA_01-27-15_MOLM14_set2_MTS2_ENV1_4hr_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214850, "OHSU_MarcTest123_v6_Phoenix_DA_01-20-15_MOLM14_set1_MTS1_PAR1_4hr_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214849, "OHSU_MarcTest123_v6_Phoenix_DA_01-20-15_MOLM14_set1_MTS1_ENV1_4hr_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214848, "OHSU_MarcTest123_v6_OHSU_KJ_06-09-15_Molm14-set2_CTG_BioTek_2hr RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214847, "OHSU_MarcTest123_v6_OHSU_KJ_06-09-15_Molm14-set1_CTG_BioTek_2hr RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214846, "OHSU_MarcTest123_v6_OHSU_KJ_03-23-15_Molm14-set3_MTS_BioTek_3hr RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214845, "OHSU_MarcTest123_v6_OHSU_KJ_03-23-15_Molm14-set2_MTS_BioTek_3hr RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214844, "OHSU_MarcTest123_v6_OHSU_KJ_03-23-15_Molm14-set1_MTS_BioTek_3hr RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214843, "OHSU_MarcTest123_v6_OHSU_KJ_03-23-15_K562-set3_MTS_BioTek_1hr RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214842, "OHSU_MarcTest123_v6_OHSU_KJ_03-23-15_K562-set2_MTS_BioTek_1hr RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214841, "OHSU_MarcTest123_v6_OHSU_KJ_03-23-15_K562-set1_MTS_BioTek_1hr RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214839, "OHSU_MarcTest123_v6_FIMM_SP_10-09-14_K562_screen02_MTS_Paradigm_HR_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214838, "OHSU_MarcTest123_v6_FIMM_SP_09-10-14_K562_screen02_CTxG_PHERAstar_HR_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214837, "OHSU_MarcTest123_v6_FIMM_SP_09-10-14_K562_screen02_CTG2_PHERAstar_HR_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214836, "OHSU_MarcTest123_v6_FIMM_SP_09-10-14_K562_screen02_CTG1_PHERAstar_HR_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214835, "OHSU_MarcTest123_v6_FIMM_SP_12-04-14_Molm14_screen05_MTS_Paradigm_HR_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214834, "OHSU_MarcTest123_v6_FIMM_SP_12-04-14_Molm14_screen05_CTxG_Pherastar_HR_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214833, "OHSU_MarcTest123_v6_FIMM_SP_12-04-14_Molm14_screen05_CTG2_Pherastar_HR_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214832, "OHSU_MarcTest123_v6_FIMM_SP_12-04-14_Molm14_screen05_CTG1_Pherastar_HR_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214831, "OHSU_MarcTest123_v6_FIMM_SP_11-13-14_Molm14_screen04_MTS_Paradigm_HR_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214830, "OHSU_MarcTest123_v6_FIMM_SP_11-13-14_Molm14_screen04_CTxG_Pherastar_HR_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214829, "OHSU_MarcTest123_v6_FIMM_SP_11-13-14_Molm14_screen04_CTG_Pherastar_HR_RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214826, "OHSU_MarcTest 123v6_FHCC_KT_05-18-15_K562_set3_MTS_BioTek_1hr RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214825, "OHSU_MarcTest 123v6_FHCC_KT_05-15-15_K562_set2_MTS_BioTek_1hr RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214824, "OHSU_MarcTest 123v6_FHCC_KT_05-14-15_Molm14_set3_MTS_BioTek_4hr RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214823, "OHSU_MarcTest 123v6_FHCC_KT_04-30-15_K562_set1_MTS_BioTek_2hr RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214822, "OHSU_MarcTest 123v6_FHCC_KT_04-27-15_Molm14_set2_MTS_BioTek_3.75hr RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214821, "OHSU_MarcTest 123v6_FHCC_KT_04-02-15_Molm14_set1_MTS_BioTek_3hr RAW.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4214763, "Challenge RUS_040215v2.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4200898, "Suppl PRO- ACT data.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4200875, "Suppl PRO- ACT data.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4200725, "UIHC.CLL.HandE.06.11.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4200721, "UIHC.CLL.HandE.06.11.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4200718, "UIHC.CLL.HandE.06.11.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4200717, "UIHC.FL.HandE.06.11.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4200709, "UIHC.FL.HandE.06.11.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4200687, "UIHC.HL.HandE.06.11.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4200515, "UIHC.MCL.TMABLOCK.06.11.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4200406, "UIHC.MCL.HandE.06.11.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4200399, "UIHC.BL.TMABLOCK.06.11.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4200398, "UIHC.BL.HandE.06.11.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4200393, "UIHC.BL.TMABLOCK.06.11.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4200390, "UIHC.BL.HandE.06.11.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4200309, "UIHC.BL.TMABLOCK.06.11.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4199692, "UIHC.BL.TMABLOCK.06.11.2015jjl.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4199682, "UIHC.BL.TMABLOCK.06.11.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4199681, "UIHC.BL.HandE.06.11.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4199678, "UIHC.BL.H&E.06.11.2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4199668, "CMC-BPD_Pitt_06-10-2015.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4199665, "LEO Protocol Elements.pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4199664, "LEO Legal Agreements.pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 4199643, "KIRP_histology_cluster_assignments-FINAL.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4199640, "KIRP_mRNA_cluster_assignments-FINAL.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4199631, "KICH_subtypes_6-11-15.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4199625, "TCGA_ccA_ccB_Clearcode_annotation_6-11-15.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4134294, "Knowledge_database_v12.0.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4087604, "Sample_List_Freeze_v1_1.0_Annotations_Merged_5-28-15.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4087597, "Sample_List_Freeze_v1_1 0_Annotations_Merged_5-18-15_BCCA_FINAL.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4087422, "CMC_DNAIsolationfromTRIzolSOP.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4051481, "HS11_run1_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4051478, "HS11_run1_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4051475, "HS01_run1_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4051472, "HS01_run1_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4051469, "MS03_run1_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4051466, "MS03_run1_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4022118, "ON_FacilitiesAndOtherResources.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4022116, "ON_Equipment.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4022114, "ON_BudgetJustification.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4022111, "Nikolova_SOW_5-2015.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4022110, "Nikolova_NIH_Biosketch_2015_06_v4.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4022099, "Suppplemental_Figures.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4022094, "2015_06_R01_Proposal.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4022088, "TCGA_GISTIC_GROUPED_BY_SUBTYPE.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4022086, "TCGA_BRCA_mutation_table_CTCF.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4022081, "TCGA_BRCA_CTCF_CN_BINNED_MUT_DATA.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4022079, "CCLE_BREAST_CELL_LINES_SUBTYPE.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4022075, "CCLE_ALL_CELL_LINES_SUBTYPE.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 4019443, "Challenge RUS_040215v2.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 4018245, "PE_Executive Committee_06-01-2015_Notes(FINAL)2.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 3985682, "phs000912_COL_DRAFT_5.28.2015.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 3985057, "L24006_0001_ARMA_NGS_IB_150520_AC.xls", "application/vnd.ms-excel" },
			new Object[] { 3985056, "L06004_0001_TRAX_NGS_IB_150520_AC.xls", "application/vnd.ms-excel" },
			new Object[] { 3985055, "B17015_0001_MAAN_NGS_IB_150518_AC.xls", "application/vnd.ms-excel" },
			new Object[] { 3970519, "CT_gov all_id_studies.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3970485, "Figures_hla_3June15_ver3_AChess.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 3970350, "CMC_isoforms_dk_3Jun2015.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 3970185, "LAP+AKT-GI-values-readme.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 3970180, "5-27-15_GI-summary-values.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3970139, "LAP+AKT-GI-values.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 3970066, "CMC_isoforms_dk_3Jun2015.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 3970051, "KIRC_Data_file_S9_mRNA_miRNA_cluster_assignments.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3970044, "KIRC_mRNA_subtyping_analysis_Data_file_S5_mRNA-supplemental-table.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3970014, "KIRP_compiled_clinical_molecular_features_for_supp_012715.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3970013, "LIHC_freeze_cases_compiled_clinical_molecular_annotation_051415b.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3970008, "B17018_0001_MAMI_NGS_CC_150504_AC.xls", "application/vnd.ms-excel" },
			new Object[] { 3961097, "Challenge RUS.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 3960829, "GWAS Autopsy Cases 06-2015.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3960631, "LEO_baseline blood manifest.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3951751, "Interest Gene List for CMC analysis v2.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3951750, "Interest Gene list in AD 2015.05 final.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3951296, "Copy of Site.EXAMPLE.SLIDE.HE.Manifest.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3951294, "Copy of Site.EXAMPLE.SLIDE.H&E.Manifest.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3951258, "May292015.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 3941744, "CCLE_BREAST_CELL_LINES_SUBTYPE.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3941743, "CCLE_ALL_CELL_LINES_SUBTYPE.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3941742, "TCGA_GISTIC_GROUPED_BY_SUBTYPE.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3941741, "TCGA_BRCA_mutation_table_CTCF.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3941740, "TCGA_BRCA_CTCF_CN_BINNED_MUT_DATA.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3941736, "Suppplemental_Figures.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 3915997, "PAAD_sample_table_for_TCGA_22May2015.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3915903, "PEC_DataSharing_Milestones_05-2015_GS1-LAB-2.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3915755, "Challenge RUS_040215v2.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 3915748, "Challenge RUS_040215v2.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 3890148, "statisticalNetworkTheory.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 3888263, "TCGA_BLCA_129samples_nature2014_chan_clusters.xls", "application/vnd.ms-excel" },
			new Object[] { 3888253, "MDA_discovery_chan_clusters.xls", "application/vnd.ms-excel" },
			new Object[] { 3888239, "GSE32894_Chan_clusters.xls", "application/vnd.ms-excel" },
			new Object[] { 3872134, "Takeda_Sage_update_May27.2015.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 3871986, "Copy of LEO Site Manifest Basline Draw Template.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3871929, "SFBCS-dbGaP Collaboration Form 1-21-2015.doc", "application/msword" },
			new Object[] { 3871924, "SFBCS-dbGaP Collaboration Form 1-21-2015.doc", "application/msword" },
			new Object[] { 3871627, "PDAC Analysis.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3871626, "Human Ig ELISA.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3871625, "AG1.3 histology analysis.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3871624, "AG1_7 CD45.xls", "application/vnd.ms-excel" },
			new Object[] { 3871617, "VIP Project-CyTOF-Plate 1 of 1-01.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3871616, "Flu 18-2011-HumanLuminex51plex-07.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3871611, "Immune monitoring for ADU-CL-01-HumanLuminex51plex-Plate003-01.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3871610, "Immune monitoring for ADU-CL-01-HumanLuminex51plex-Plate001-01 (1).xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3871479, "AACR_am_abs_mai.xls", "application/vnd.ms-excel" },
			new Object[] { 3861355, "MS12_run1_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3861354, "MS12_run1_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3861353, "MS02_run1_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3861352, "MS02_run1_CUDC_and_Pano_kinome.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3861351, "DavyKavanagh_h3k27ac_downsampling_22May2015.pptx",
					"application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 3860982, "LEO pathology request fax template.doc", "application/msword" },
			new Object[] { 3860981, "Site.EXAMPLE.SLIDE.HandE.Manifest.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3860978, "Site.EXAMPLE.SLIDE.HandE.Manifest.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3860977, "Site.EXAMPLE.SLIDE.HandE.Manifest.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3860976, "Site.EXAMPLE.SLIDE.HandE.Manifest.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3860975, "Site.EXAMPLE.SLIDE.HandE.Manifest.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3860974, "Site.EXAMPLE.SLIDE.HandE.Manifest.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3860973, "Site.EXAMPLE.SLIDE.HandE.Manifest.xlsx",
					"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3860968, "TMABLOCK Manifest.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3860962, "SLIDE.HandE.Manifest.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3860960, "SLIDEH&E Manifest.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3860959, "SLIDEH&E Manifest.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3860735, "L35003_0001_FOJE_NGS_CC_150429_AC.xls", "application/vnd.ms-excel" },
			new Object[] { 3860734, "B17019_0001_MABR_NGS_CC_150504_AC.xls", "application/vnd.ms-excel" },
			new Object[] { 3860733, "B17018_0001_MABR_NGS_CC_150504_AC.xls", "application/vnd.ms-excel" },
			new Object[] { 3860732, "B17017_0001_ANCH_NGS_CC_150504_AC.xls", "application/vnd.ms-excel" },
			new Object[] { 3854011, "TNM_b_descriptive.pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
			new Object[] { 3854010, "TNM_b.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3827722, "AppendixB-BCS-AboutthisStudy-128332090.docx",
					"application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
			new Object[] { 3825511, "PsychENCODE membership list.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
			new Object[] { 3778943, "Syn6_run1_GSK458_kinome.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" } };

	@Test
	public void testMany() throws Exception {
		OfficePreviewGenerator officePreviewGenerator = new OfficePreviewGenerator();

		File indir = new File("C:/cygwin64/home/mblonk/tmp/docin");
		File outdir = new File("C:/cygwin64/home/mblonk/tmp/docout");
		for (Object[] file : files) {
			int id = (Integer) file[0];
			String name = (String) file[1];
			String content_type = (String) file[2];
			assertTrue(officePreviewGenerator.supportsContentType(content_type, PreviewGeneratorUtils.findExtension(name)));
			File f = new File(indir, "" + id);
			File fout = new File(outdir, id + ".gif");
			assertTrue(f.exists());
			if (!fout.exists()) {
				System.out.println(name);
				InputStream in = new FileInputStream(f);
				OutputStream out = new FileOutputStream(fout);
				try {
					officePreviewGenerator.generatePreview(in, out);
				} catch (RuntimeException e) {
					e.printStackTrace();
					out.close();
					fout.delete();
				}
				in.close();
				out.close();
			}
		}
	}
}
