CREATE TABLE IF NOT EXISTS `PORTAL` (
  `ID` BIGINT NOT NULL,
  `ETAG` CHAR(36) NOT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `MODIFIED_BY` BIGINT NOT NULL,
  `MODIFIED_ON` TIMESTAMP(3) NOT NULL,
  `NAME` VARCHAR(256) NOT NULL,
  `ENDPOINT` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE (`NAME`),
  UNIQUE (`ENDPOINT`),
  CONSTRAINT `PORTAL_CREATED_BY_FK` FOREIGN KEY (`CREATED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE RESTRICT,
  CONSTRAINT `PORTAL_MODIFIED_BY_ID_FK` FOREIGN KEY (`MODIFIED_BY`) REFERENCES `USER_GROUP` (`ID`) ON DELETE RESTRICT
)
