package org.sagebionetworks.repo.manager.table;

import org.sagebionetworks.repo.model.table.FacetColumnResult;
import org.sagebionetworks.repo.model.table.RowSet;
import org.sagebionetworks.table.cluster.SqlQuery;

/**
 * An interface for classes that generates SQL necessary to obtain facet information and converts the SQL result from that query to a FacetColumnResult
 * @author zdong
 *
 */
public interface FacetTransformer {
	
	/**
	 * Returns the name of the column for which this transformer is responsible.
	 * @return
	 */
	public String getColumnName();
	
	/**
	 * Generates a new Query to get facet information based on the original query
	 * @param originalQuery
	 * @return
	 */
	public SqlQuery getFacetSqlQuery();
	
	/**
	 * translates the result obtained after running the query generated by generateSqlQuery()
	 * @param rowSet
	 * @return
	 */
	public FacetColumnResult translateToResult(RowSet rowSet);
}
