WITH DELTAS (ID, MISSING) AS ( 
	SELECT R.OBJECT_ID, V.ROW_ID FROM OBJECT_REPLICATION R 
		LEFT JOIN %1$s V ON ( R.OBJECT_ID = V.ROW_ID AND R.ETAG = V.ROW_ETAG AND R.BENEFACTOR_ID = V.ROW_BENEFACTOR)
        	WHERE %2$s
UNION ALL
	SELECT V.ROW_ID, R.OBJECT_ID FROM OBJECT_REPLICATION R 
		RIGHT JOIN %1$s V ON ( R.OBJECT_ID = V.ROW_ID AND R.ETAG = V.ROW_ETAG AND R.BENEFACTOR_ID = V.ROW_BENEFACTOR 
			AND %2$s )
)
SELECT ID FROM DELTAS WHERE MISSING IS NULL ORDER BY ID DESC LIMIT :pLimit