SELECT 
	A.ANNO_KEY,
    GROUP_CONCAT(DISTINCT A.ANNO_TYPE),
    MAX(MAX_STRING_LENGTH),
    MAX(LIST_LENGTH)
		FROM OBJECT_REPLICATION AS R
			INNER JOIN ANNOTATION_REPLICATION AS A ON (R.OBJECT_TYPE = A.OBJECT_TYPE AND R.OBJECT_ID = A.OBJECT_ID AND R.OBJECT_VERSION = A.OBJECT_VERSION)
				WHERE %1$s %2$s
        GROUP BY A.ANNO_KEY LIMIT :pLimit OFFSET :pOffset