/* adder.jj Adding up numbers */
options
{
STATIC = false;
}
PARSER_BEGIN(Adder)
	class Adder {
		public static void main( String[] args ) throws ParseException, TokenMgrError {
			Adder parser = new Adder( System.in );
			parser.Start();
		}
	}
PARSER_END(Adder)

SKIP :{" "}
SKIP :{"\n" | "\r" | "\r\n"}
TOKEN : { <PLUS: "+"> }
TOKEN : { <NUMBER: (["0"-"9"])+> }

void Start():
{}
{
	<NUMBER>(<PLUS><NUMBER>)*<EOF>
}