CREATE TABLE IF NOT EXISTS QUERY_CACHE (
	REQUEST_HASH VARCHAR(64) NOT NULL,
	REQUEST JSON NOT NULL,
	RESULTS JSON NOT NULL,
	EXPIRES_ON TIMESTAMP NOT NULL,
	RUNTIME_MS BIGINT NOT NULL,
	PRIMARY KEY(REQUEST_HASH)
)