CREATE TABLE IF NOT EXISTS REPLICATION_SYNC_EXPIRATION (
    OBJECT_TYPE ENUM('SUBMISSION', 'ENTITY') NOT NULL,
    OBJECT_ID BIGINT NOT NULL,
    EXPIRES_MS BIGINT NOT NULL,
    PRIMARY KEY (OBJECT_ID , OBJECT_TYPE)
)