CREATE TABLE IF NOT EXISTS SEARCH_INDEX_STATUS (
	SEARCH_INDEX_ID BIGINT NOT NULL,
	STATE ENUM('CREATING','ACTIVE','FAILED','WAITING_FOR_SOURCE') NOT NULL DEFAULT 'CREATING',
	ERROR_MESSAGE VARCHAR(3000) DEFAULT NULL,
	CHANGED_ON TIMESTAMP(3) NOT NULL,
	PRIMARY KEY (SEARCH_INDEX_ID)
)
