CREATE TABLE IF NOT EXISTS VIEW_SCOPE (
    VIEW_ID BIGINT NOT NULL,
    OBJECT_TYPE ENUM('SUBMISSION', 'ENTITY') NOT NULL,
    OBJECT_IDS JSON NOT NULL,
   	IDS_HASH VARCHAR(64) NOT NULL,
    PRIMARY KEY (VIEW_ID, OBJECT_TYPE),
    INDEX ob_ids(OBJECT_TYPE, (CAST(OBJECT_IDS->'$' AS UNSIGNED ARRAY)))
)